import type { Module } from '@/types'

const module: Module = {
  slug: 'asking-questions',
  track: 'esl',
  titleEn: 'Asking Questions',
  titleEs: 'Cómo Hacer Preguntas',
  descriptionEn: 'Learn how to ask who, what, where, when, why, and how — and ask politely for help.',
  descriptionEs: 'Aprende a preguntar quién, qué, dónde, cuándo, por qué y cómo — y a pedir ayuda cortésmente.',
  icon: 'HelpCircle',
  vocab: [
    { id: 'who', en: 'who', es: 'quién',
      exampleEn: 'Who is that?', exampleEs: '¿Quién es ese?' },
    { id: 'what', en: 'what', es: 'qué',
      exampleEn: 'What is this?', exampleEs: '¿Qué es esto?' },
    { id: 'where', en: 'where', es: 'dónde',
      exampleEn: 'Where do you live?', exampleEs: '¿Dónde vives?' },
    { id: 'when', en: 'when', es: 'cuándo',
      exampleEn: 'When is your appointment?', exampleEs: '¿Cuándo es tu cita?' },
    { id: 'why', en: 'why', es: 'por qué',
      exampleEn: 'Why are you late?', exampleEs: '¿Por qué llegas tarde?' },
    { id: 'how', en: 'how', es: 'cómo',
      exampleEn: 'How do you say this in English?', exampleEs: '¿Cómo se dice esto en inglés?' },
    { id: 'how-much', en: 'how much', es: 'cuánto',
      exampleEn: 'How much is this?', exampleEs: '¿Cuánto cuesta esto?' },
    { id: 'how-many', en: 'how many', es: 'cuántos',
      exampleEn: 'How many children do you have?', exampleEs: '¿Cuántos hijos tienes?' },
    { id: 'can-you', en: 'Can you help me?', es: '¿Puedes ayudarme?',
      exampleEn: 'Excuse me, can you help me?', exampleEs: 'Disculpe, ¿puedes ayudarme?' },
    { id: 'could-you-please-help-me', en: 'Could you please help me?', es: '¿Podría ayudarme, por favor?',
      exampleEn: 'Could you please help me fill out this form?', exampleEs: '¿Podría ayudarme a llenar este formulario, por favor?' },
    { id: 'do-you', en: 'Do you speak Spanish?', es: '¿Hablas español?',
      exampleEn: 'Excuse me, do you speak Spanish?', exampleEs: 'Disculpe, ¿habla español?' },
    { id: 'is-it', en: 'Is it far from here?', es: '¿Está lejos de aquí?',
      exampleEn: 'Is it far from here?', exampleEs: '¿Está lejos de aquí?' },
    { id: 'what-time-is-it', en: 'What time is it?', es: '¿Qué hora es?',
      exampleEn: 'Excuse me, what time is it?', exampleEs: 'Disculpe, ¿qué hora es?' },
    { id: 'where-is-the', en: 'Where is the...?', es: '¿Dónde está el/la...?',
      exampleEn: 'Excuse me, where is the bathroom?', exampleEs: 'Disculpe, ¿dónde está el baño?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"¿Dónde?" in English is:', promptEs: '"¿Dónde?" en inglés es:',
      answer: 'Where', options: ['Where', 'When', 'Who', 'Why'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"¿Cuándo?" in English is:', promptEs: '"¿Cuándo?" en inglés es:',
      answer: 'When', options: ['When', 'Where', 'What', 'How'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Which words do you use to ask a price?', promptEs: '¿Qué palabras usas para preguntar un precio?',
      answer: 'How much', options: ['How much', 'How many', 'What time', 'Where'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ is your name?"', promptEs: 'Completa: "___ is your name?"',
      answer: 'What', options: ['What', 'Who', 'Where', 'When'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you politely ask for help?', promptEs: '¿Cómo pides ayuda cortésmente?',
      answer: 'Could you please help me?', options: ['Could you please help me?', 'Where is the bathroom?', 'What time is it?', 'Why are you late?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Basic questions when meeting someone or feeling lost',
      text: 'Practice asking basic questions like "Who is that?", "What is this?", and "Where do you live?" in a conversation.',
      script: [
        { speaker: 'tutor', en: "Let's practice meeting someone new. Imagine we just met at a party. Who is that over there?", es: 'Practiquemos conocer a alguien nuevo. Imagina que nos acabamos de conocer en una fiesta. ¿Quién es ese de allá?' },
        { speaker: 'student', en: 'Who is that?', es: '¿Quién es ese?' },
        { speaker: 'tutor', en: "That's my neighbor. Now imagine you see something you don't recognize on the table.", es: 'Ese es mi vecino. Ahora imagina que ves algo que no reconoces en la mesa.' },
        { speaker: 'student', en: 'What is this?', es: '¿Qué es esto?' },
        { speaker: 'tutor', en: "Good question! Now let's say you're lost in a new neighborhood and want to know where I live.", es: '¡Buena pregunta! Ahora digamos que estás perdido en un vecindario nuevo y quieres saber dónde vivo.' },
        { speaker: 'student', en: 'Where do you live?', es: '¿Dónde vives?' },
        { speaker: 'tutor', en: 'I live nearby. What if you needed to know when your appointment is?', es: 'Vivo cerca. ¿Qué tal si necesitaras saber cuándo es tu cita?' },
        { speaker: 'student', en: 'When is your appointment?', es: '¿Cuándo es tu cita?' },
        { speaker: 'tutor', en: 'Perfect, and if someone is late, you could ask why.', es: 'Perfecto, y si alguien llega tarde, podrías preguntar por qué.' },
        { speaker: 'student', en: 'Why are you late?', es: '¿Por qué llegas tarde?' },
        { speaker: 'tutor', en: 'Excellent! You now have who, what, where, and when ready for any conversation.', es: '¡Excelente! Ahora tienes quién, qué, dónde y cuándo listos para cualquier conversación.' },
      ] },
    { label: 'Part 2: Asking about prices and quantities',
      text: 'You are shopping and need to ask how much something costs and how many of something you can buy.',
      script: [
        { speaker: 'tutor', en: "I'm the cashier today. Welcome to the store! How can I help you?", es: 'Soy el cajero hoy. ¡Bienvenido a la tienda! ¿Cómo puedo ayudarte?' },
        { speaker: 'student', en: 'How much is this?', es: '¿Cuánto cuesta esto?' },
        { speaker: 'tutor', en: "It's five dollars. Are you buying more than one?", es: 'Cuesta cinco dólares. ¿Vas a comprar más de uno?' },
        { speaker: 'student', en: 'How many can I buy?', es: '¿Cuántos puedo comprar?' },
        { speaker: 'tutor', en: 'You can buy as many as you like! Do you have children, by the way?', es: '¡Puedes comprar tantos como quieras! Por cierto, ¿tienes hijos?' },
        { speaker: 'student', en: 'How many children do you have?', es: '¿Cuántos hijos tienes?' },
        { speaker: 'tutor', en: 'I have two! Now, is the pharmacy far from here?', es: '¡Tengo dos! Ahora, ¿la farmacia está lejos de aquí?' },
        { speaker: 'student', en: 'Is it far from here?', es: '¿Está lejos de aquí?' },
        { speaker: 'tutor', en: 'No, just two blocks. Do you know what time it is, by chance?', es: 'No, solo dos cuadras. ¿Sabes qué hora es, por casualidad?' },
        { speaker: 'student', en: 'What time is it?', es: '¿Qué hora es?' },
        { speaker: 'tutor', en: 'It\'s almost closing time. Great job asking about prices and quantities today!', es: 'Ya casi es hora de cerrar. ¡Buen trabajo preguntando sobre precios y cantidades hoy!' },
      ] },
    { label: 'Part 3: Politely asking for help',
      text: 'You need help with a form or directions. Practice "Can you help me?", "Could you please help me?", and asking if someone speaks Spanish.',
      script: [
        { speaker: 'tutor', en: "Let's imagine you need help with a form at an office. I'll be the clerk.", es: 'Imaginemos que necesitas ayuda con un formulario en una oficina. Yo seré el empleado.' },
        { speaker: 'student', en: 'Excuse me, can you help me?', es: 'Disculpe, ¿puedes ayudarme?' },
        { speaker: 'tutor', en: 'Of course. What do you need?', es: 'Claro. ¿Qué necesitas?' },
        { speaker: 'student', en: 'Could you please help me fill out this form?', es: '¿Podría ayudarme a llenar este formulario, por favor?' },
        { speaker: 'tutor', en: 'Yes, I can help with that. Do you need directions somewhere too?', es: 'Sí, puedo ayudarte con eso. ¿También necesitas indicaciones a algún lugar?' },
        { speaker: 'student', en: 'Where is the bathroom?', es: '¿Dónde está el baño?' },
        { speaker: 'tutor', en: 'It\'s down the hall. Is there anything else?', es: 'Está al final del pasillo. ¿Hay algo más?' },
        { speaker: 'student', en: 'Excuse me, do you speak Spanish?', es: 'Disculpe, ¿habla español?' },
        { speaker: 'tutor', en: 'A little bit! Between English and Spanish, we\'ll understand each other just fine.', es: 'Un poco. Entre inglés y español, nos entenderemos bien.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ is your name?', promptEs: '¿Cómo te llamas? (____ is your name?)', answer: 'What' },
    { id: 'w2', promptEn: '____ do you live?', promptEs: '¿Dónde vives? (____ do you live?)', answer: 'Where' },
    { id: 'w3', promptEn: '____ much does this cost?', promptEs: '¿Cuánto cuesta esto? (____ much does this cost?)', answer: 'How' },
    { id: 'w4', promptEn: '____ you help me?', promptEs: '¿Puedes ayudarme? (____ you help me?)', answer: 'Can' },
    { id: 'w5', promptEn: '____ time is it?', promptEs: '¿Qué hora es? (____ time is it?)', answer: 'What' },
  ],
}

export default module
