import type { Module } from '@/types'

const module: Module = {
  slug: 'asking-questions',
  track: 'esl',
  titleEn: 'Asking Questions',
  titleEs: 'Cómo Hacer Preguntas',
  descriptionEn: 'Learn how to ask who, what, where, when, why, and how — and ask politely for help.',
  descriptionEs: 'Aprende a preguntar quién, qué, dónde, cuándo, por qué y cómo — y a pedir ayuda cortésmente.',
  icon: 'HelpCircle',
  vocab: [
    { id: 'who', en: 'who', es: 'quién',
      exampleEn: 'Who is that?', exampleEs: '¿Quién es ese?' },
    { id: 'what', en: 'what', es: 'qué',
      exampleEn: 'What is this?', exampleEs: '¿Qué es esto?' },
    { id: 'where', en: 'where', es: 'dónde',
      exampleEn: 'Where do you live?', exampleEs: '¿Dónde vives?' },
    { id: 'when', en: 'when', es: 'cuándo',
      exampleEn: 'When is your appointment?', exampleEs: '¿Cuándo es tu cita?' },
    { id: 'why', en: 'why', es: 'por qué',
      exampleEn: 'Why are you late?', exampleEs: '¿Por qué llegas tarde?' },
    { id: 'how', en: 'how', es: 'cómo',
      exampleEn: 'How do you say this in English?', exampleEs: '¿Cómo se dice esto en inglés?' },
    { id: 'how-much', en: 'how much', es: 'cuánto',
      exampleEn: 'How much is this?', exampleEs: '¿Cuánto cuesta esto?' },
    { id: 'how-many', en: 'how many', es: 'cuántos',
      exampleEn: 'How many children do you have?', exampleEs: '¿Cuántos hijos tienes?' },
    { id: 'can-you', en: 'Can you help me?', es: '¿Puedes ayudarme?',
      exampleEn: 'Excuse me, can you help me?', exampleEs: 'Disculpe, ¿puedes ayudarme?' },
    { id: 'could-you-please-help-me', en: 'Could you please help me?', es: '¿Podría ayudarme, por favor?',
      exampleEn: 'Could you please help me fill out this form?', exampleEs: '¿Podría ayudarme a llenar este formulario, por favor?' },
    { id: 'do-you', en: 'Do you speak Spanish?', es: '¿Hablas español?',
      exampleEn: 'Excuse me, do you speak Spanish?', exampleEs: 'Disculpe, ¿habla español?' },
    { id: 'is-it', en: 'Is it far from here?', es: '¿Está lejos de aquí?',
      exampleEn: 'Is it far from here?', exampleEs: '¿Está lejos de aquí?' },
    { id: 'what-time-is-it', en: 'What time is it?', es: '¿Qué hora es?',
      exampleEn: 'Excuse me, what time is it?', exampleEs: 'Disculpe, ¿qué hora es?' },
    { id: 'where-is-the', en: 'Where is the...?', es: '¿Dónde está el/la...?',
      exampleEn: 'Excuse me, where is the bathroom?', exampleEs: 'Disculpe, ¿dónde está el baño?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"¿Dónde?" in English is:', promptEs: '"¿Dónde?" en inglés es:',
      answer: 'Where', options: ['Where', 'When', 'Who', 'Why'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"¿Cuándo?" in English is:', promptEs: '"¿Cuándo?" en inglés es:',
      answer: 'When', options: ['When', 'Where', 'What', 'How'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Which words do you use to ask a price?', promptEs: '¿Qué palabras usas para preguntar un precio?',
      answer: 'How much', options: ['How much', 'How many', 'What time', 'Where'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ is your name?"', promptEs: 'Completa: "___ is your name?"',
      answer: 'What', options: ['What', 'Who', 'Where', 'When'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you politely ask for help?', promptEs: '¿Cómo pides ayuda cortésmente?',
      answer: 'Could you please help me?', options: ['Could you please help me?', 'Where is the bathroom?', 'What time is it?', 'Why are you late?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Basic questions when meeting someone or feeling lost',
      text: 'Practice asking basic questions like "Who is that?", "What is this?", and "Where do you live?" in a conversation.' },
    { label: 'Part 2: Asking about prices and quantities',
      text: 'You are shopping and need to ask how much something costs and how many of something you can buy.' },
    { label: 'Part 3: Politely asking for help',
      text: 'You need help with a form or directions. Practice "Can you help me?", "Could you please help me?", and asking if someone speaks Spanish.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ is your name?', promptEs: '¿Cómo te llamas? (____ is your name?)', answer: 'What' },
    { id: 'w2', promptEn: '____ do you live?', promptEs: '¿Dónde vives? (____ do you live?)', answer: 'Where' },
    { id: 'w3', promptEn: '____ much does this cost?', promptEs: '¿Cuánto cuesta esto? (____ much does this cost?)', answer: 'How' },
    { id: 'w4', promptEn: '____ you help me?', promptEs: '¿Puedes ayudarme? (____ you help me?)', answer: 'Can' },
    { id: 'w5', promptEn: '____ time is it?', promptEs: '¿Qué hora es? (____ time is it?)', answer: 'What' },
  ],
}

export default module
