import type { Module } from '@/types'

const module: Module = {
  slug: 'buying-clothes',
  track: 'esl',
  titleEn: 'Buying Clothes',
  titleEs: 'Comprar Ropa',
  descriptionEn: 'Learn how to shop for clothes and ask for help at a store.',
  descriptionEs: 'Aprende a comprar ropa y pedir ayuda en una tienda.',
  icon: 'Shirt',
  vocab: [
    {
      id: 'size',
      en: 'size',
      es: 'la talla / el tamaño',
      exampleEn: 'What size do you wear?',
      exampleEs: '¿Qué talla usas?',
    },
    {
      id: 'fitting-room',
      en: 'fitting room',
      es: 'el probador',
      exampleEn: 'Can I use the fitting room to try this on?',
      exampleEs: '¿Puedo usar el probador para probarme esto?',
    },
    {
      id: 'too-big-small',
      en: 'too big / too small',
      es: 'muy grande / muy pequeño',
      exampleEn: 'This shirt is too big. Do you have a smaller size?',
      exampleEs: 'Esta camisa es muy grande. ¿Tiene una talla más pequeña?',
    },
    {
      id: 'do-you-have',
      en: 'Do you have this in...?',
      es: '¿Tiene esto en...?',
      exampleEn: 'Do you have this in blue? Do you have this in a size medium?',
      exampleEs: '¿Tiene esto en azul? ¿Tiene esto en talla mediana?',
    },
    {
      id: 'return',
      en: 'return / exchange',
      es: 'devolver / cambiar',
      exampleEn: 'I would like to return this shirt, please.',
      exampleEs: 'Me gustaría devolver esta camisa, por favor.',
    },
    {
      id: 'discount',
      en: 'discount',
      es: 'el descuento',
      exampleEn: 'Is there a discount on these shoes?',
      exampleEs: '¿Hay algún descuento en estos zapatos?',
    },
    {
      id: 'try-on',
      en: 'try on',
      es: 'probarse',
      exampleEn: 'Can I try on this jacket?',
      exampleEs: '¿Me puedo probar esta chaqueta?',
    },
    {
      id: 'i-am-looking-for',
      en: 'I am looking for...',
      es: 'Estoy buscando...',
      exampleEn: 'I am looking for a warm coat for winter.',
      exampleEs: 'Estoy buscando un abrigo caliente para el invierno.',
    },
    {
      id: 'color',
      en: 'color',
      es: 'el color',
      exampleEn: 'What color do you want?',
      exampleEs: '¿Qué color quiere?',
    },
    {
      id: 'price-tag',
      en: 'price tag',
      es: 'la etiqueta de precio',
      exampleEn: 'Check the price tag before you buy it.',
      exampleEs: 'Revisa la etiqueta de precio antes de comprarlo.',
    },
    {
      id: 'pay',
      en: 'pay',
      es: 'pagar',
      exampleEn: 'Where do I pay for this?',
      exampleEs: '¿Dónde pago esto?',
    },
    {
      id: 'on-sale',
      en: 'on sale',
      es: 'en oferta',
      exampleEn: 'This jacket is on sale today.',
      exampleEs: 'Esta chaqueta está en oferta hoy.',
    },
    {
      id: 'match',
      en: 'match / matches',
      es: 'combinar / hace juego',
      exampleEn: 'Does this shirt match these pants?',
      exampleEs: '¿Esta camisa hace juego con estos pantalones?',
    },
    {
      id: 'cash-register',
      en: 'cash register',
      es: 'la caja registradora',
      exampleEn: 'The cash register is at the front of the store.',
      exampleEs: 'La caja registradora está al frente de la tienda.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'Where do you try on clothes in a store?',
      promptEs: '¿Dónde te pruebas la ropa en una tienda?',
      answer: 'Fitting room',
      options: ['Fitting room', 'Cashier', 'Aisle', 'Exit'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'How do you say "Esta camisa es muy grande" in English?',
      promptEs: '¿Cómo se dice "Esta camisa es muy grande" en inglés?',
      answer: 'This shirt is too big',
      options: ['This shirt is too big', 'This shirt is too small', 'This shirt is on sale', 'This shirt is my size'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Estoy buscando..." in English is:',
      promptEs: '"Estoy buscando..." en inglés es:',
      answer: 'I am looking for...',
      options: ['I am looking for...', 'I am trying on...', 'I want to return...', 'Do you have...?'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you ask if a store has something in a different color?',
      promptEs: '¿Cómo preguntas si una tienda tiene algo en otro color?',
      answer: 'Do you have this in...?',
      options: ['Do you have this in...?', 'Where is the fitting room?', 'Can I return this?', 'What is the size?'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"El descuento" in English is:',
      promptEs: '"El descuento" en inglés es:',
      answer: 'discount',
      options: ['discount', 'receipt', 'return', 'exchange'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Finding the right size',
      text: 'You are at a clothing store in New York. You need to find a coat for winter but you do not know your size in American sizes, and you need help asking about the fitting room.',
      script: [
        { speaker: 'tutor', en: "Let's practice shopping for a coat. I'll be the store clerk. What are you looking for?", es: 'Vamos a practicar cómo comprar un abrigo. Yo seré el empleado de la tienda. ¿Qué está buscando?' },
        { speaker: 'student', en: 'I am looking for a warm coat for winter.', es: 'Estoy buscando un abrigo caliente para el invierno.' },
        { speaker: 'tutor', en: 'Great, what size do you wear?', es: 'Muy bien, ¿qué talla usa?' },
        { speaker: 'student', en: "I'm not sure. Do you have this in a medium?", es: 'No estoy segura. ¿Tiene esto en talla mediana?' },
        { speaker: 'tutor', en: 'Yes, here is a medium. Would you like to try it on?', es: 'Sí, aquí tiene una mediana. ¿Le gustaría probársela?' },
        { speaker: 'student', en: 'Yes, can I use the fitting room to try this on?', es: '¿Puedo usar el probador para probarme esto?' },
        { speaker: 'tutor', en: "Of course, it's right over there.", es: 'Claro, está justo allí.' },
        { speaker: 'student', en: 'This coat is too big. Do you have a smaller size?', es: 'Este abrigo es muy grande. ¿Tiene una talla más pequeña?' },
        { speaker: 'tutor', en: 'Let me get you a small.', es: 'Le traigo una talla pequeña.' },
        { speaker: 'student', en: "Thank you, that's much better.", es: 'Gracias, eso está mucho mejor.' },
        { speaker: 'tutor', en: 'Perfect! You found your size and used the fitting room like a pro.', es: '¡Perfecto! Encontró su talla y usó el probador como una experta.' },
      ],
    },
    {
      label: 'Part 2: Asking about colors and prices',
      text: 'You found a coat you like but want to know if it comes in a different color, check the price tag, and ask if it is on sale.',
      script: [
        { speaker: 'tutor', en: "You like the coat! Now let's ask about colors and price. I'm the clerk again.", es: '¡Le gusta el abrigo! Ahora preguntemos sobre colores y precio. Yo soy el empleado otra vez.' },
        { speaker: 'student', en: 'Do you have this in a different color?', es: '¿Tiene esto en otro color?' },
        { speaker: 'tutor', en: 'What color do you want?', es: '¿Qué color quiere?' },
        { speaker: 'student', en: 'Do you have this in blue?', es: '¿Tiene esto en azul?' },
        { speaker: 'tutor', en: 'Yes, we have it in blue too.', es: 'Sí, también lo tenemos en azul.' },
        { speaker: 'student', en: 'Let me check the price tag. Is this coat on sale?', es: 'Déjeme revisar la etiqueta de precio. ¿Este abrigo está en oferta?' },
        { speaker: 'tutor', en: "Yes, it's on sale today.", es: 'Sí, está en oferta hoy.' },
        { speaker: 'student', en: 'Is there a discount if I buy two?', es: '¿Hay un descuento si compro dos?' },
        { speaker: 'tutor', en: "Yes, there's an extra ten percent off.", es: 'Sí, hay un diez por ciento adicional de descuento.' },
        { speaker: 'student', en: "Great, I'll take the blue one.", es: 'Genial, me llevo el azul.' },
        { speaker: 'tutor', en: 'Excellent! You asked about color, checked the price tag, and found a great discount.', es: '¡Excelente! Preguntó sobre el color, revisó la etiqueta de precio y encontró un buen descuento.' },
      ],
    },
    {
      label: 'Part 3: Paying and returns',
      text: 'You are ready to buy the coat. Practice paying at the cash register, and asking about the store\'s return or exchange policy in case it does not fit.',
      script: [
        { speaker: 'tutor', en: "You're ready to buy. I'll be the cashier. Where do you pay for this?", es: 'Ya está lista para comprar. Yo seré el cajero. ¿Dónde paga esto?' },
        { speaker: 'student', en: 'Where do I pay for this?', es: '¿Dónde pago esto?' },
        { speaker: 'tutor', en: 'The cash register is at the front of the store.', es: 'La caja registradora está al frente de la tienda.' },
        { speaker: 'student', en: 'Does this scarf match this coat?', es: '¿Esta bufanda hace juego con este abrigo?' },
        { speaker: 'tutor', en: 'Yes, it matches very well.', es: 'Sí, hace juego muy bien.' },
        { speaker: 'student', en: "Great, I'll take both. What if I need to return it?", es: 'Genial, me llevo los dos. ¿Y si necesito devolverlo?' },
        { speaker: 'tutor', en: 'Our policy allows you to return or exchange items within 30 days with a receipt.', es: 'Nuestra política permite devolver o cambiar artículos dentro de 30 días con un recibo.' },
        { speaker: 'student', en: "Good, I would like to return this coat if it doesn't fit, is that okay?", es: 'Bien, me gustaría devolver este abrigo si no me queda bien, ¿está bien?' },
        { speaker: 'tutor', en: "Yes, that's no problem at all.", es: 'Sí, no hay ningún problema.' },
        { speaker: 'student', en: 'Thank you very much!', es: '¡Muchas gracias!' },
        { speaker: 'tutor', en: 'Wonderful! You paid at the register and learned about returns and exchanges.', es: '¡Maravilloso! Pagó en la caja registradora y aprendió sobre devoluciones y cambios.' },
      ],
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'This shirt is too ____.', promptEs: 'Esta camisa es muy grande. (This shirt is too ____.)', answer: 'big' },
    { id: 'w2', promptEn: 'Do you ____ this in blue?', promptEs: '¿Tiene esto en azul? (Do you ____ this in blue?)', answer: 'have' },
    { id: 'w3', promptEn: 'I am ____ for a warm coat.', promptEs: 'Estoy buscando un abrigo caliente. (I am ____ for a warm coat.)', answer: 'looking' },
    { id: 'w4', promptEn: 'Can I ____ on this jacket?', promptEs: '¿Me puedo probar esta chaqueta? (Can I ____ on this jacket?)', answer: 'try' },
    { id: 'w5', promptEn: 'Is there a ____ on these shoes?', promptEs: '¿Hay un descuento en estos zapatos? (Is there a ____ on these shoes?)', answer: 'discount' },
  ],
}

export default module
