import type { Module } from '@/types'

const module: Module = {
  slug: 'buying-groceries',
  track: 'esl',
  titleEn: 'Buying Groceries',
  titleEs: 'Comprar Comida',
  descriptionEn: 'Learn how to shop for food at a supermarket in New York.',
  descriptionEs: 'Aprende a hacer compras en un supermercado en Nueva York.',
  icon: 'ShoppingCart',
  vocab: [
    {
      id: 'aisle',
      en: 'aisle',
      es: 'el pasillo',
      exampleEn: 'The rice is in aisle 5.',
      exampleEs: 'El arroz está en el pasillo 5.',
    },
    {
      id: 'how-much',
      en: 'How much does this cost?',
      es: '¿Cuánto cuesta esto?',
      exampleEn: 'Excuse me, how much does this cost?',
      exampleEs: 'Disculpe, ¿cuánto cuesta esto?',
    },
    {
      id: 'receipt',
      en: 'receipt',
      es: 'el recibo',
      exampleEn: 'Can I have a receipt, please?',
      exampleEs: '¿Me puede dar el recibo, por favor?',
    },
    {
      id: 'cashier',
      en: 'cashier',
      es: 'el cajero / la cajera',
      exampleEn: 'Pay at the cashier at the front of the store.',
      exampleEs: 'Paga en la caja al frente de la tienda.',
    },
    {
      id: 'bag',
      en: 'bag',
      es: 'la bolsa',
      exampleEn: 'Do you need a bag for your groceries?',
      exampleEs: '¿Necesita una bolsa para sus compras?',
    },
    {
      id: 'on-sale',
      en: 'on sale',
      es: 'en oferta / en descuento',
      exampleEn: 'The chicken is on sale this week.',
      exampleEs: 'El pollo está en oferta esta semana.',
    },
    {
      id: 'where-is',
      en: 'Where is the...?',
      es: '¿Dónde está el/la...?',
      exampleEn: 'Excuse me, where is the milk?',
      exampleEs: 'Disculpe, ¿dónde está la leche?',
    },
    {
      id: 'cash-credit',
      en: 'cash or credit card',
      es: 'efectivo o tarjeta de crédito',
      exampleEn: 'Will you be paying with cash or credit card?',
      exampleEs: '¿Va a pagar con efectivo o tarjeta de crédito?',
    },
    {
      id: 'fresh',
      en: 'fresh',
      es: 'fresco / fresca',
      exampleEn: 'Is this fish fresh?',
      exampleEs: '¿Este pescado está fresco?',
    },
    {
      id: 'pound',
      en: 'pound',
      es: 'la libra',
      exampleEn: 'I need two pounds of rice.',
      exampleEs: 'Necesito dos libras de arroz.',
    },
    {
      id: 'checkout-line',
      en: 'checkout line',
      es: 'la fila de pago',
      exampleEn: 'The checkout line is very long today.',
      exampleEs: 'La fila de pago está muy larga hoy.',
    },
    {
      id: 'do-you-have',
      en: 'Do you have...?',
      es: '¿Tiene...?',
      exampleEn: 'Do you have any fresh tomatoes?',
      exampleEs: '¿Tiene tomates frescos?',
    },
    {
      id: 'expensive-cheap',
      en: 'expensive / cheap',
      es: 'caro / barato',
      exampleEn: 'This store is expensive, but that one is cheap.',
      exampleEs: 'Esta tienda es cara, pero esa es barata.',
    },
    {
      id: 'i-would-like',
      en: 'I would like...',
      es: 'Quisiera... / Me gustaría...',
      exampleEn: 'I would like two pounds of chicken, please.',
      exampleEs: 'Quisiera dos libras de pollo, por favor.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'How do you ask where something is in a store?',
      promptEs: '¿Cómo preguntas dónde está algo en una tienda?',
      answer: 'Where is the...?',
      options: ['Where is the...?', 'How much does this cost?', 'Can I have a receipt?', 'Is this on sale?'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: '"El pasillo" in English is:',
      promptEs: '"El pasillo" en inglés es:',
      answer: 'aisle',
      options: ['aisle', 'cashier', 'receipt', 'bag'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: 'How do you ask the price of something?',
      promptEs: '¿Cómo preguntas el precio de algo?',
      answer: 'How much does this cost?',
      options: ['How much does this cost?', 'Where is the cashier?', 'Can I have a bag?', 'Is this on sale?'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: '"En oferta" in English means:',
      promptEs: '"En oferta" en inglés significa:',
      answer: 'on sale',
      options: ['on sale', 'on aisle', 'on cash', 'on receipt'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: 'The person who takes your payment at the store is called:',
      promptEs: 'La persona que recibe tu pago en la tienda se llama:',
      answer: 'cashier',
      options: ['cashier', 'manager', 'customer', 'bagger'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Finding items and asking prices',
      text: 'You are at a supermarket in Queens. You need to buy rice, bread, and vegetables but do not know how to ask where things are or how much they cost.',
      script: [
        { speaker: 'tutor', en: "Let's practice finding items in the supermarket. I'll be a store employee. Ask me where the rice is.", es: 'Vamos a practicar cómo encontrar productos en el supermercado. Yo seré un empleado de la tienda. Pregúntame dónde está el arroz.' },
        { speaker: 'student', en: 'Excuse me, where is the rice?', es: 'Disculpe, ¿dónde está el arroz?' },
        { speaker: 'tutor', en: 'The rice is in aisle 5.', es: 'El arroz está en el pasillo 5.' },
        { speaker: 'student', en: 'Thank you. Where is the bread?', es: 'Gracias. ¿Dónde está el pan?' },
        { speaker: 'tutor', en: 'The bread is in aisle 3, next to the milk.', es: 'El pan está en el pasillo 3, al lado de la leche.' },
        { speaker: 'student', en: 'Do you have any fresh vegetables?', es: '¿Tiene verduras frescas?' },
        { speaker: 'tutor', en: 'Yes, the vegetables are in aisle 1.', es: 'Sí, las verduras están en el pasillo 1.' },
        { speaker: 'student', en: 'How much does this cost?', es: '¿Cuánto cuesta esto?' },
        { speaker: 'tutor', en: "That's on sale this week — it's two dollars.", es: 'Eso está en oferta esta semana — cuesta dos dólares.' },
        { speaker: 'student', en: 'Great, thank you for your help!', es: '¡Genial, gracias por su ayuda!' },
        { speaker: 'tutor', en: 'Well done! You asked where things are and how much they cost like a pro.', es: '¡Muy bien! Preguntaste dónde están las cosas y cuánto cuestan como un experto.' },
      ],
    },
    {
      label: 'Part 2: Asking for a specific amount',
      text: 'You need a specific quantity of something (like two pounds of chicken) and want to know if the fish is fresh. Practice asking the person at the counter.',
      script: [
        { speaker: 'tutor', en: "Now let's practice asking for a specific amount. I'll be the person at the counter. Tell me what you would like.", es: 'Ahora vamos a practicar cómo pedir una cantidad específica. Yo seré la persona en el mostrador. Dime qué quisieras.' },
        { speaker: 'student', en: 'I would like two pounds of chicken, please.', es: 'Quisiera dos libras de pollo, por favor.' },
        { speaker: 'tutor', en: 'Of course. Anything else?', es: 'Claro. ¿Algo más?' },
        { speaker: 'student', en: 'Do you have any fresh fish today?', es: '¿Tiene pescado fresco hoy?' },
        { speaker: 'tutor', en: 'Yes, is this fish fresh? Let me check for you — yes, it came in this morning.', es: 'Sí, ¿este pescado está fresco? Déjeme revisar — sí, llegó esta mañana.' },
        { speaker: 'student', en: 'I would like one pound of fish, please.', es: 'Quisiera una libra de pescado, por favor.' },
        { speaker: 'tutor', en: 'One pound of fish, coming right up. Anything else?', es: 'Una libra de pescado, enseguida. ¿Algo más?' },
        { speaker: 'student', en: "No, that's all. How much does this cost?", es: 'No, eso es todo. ¿Cuánto cuesta esto?' },
        { speaker: 'tutor', en: 'That will be twelve dollars total.', es: 'Eso será doce dólares en total.' },
        { speaker: 'student', en: 'Thank you very much.', es: 'Muchas gracias.' },
        { speaker: 'tutor', en: 'Perfect! You asked for exact amounts and checked freshness just like a real customer.', es: '¡Perfecto! Pediste cantidades exactas y preguntaste por lo fresco como una verdadera clienta.' },
      ],
    },
    {
      label: 'Part 3: Checkout and paying',
      text: 'You are in the checkout line. Practice asking for a bag, paying with cash or credit card, and asking for a receipt.',
      script: [
        { speaker: 'tutor', en: "Now let's practice checkout. I'll be the cashier and you're in the checkout line.", es: 'Ahora vamos a practicar el pago. Yo seré el cajero y tú estás en la fila de pago.' },
        { speaker: 'student', en: 'Hi, the checkout line was very long today!', es: 'Hola, ¡la fila de pago estaba muy larga hoy!' },
        { speaker: 'tutor', en: 'Yes, it is busy today. Will you be paying with cash or credit card?', es: '¿Va a pagar con efectivo o tarjeta de crédito?' },
        { speaker: 'student', en: 'I would like to pay with credit card.', es: 'Quisiera pagar con tarjeta de crédito.' },
        { speaker: 'tutor', en: 'Great. Do you need a bag for your groceries?', es: '¿Necesita una bolsa para sus compras?' },
        { speaker: 'student', en: 'Yes, I need a bag, please.', es: 'Sí, necesito una bolsa, por favor.' },
        { speaker: 'tutor', en: 'Here you go. Anything else?', es: 'Aquí tiene. ¿Algo más?' },
        { speaker: 'student', en: 'Can I have a receipt, please?', es: '¿Me puede dar el recibo, por favor?' },
        { speaker: 'tutor', en: 'Of course, here is your receipt.', es: 'Claro, aquí está su recibo.' },
        { speaker: 'student', en: 'Thank you, have a good day!', es: 'Gracias, ¡que tenga un buen día!' },
        { speaker: 'tutor', en: 'Excellent work! You handled the whole checkout — cash or card, bag, and receipt.', es: '¡Excelente trabajo! Manejaste todo el proceso de pago — efectivo o tarjeta, bolsa y recibo.' },
      ],
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'Excuse me, ____ is the milk?', promptEs: 'Disculpe, ¿____ está la leche?', answer: 'where' },
    { id: 'w2', promptEn: 'How ____ does this cost?', promptEs: '¿Cuánto cuesta esto? (How ____ does this cost?)', answer: 'much' },
    { id: 'w3', promptEn: 'I would ____ two pounds of rice.', promptEs: 'Quisiera dos libras de arroz. (I would ____ two pounds...)', answer: 'like' },
    { id: 'w4', promptEn: 'Do you ____ any fresh tomatoes?', promptEs: '¿Tiene tomates frescos? (Do you ____ any fresh tomatoes?)', answer: 'have' },
    { id: 'w5', promptEn: 'Can I ____ a receipt, please?', promptEs: '¿Me puede dar el recibo? (Can I ____ a receipt, please?)', answer: 'have' },
  ],
}

export default module
