import type { Module } from '@/types'

const module: Module = {
  slug: 'buying-groceries',
  track: 'esl',
  titleEn: 'Buying Groceries',
  titleEs: 'Comprar Comida',
  descriptionEn: 'Learn how to shop for food at a supermarket in New York.',
  descriptionEs: 'Aprende a hacer compras en un supermercado en Nueva York.',
  icon: 'ShoppingCart',
  vocab: [
    {
      id: 'aisle',
      en: 'aisle',
      es: 'el pasillo',
      exampleEn: 'The rice is in aisle 5.',
      exampleEs: 'El arroz está en el pasillo 5.',
    },
    {
      id: 'how-much',
      en: 'How much does this cost?',
      es: '¿Cuánto cuesta esto?',
      exampleEn: 'Excuse me, how much does this cost?',
      exampleEs: 'Disculpe, ¿cuánto cuesta esto?',
    },
    {
      id: 'receipt',
      en: 'receipt',
      es: 'el recibo',
      exampleEn: 'Can I have a receipt, please?',
      exampleEs: '¿Me puede dar el recibo, por favor?',
    },
    {
      id: 'cashier',
      en: 'cashier',
      es: 'el cajero / la cajera',
      exampleEn: 'Pay at the cashier at the front of the store.',
      exampleEs: 'Paga en la caja al frente de la tienda.',
    },
    {
      id: 'bag',
      en: 'bag',
      es: 'la bolsa',
      exampleEn: 'Do you need a bag for your groceries?',
      exampleEs: '¿Necesita una bolsa para sus compras?',
    },
    {
      id: 'on-sale',
      en: 'on sale',
      es: 'en oferta / en descuento',
      exampleEn: 'The chicken is on sale this week.',
      exampleEs: 'El pollo está en oferta esta semana.',
    },
    {
      id: 'where-is',
      en: 'Where is the...?',
      es: '¿Dónde está el/la...?',
      exampleEn: 'Excuse me, where is the milk?',
      exampleEs: 'Disculpe, ¿dónde está la leche?',
    },
    {
      id: 'cash-credit',
      en: 'cash or credit card',
      es: 'efectivo o tarjeta de crédito',
      exampleEn: 'Will you be paying with cash or credit card?',
      exampleEs: '¿Va a pagar con efectivo o tarjeta de crédito?',
    },
    {
      id: 'fresh',
      en: 'fresh',
      es: 'fresco / fresca',
      exampleEn: 'Is this fish fresh?',
      exampleEs: '¿Este pescado está fresco?',
    },
    {
      id: 'pound',
      en: 'pound',
      es: 'la libra',
      exampleEn: 'I need two pounds of rice.',
      exampleEs: 'Necesito dos libras de arroz.',
    },
    {
      id: 'checkout-line',
      en: 'checkout line',
      es: 'la fila de pago',
      exampleEn: 'The checkout line is very long today.',
      exampleEs: 'La fila de pago está muy larga hoy.',
    },
    {
      id: 'do-you-have',
      en: 'Do you have...?',
      es: '¿Tiene...?',
      exampleEn: 'Do you have any fresh tomatoes?',
      exampleEs: '¿Tiene tomates frescos?',
    },
    {
      id: 'expensive-cheap',
      en: 'expensive / cheap',
      es: 'caro / barato',
      exampleEn: 'This store is expensive, but that one is cheap.',
      exampleEs: 'Esta tienda es cara, pero esa es barata.',
    },
    {
      id: 'i-would-like',
      en: 'I would like...',
      es: 'Quisiera... / Me gustaría...',
      exampleEn: 'I would like two pounds of chicken, please.',
      exampleEs: 'Quisiera dos libras de pollo, por favor.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'How do you ask where something is in a store?',
      promptEs: '¿Cómo preguntas dónde está algo en una tienda?',
      answer: 'Where is the...?',
      options: ['Where is the...?', 'How much does this cost?', 'Can I have a receipt?', 'Is this on sale?'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: '"El pasillo" in English is:',
      promptEs: '"El pasillo" en inglés es:',
      answer: 'aisle',
      options: ['aisle', 'cashier', 'receipt', 'bag'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: 'How do you ask the price of something?',
      promptEs: '¿Cómo preguntas el precio de algo?',
      answer: 'How much does this cost?',
      options: ['How much does this cost?', 'Where is the cashier?', 'Can I have a bag?', 'Is this on sale?'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: '"En oferta" in English means:',
      promptEs: '"En oferta" en inglés significa:',
      answer: 'on sale',
      options: ['on sale', 'on aisle', 'on cash', 'on receipt'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: 'The person who takes your payment at the store is called:',
      promptEs: 'La persona que recibe tu pago en la tienda se llama:',
      answer: 'cashier',
      options: ['cashier', 'manager', 'customer', 'bagger'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Finding items and asking prices',
      text: 'You are at a supermarket in Queens. You need to buy rice, bread, and vegetables but do not know how to ask where things are or how much they cost.',
    },
    {
      label: 'Part 2: Asking for a specific amount',
      text: 'You need a specific quantity of something (like two pounds of chicken) and want to know if the fish is fresh. Practice asking the person at the counter.',
    },
    {
      label: 'Part 3: Checkout and paying',
      text: 'You are in the checkout line. Practice asking for a bag, paying with cash or credit card, and asking for a receipt.',
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'Excuse me, ____ is the milk?', promptEs: 'Disculpe, ¿____ está la leche?', answer: 'where' },
    { id: 'w2', promptEn: 'How ____ does this cost?', promptEs: '¿Cuánto cuesta esto? (How ____ does this cost?)', answer: 'much' },
    { id: 'w3', promptEn: 'I would ____ two pounds of rice.', promptEs: 'Quisiera dos libras de arroz. (I would ____ two pounds...)', answer: 'like' },
    { id: 'w4', promptEn: 'Do you ____ any fresh tomatoes?', promptEs: '¿Tiene tomates frescos? (Do you ____ any fresh tomatoes?)', answer: 'have' },
    { id: 'w5', promptEn: 'Can I ____ a receipt, please?', promptEs: '¿Me puede dar el recibo? (Can I ____ a receipt, please?)', answer: 'have' },
  ],
}

export default module
