import type { Module } from '@/types'

const module: Module = {
  slug: 'demonstratives',
  track: 'esl',
  titleEn: 'This/That, These/Those',
  titleEs: 'This/That, These/Those',
  descriptionEn: 'Learn how to point out things that are near or far, one or many.',
  descriptionEs: 'Aprende a señalar cosas que están cerca o lejos, una o varias.',
  icon: 'MousePointer2',
  vocab: [
    { id: 'this', en: 'this', es: 'esto / este / esta',
      exampleEn: 'This is my house.', exampleEs: 'Esta es mi casa.' },
    { id: 'that', en: 'that', es: 'eso / ese / esa',
      exampleEn: 'That is my car.', exampleEs: 'Ese es mi carro.' },
    { id: 'these', en: 'these', es: 'estos / estas',
      exampleEn: 'These are my keys.', exampleEs: 'Estas son mis llaves.' },
    { id: 'those', en: 'those', es: 'esos / esas',
      exampleEn: 'Those are my shoes.', exampleEs: 'Esos son mis zapatos.' },
    { id: 'this-is-my-house', en: 'This is my house', es: 'Esta es mi casa',
      exampleEn: 'This is my house on Main Street.', exampleEs: 'Esta es mi casa en la calle Main.' },
    { id: 'that-is-my-car', en: 'That is my car', es: 'Ese es mi carro',
      exampleEn: 'That is my car over there.', exampleEs: 'Ese es mi carro allá.' },
    { id: 'these-are-my-keys', en: 'These are my keys', es: 'Estas son mis llaves',
      exampleEn: 'These are my keys, right here.', exampleEs: 'Estas son mis llaves, aquí mismo.' },
    { id: 'those-are-my-shoes', en: 'Those are my shoes', es: 'Esos son mis zapatos',
      exampleEn: 'Those are my shoes by the door.', exampleEs: 'Esos son mis zapatos junto a la puerta.' },
    { id: 'is-this-yours', en: 'Is this yours?', es: '¿Esto es tuyo?',
      exampleEn: 'Excuse me, is this yours?', exampleEs: 'Disculpe, ¿esto es suyo?' },
    { id: 'what-is-this', en: 'What is this?', es: '¿Qué es esto?',
      exampleEn: 'What is this? I don\'t know this word.', exampleEs: '¿Qué es esto? No conozco esta palabra.' },
    { id: 'i-like-this-one', en: 'I like this one', es: 'Me gusta este / esta',
      exampleEn: 'I like this one better than that one.', exampleEs: 'Me gusta este más que ese.' },
    { id: 'i-like-that-one', en: 'I like that one', es: 'Me gusta ese / esa',
      exampleEn: 'I like that one over there.', exampleEs: 'Me gusta ese que está allá.' },
    { id: 'here', en: 'here', es: 'aquí',
      exampleEn: 'My documents are here.', exampleEs: 'Mis documentos están aquí.' },
    { id: 'there', en: 'there', es: 'allí / allá',
      exampleEn: 'The bus stop is over there.', exampleEs: 'La parada de autobús está allá.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Esto" (near, one thing) in English is:', promptEs: '"Esto" (cerca, una cosa) en inglés es:',
      answer: 'this', options: ['this', 'that', 'these', 'those'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"Esos" (far, many things) in English is:', promptEs: '"Esos" (lejos, varias cosas) en inglés es:',
      answer: 'those', options: ['those', 'these', 'this', 'that'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "___ are my keys." (they are right here)', promptEs: 'Completa: "___ are my keys." (están aquí mismo)',
      answer: 'These', options: ['These', 'Those', 'This', 'That'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ is my car." (it is far away)', promptEs: 'Completa: "___ is my car." (está lejos)',
      answer: 'That', options: ['That', 'This', 'These', 'Those'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"¿Qué es esto?" in English is:', promptEs: '"¿Qué es esto?" en inglés es:',
      answer: 'What is this?', options: ['What is this?', 'What is that?', 'Is this yours?', 'I like this one'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Pointing out things at home',
      text: 'Practice pointing out things near you at home — "This is my house," "These are my keys" — using this/these.',
      script: [
        { speaker: 'tutor', en: "Let's practice pointing at things in your home. What is this?", es: 'Practiquemos señalando cosas en tu casa. ¿Qué es esto?' },
        { speaker: 'student', en: 'This is my house.', es: 'Esta es mi casa.' },
        { speaker: 'tutor', en: 'Nice! And what about these things on the table?', es: '¡Bien! ¿Y qué hay de estas cosas en la mesa?' },
        { speaker: 'student', en: 'These are my keys.', es: 'Estas son mis llaves.' },
        { speaker: 'tutor', en: 'Good. Are your keys here or over there?', es: '¿Tus llaves están aquí o allá?' },
        { speaker: 'student', en: 'My keys are here, on the table.', es: 'Mis llaves están aquí, en la mesa.' },
        { speaker: 'tutor', en: 'Perfect. Now point to something across the room and tell me what it is.', es: 'Perfecto. Ahora señala algo al otro lado del cuarto y dime qué es.' },
        { speaker: 'student', en: "That is my car... wait, that's a photo of my car!", es: 'Eso es mi carro... espera, ¡esa es una foto de mi carro!' },
        { speaker: 'tutor', en: 'Good catch! This and these are for things nearby. That and those are for things far away.', es: '¡Buena corrección! This y these son para cosas cercanas. That y those son para cosas lejanas.' },
        { speaker: 'student', en: 'This is my house, and that is my car in the photo.', es: 'Esta es mi casa, y ese es mi carro en la foto.' },
        { speaker: 'tutor', en: 'Excellent! Now you know when to use this/these for near things and that/those for far things.', es: '¡Excelente! Ahora sabes cuándo usar this/these para cosas cercanas y that/those para cosas lejanas.' },
      ] },
    { label: 'Part 2: Comparing items in a store',
      text: 'Practice comparing an item close to you with one far away on a shelf, like "I like this one" versus "I like that one."',
      script: [
        { speaker: 'tutor', en: 'Imagine we are in a shoe store. There are two pairs of shoes — one close to you, one far away on a shelf. Which do you like?', es: 'Imagina que estamos en una zapatería. Hay dos pares de zapatos, uno cerca de ti y otro lejos en un estante. ¿Cuál te gusta?' },
        { speaker: 'student', en: 'I like this one.', es: 'Me gusta este.' },
        { speaker: 'tutor', en: 'Why do you like this one?', es: '¿Por qué te gusta este?' },
        { speaker: 'student', en: 'These are my favorite color.', es: 'Estos son de mi color favorito.' },
        { speaker: 'tutor', en: 'Good sentence! Now look at the shoes over there. Do you like those?', es: '¡Buena oración! Ahora mira los zapatos allá. ¿Te gustan esos?' },
        { speaker: 'student', en: 'I like that one too, but this one is cheaper.', es: 'También me gusta ese, pero este es más barato.' },
        { speaker: 'tutor', en: 'Great comparison. So, this one here or that one there — which will you buy?', es: 'Buena comparación. Entonces, ¿este de aquí o ese de allá? ¿Cuál vas a comprar?' },
        { speaker: 'student', en: 'I like this one. Those are nice, but these are better for me.', es: 'Me gusta este. Esos son bonitos, pero estos son mejores para mí.' },
        { speaker: 'tutor', en: 'Perfect! You compared items near and far very well.', es: '¡Perfecto! Comparaste artículos cercanos y lejanos muy bien.' },
      ] },
    { label: 'Part 3: Asking about unfamiliar things',
      text: 'You see something you don\'t recognize at the pharmacy or grocery store. Practice asking "What is this?" and "Is this yours?"',
      script: [
        { speaker: 'tutor', en: "Let's practice at the pharmacy. You see something on the shelf you don't recognize. What do you ask?", es: 'Practiquemos en la farmacia. Ves algo en el estante que no reconoces. ¿Qué preguntas?' },
        { speaker: 'student', en: 'What is this?', es: '¿Qué es esto?' },
        { speaker: 'tutor', en: "Good question! Now imagine you found something on the floor that isn't yours.", es: '¡Buena pregunta! Ahora imagina que encontraste algo en el piso que no es tuyo.' },
        { speaker: 'student', en: 'Excuse me, is this yours?', es: 'Disculpe, ¿esto es suyo?' },
        { speaker: 'tutor', en: 'Perfect. What if the pharmacist says yes, it is hers? What do you say?', es: 'Perfecto. ¿Y si la farmacéutica dice que sí, que es suyo? ¿Qué dices?' },
        { speaker: 'student', en: 'Oh, okay. Then what is that, over there?', es: 'Ah, bueno. Entonces, ¿qué es eso, allá?' },
        { speaker: 'tutor', en: 'That is medicine for a headache.', es: 'Eso es medicina para el dolor de cabeza.' },
        { speaker: 'student', en: 'Thank you. I like this one better than that one.', es: 'Gracias. Me gusta este más que ese.' },
        { speaker: 'tutor', en: 'Great! You asked about things you do not recognize very naturally.', es: '¡Genial! Preguntaste sobre cosas que no reconoces de forma muy natural.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ is my house.', promptEs: 'Esta es mi casa. (____ is my house.)', answer: 'This' },
    { id: 'w2', promptEn: '____ are my keys.', promptEs: 'Estas son mis llaves. (____ are my keys.)', answer: 'These' },
    { id: 'w3', promptEn: '____ is my car.', promptEs: 'Ese es mi carro. (____ is my car.)', answer: 'That' },
    { id: 'w4', promptEn: '____ are my shoes.', promptEs: 'Esos son mis zapatos. (____ are my shoes.)', answer: 'Those' },
    { id: 'w5', promptEn: 'What is ____?', promptEs: '¿Qué es esto? (What is ____?)', answer: 'this' },
  ],
}

export default module
