import type { Module } from '@/types'

const module: Module = {
  slug: 'demonstratives',
  track: 'esl',
  titleEn: 'This/That, These/Those',
  titleEs: 'This/That, These/Those',
  descriptionEn: 'Learn how to point out things that are near or far, one or many.',
  descriptionEs: 'Aprende a señalar cosas que están cerca o lejos, una o varias.',
  icon: 'MousePointer2',
  vocab: [
    { id: 'this', en: 'this', es: 'esto / este / esta',
      exampleEn: 'This is my house.', exampleEs: 'Esta es mi casa.' },
    { id: 'that', en: 'that', es: 'eso / ese / esa',
      exampleEn: 'That is my car.', exampleEs: 'Ese es mi carro.' },
    { id: 'these', en: 'these', es: 'estos / estas',
      exampleEn: 'These are my keys.', exampleEs: 'Estas son mis llaves.' },
    { id: 'those', en: 'those', es: 'esos / esas',
      exampleEn: 'Those are my shoes.', exampleEs: 'Esos son mis zapatos.' },
    { id: 'this-is-my-house', en: 'This is my house', es: 'Esta es mi casa',
      exampleEn: 'This is my house on Main Street.', exampleEs: 'Esta es mi casa en la calle Main.' },
    { id: 'that-is-my-car', en: 'That is my car', es: 'Ese es mi carro',
      exampleEn: 'That is my car over there.', exampleEs: 'Ese es mi carro allá.' },
    { id: 'these-are-my-keys', en: 'These are my keys', es: 'Estas son mis llaves',
      exampleEn: 'These are my keys, right here.', exampleEs: 'Estas son mis llaves, aquí mismo.' },
    { id: 'those-are-my-shoes', en: 'Those are my shoes', es: 'Esos son mis zapatos',
      exampleEn: 'Those are my shoes by the door.', exampleEs: 'Esos son mis zapatos junto a la puerta.' },
    { id: 'is-this-yours', en: 'Is this yours?', es: '¿Esto es tuyo?',
      exampleEn: 'Excuse me, is this yours?', exampleEs: 'Disculpe, ¿esto es suyo?' },
    { id: 'what-is-this', en: 'What is this?', es: '¿Qué es esto?',
      exampleEn: 'What is this? I don\'t know this word.', exampleEs: '¿Qué es esto? No conozco esta palabra.' },
    { id: 'i-like-this-one', en: 'I like this one', es: 'Me gusta este / esta',
      exampleEn: 'I like this one better than that one.', exampleEs: 'Me gusta este más que ese.' },
    { id: 'i-like-that-one', en: 'I like that one', es: 'Me gusta ese / esa',
      exampleEn: 'I like that one over there.', exampleEs: 'Me gusta ese que está allá.' },
    { id: 'here', en: 'here', es: 'aquí',
      exampleEn: 'My documents are here.', exampleEs: 'Mis documentos están aquí.' },
    { id: 'there', en: 'there', es: 'allí / allá',
      exampleEn: 'The bus stop is over there.', exampleEs: 'La parada de autobús está allá.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Esto" (near, one thing) in English is:', promptEs: '"Esto" (cerca, una cosa) en inglés es:',
      answer: 'this', options: ['this', 'that', 'these', 'those'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"Esos" (far, many things) in English is:', promptEs: '"Esos" (lejos, varias cosas) en inglés es:',
      answer: 'those', options: ['those', 'these', 'this', 'that'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "___ are my keys." (they are right here)', promptEs: 'Completa: "___ are my keys." (están aquí mismo)',
      answer: 'These', options: ['These', 'Those', 'This', 'That'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ is my car." (it is far away)', promptEs: 'Completa: "___ is my car." (está lejos)',
      answer: 'That', options: ['That', 'This', 'These', 'Those'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"¿Qué es esto?" in English is:', promptEs: '"¿Qué es esto?" en inglés es:',
      answer: 'What is this?', options: ['What is this?', 'What is that?', 'Is this yours?', 'I like this one'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Pointing out things at home',
      text: 'Practice pointing out things near you at home — "This is my house," "These are my keys" — using this/these.' },
    { label: 'Part 2: Comparing items in a store',
      text: 'Practice comparing an item close to you with one far away on a shelf, like "I like this one" versus "I like that one."' },
    { label: 'Part 3: Asking about unfamiliar things',
      text: 'You see something you don\'t recognize at the pharmacy or grocery store. Practice asking "What is this?" and "Is this yours?"' },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ is my house.', promptEs: 'Esta es mi casa. (____ is my house.)', answer: 'This' },
    { id: 'w2', promptEn: '____ are my keys.', promptEs: 'Estas son mis llaves. (____ are my keys.)', answer: 'These' },
    { id: 'w3', promptEn: '____ is my car.', promptEs: 'Ese es mi carro. (____ is my car.)', answer: 'That' },
    { id: 'w4', promptEn: '____ are my shoes.', promptEs: 'Esos son mis zapatos. (____ are my shoes.)', answer: 'Those' },
    { id: 'w5', promptEn: 'What is ____?', promptEs: '¿Qué es esto? (What is ____?)', answer: 'this' },
  ],
}

export default module
