import type { Module } from '@/types'

const module: Module = {
  slug: 'everyday-essentials',
  track: 'esl',
  titleEn: 'Everyday Essentials',
  titleEs: 'Lo Esencial del Día a Día',
  descriptionEn: 'Learn the everyday words and phrases you need to fill out forms and ask for help.',
  descriptionEs: 'Aprende las palabras y frases diarias que necesitas para llenar formularios y pedir ayuda.',
  icon: 'Home',
  vocab: [
    { id: 'phone-number', en: 'phone number', es: 'el número de teléfono',
      exampleEn: 'What is your phone number?', exampleEs: '¿Cuál es tu número de teléfono?' },
    { id: 'address', en: 'address', es: 'la dirección',
      exampleEn: 'What is your address?', exampleEs: '¿Cuál es tu dirección?' },
    { id: 'id', en: 'ID / identification', es: 'la identificación',
      exampleEn: 'Do you have an ID?', exampleEs: '¿Tiene una identificación?' },
    { id: 'bathroom', en: 'bathroom / restroom', es: 'el baño',
      exampleEn: 'Excuse me, where is the bathroom?', exampleEs: 'Disculpe, ¿dónde está el baño?' },
    { id: 'where-is-the-bathroom', en: 'Where is the bathroom?', es: '¿Dónde está el baño?',
      exampleEn: 'Excuse me, where is the bathroom?', exampleEs: 'Disculpe, ¿dónde está el baño?' },
    { id: 'key', en: 'key', es: 'la llave',
      exampleEn: "I lost my key.", exampleEs: 'Perdí mi llave.' },
    { id: 'wallet', en: 'wallet', es: 'la cartera',
      exampleEn: 'My wallet is in my bag.', exampleEs: 'Mi cartera está en mi bolsa.' },
    { id: 'wifi', en: 'wifi / internet', es: 'el wifi / internet',
      exampleEn: 'Is there free wifi here?', exampleEs: '¿Hay wifi gratis aquí?' },
    { id: 'password', en: 'password', es: 'la contraseña',
      exampleEn: 'What is the wifi password?', exampleEs: '¿Cuál es la contraseña del wifi?' },
    { id: 'mailbox', en: 'mailbox / mail', es: 'el buzón / el correo',
      exampleEn: 'Check the mailbox for a letter.', exampleEs: 'Revisa el buzón por una carta.' },
    { id: 'i-need-help', en: 'I need help', es: 'Necesito ayuda',
      exampleEn: 'Excuse me, I need help.', exampleEs: 'Disculpe, necesito ayuda.' },
    { id: 'emergency', en: 'emergency', es: 'la emergencia',
      exampleEn: 'Call 911 in an emergency.', exampleEs: 'Llama al 911 en una emergencia.' },
    { id: 'can-i-use-your-phone', en: 'Can I use your phone?', es: '¿Puedo usar tu teléfono?',
      exampleEn: 'Excuse me, can I use your phone?', exampleEs: 'Disculpe, ¿puedo usar tu teléfono?' },
    { id: 'im-lost', en: "I'm lost", es: 'Estoy perdido / perdida',
      exampleEn: "Excuse me, I'm lost. Can you help me?", exampleEs: 'Disculpe, estoy perdido. ¿Me puede ayudar?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"La dirección" in English is:', promptEs: '"La dirección" en inglés es:',
      answer: 'address', options: ['address', 'phone number', 'ID', 'wallet'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"El baño" in English is:', promptEs: '"El baño" en inglés es:',
      answer: 'bathroom', options: ['bathroom', 'mailbox', 'wallet', 'key'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'How do you say "Necesito ayuda"?', promptEs: '¿Cómo se dice "Necesito ayuda"?',
      answer: 'I need help', options: ['I need help', "I'm lost", 'Can I use your phone?', 'Where is the bathroom?'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Estoy perdido" in English is:', promptEs: '"Estoy perdido" en inglés es:',
      answer: "I'm lost", options: ["I'm lost", 'I need help', 'I lost my key', 'Where is it?'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"La contraseña" in English is:', promptEs: '"La contraseña" en inglés es:',
      answer: 'password', options: ['password', 'wifi', 'address', 'ID'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Filling out a form',
      text: 'You are filling out a form at a community office and need to give your phone number, address, and ID.' },
    { label: 'Part 2: Asking for help at a public place',
      text: 'You are at a library or community center and need to ask where the bathroom is and what the wifi password is.' },
    { label: 'Part 3: Asking a stranger for help',
      text: 'You lost your keys or wallet, or you are lost on the street. Practice asking a stranger for help and explaining the problem.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'What is your phone ____?', promptEs: '¿Cuál es tu número de teléfono? (What is your phone ____?)', answer: 'number' },
    { id: 'w2', promptEn: 'Where is the ____?', promptEs: '¿Dónde está el baño? (Where is the ____?)', answer: 'bathroom' },
    { id: 'w3', promptEn: 'I need ____.', promptEs: 'Necesito ayuda. (I need ____.)', answer: 'help' },
    { id: 'w4', promptEn: 'I am ____.', promptEs: 'Estoy perdido. (I am ____.)', answer: 'lost' },
    { id: 'w5', promptEn: 'Can I use your ____?', promptEs: '¿Puedo usar tu teléfono? (Can I use your ____?)', answer: 'phone' },
  ],
}

export default module
