import type { Module } from '@/types'

const module: Module = {
  slug: 'family-tree',
  track: 'esl',
  titleEn: 'Family',
  titleEs: 'La Familia',
  descriptionEn: 'Learn how to talk about your family members in English.',
  descriptionEs: 'Aprende a hablar de los miembros de tu familia en inglés.',
  icon: 'Users',
  vocab: [
    {
      id: 'mother',
      en: 'mother / mom',
      es: 'la madre / mamá',
      exampleEn: 'My mother is a great cook.',
      exampleEs: 'Mi mamá cocina muy bien.',
    },
    {
      id: 'father',
      en: 'father / dad',
      es: 'el padre / papá',
      exampleEn: 'My father works in construction.',
      exampleEs: 'Mi papá trabaja en construcción.',
    },
    {
      id: 'brother',
      en: 'brother',
      es: 'el hermano',
      exampleEn: 'I have two brothers and one sister.',
      exampleEs: 'Tengo dos hermanos y una hermana.',
    },
    {
      id: 'sister',
      en: 'sister',
      es: 'la hermana',
      exampleEn: 'My sister lives in the Bronx.',
      exampleEs: 'Mi hermana vive en el Bronx.',
    },
    {
      id: 'son',
      en: 'son',
      es: 'el hijo',
      exampleEn: 'My son is seven years old.',
      exampleEs: 'Mi hijo tiene siete años.',
    },
    {
      id: 'daughter',
      en: 'daughter',
      es: 'la hija',
      exampleEn: 'My daughter is learning English at school.',
      exampleEs: 'Mi hija está aprendiendo inglés en la escuela.',
    },
    {
      id: 'grandparents',
      en: 'grandparents',
      es: 'los abuelos',
      exampleEn: 'My grandparents stayed in Mexico.',
      exampleEs: 'Mis abuelos se quedaron en México.',
    },
    {
      id: 'i-have',
      en: 'I have... / I don\'t have...',
      es: 'Tengo... / No tengo...',
      exampleEn: 'I have three children. I don\'t have any brothers.',
      exampleEs: 'Tengo tres hijos. No tengo hermanos.',
    },
    {
      id: 'husband-wife',
      en: 'husband / wife',
      es: 'el esposo / la esposa',
      exampleEn: 'My husband works in Manhattan.',
      exampleEs: 'Mi esposo trabaja en Manhattan.',
    },
    {
      id: 'children',
      en: 'children / kids',
      es: 'los hijos / los niños',
      exampleEn: 'I have three children.',
      exampleEs: 'Tengo tres hijos.',
    },
    {
      id: 'cousin',
      en: 'cousin',
      es: 'el primo / la prima',
      exampleEn: 'My cousin lives in Brooklyn.',
      exampleEs: 'Mi primo vive en Brooklyn.',
    },
    {
      id: 'aunt-uncle',
      en: 'aunt / uncle',
      es: 'la tía / el tío',
      exampleEn: 'My aunt and uncle came to visit.',
      exampleEs: 'Mi tía y mi tío vinieron de visita.',
    },
    {
      id: 'baby',
      en: 'baby',
      es: 'el bebé',
      exampleEn: 'My baby is one year old.',
      exampleEs: 'Mi bebé tiene un año.',
    },
    {
      id: 'how-many-children',
      en: 'How many children do you have?',
      es: '¿Cuántos hijos tienes?',
      exampleEn: 'How many children do you have? I have two.',
      exampleEs: '¿Cuántos hijos tienes? Tengo dos.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: '"La hermana" in English is:',
      promptEs: '"La hermana" en inglés es:',
      answer: 'sister',
      options: ['sister', 'daughter', 'mother', 'aunt'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: '"My son is seven years old" means:',
      promptEs: '"My son is seven years old" significa:',
      answer: 'Mi hijo tiene siete años',
      options: ['Mi hijo tiene siete años', 'Mi hermano tiene siete años', 'Mi padre tiene siete años', 'Mi hijo tiene siete hijos'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Los abuelos" in English is:',
      promptEs: '"Los abuelos" en inglés es:',
      answer: 'grandparents',
      options: ['grandparents', 'parents', 'children', 'cousins'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you say "Tengo dos hijos" in English?',
      promptEs: '¿Cómo se dice "Tengo dos hijos" en inglés?',
      answer: 'I have two children',
      options: ['I have two children', 'I have two brothers', 'I don\'t have children', 'My two sons'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"La hija" in English is:',
      promptEs: '"La hija" en inglés es:',
      answer: 'daughter',
      options: ['daughter', 'sister', 'mother', 'grandmother'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Talking about your immediate family',
      text: 'You are talking with a new friend at the church. They want to know about your parents and siblings, but you do not know the English words for family members.',
      script: [
        { speaker: 'tutor', en: "Let's practice talking about your family. I'll be your new friend from church. Tell me about your parents.", es: 'Vamos a practicar cómo hablar de tu familia. Yo seré tu nueva amiga de la iglesia. Cuéntame de tus padres.' },
        { speaker: 'student', en: 'My mother is a great cook. My father works in construction.', es: 'Mi mamá cocina muy bien. Mi papá trabaja en construcción.' },
        { speaker: 'tutor', en: 'That is nice! Do you have any brothers or sisters?', es: '¡Qué bien! ¿Tienes hermanos o hermanas?' },
        { speaker: 'student', en: 'I have two brothers and one sister.', es: 'Tengo dos hermanos y una hermana.' },
        { speaker: 'tutor', en: 'Where does your sister live?', es: '¿Dónde vive tu hermana?' },
        { speaker: 'student', en: 'My sister lives in the Bronx.', es: 'Mi hermana vive en el Bronx.' },
        { speaker: 'tutor', en: 'And your brothers, do they live nearby too?', es: '¿Y tus hermanos, también viven cerca?' },
        { speaker: 'student', en: "I have two brothers, but I don't have any sisters here in New York besides the one I mentioned.", es: 'Tengo dos hermanos, pero no tengo más hermanas aquí en Nueva York.' },
        { speaker: 'tutor', en: 'Thank you for sharing! Now you can talk about your parents and siblings with confidence.', es: '¡Gracias por compartir! Ahora puedes hablar de tus padres y hermanos con confianza.' },
      ],
    },
    {
      label: 'Part 2: Talking about your spouse and children',
      text: 'The conversation continues. Practice talking about your husband/wife and children, including how many children you have and their ages.',
      script: [
        { speaker: 'tutor', en: "Let's keep talking. I'll ask about your husband or wife and your children.", es: 'Sigamos hablando. Te preguntaré sobre tu esposo o esposa y tus hijos.' },
        { speaker: 'student', en: 'My husband works in Manhattan.', es: 'Mi esposo trabaja en Manhattan.' },
        { speaker: 'tutor', en: 'How many children do you have?', es: '¿Cuántos hijos tienes?' },
        { speaker: 'student', en: 'I have three children.', es: 'Tengo tres hijos.' },
        { speaker: 'tutor', en: 'Tell me about them. Do you have a son or a daughter?', es: '¿Cuéntame de ellos. Tienes un hijo o una hija?' },
        { speaker: 'student', en: 'My son is seven years old, and my daughter is learning English at school.', es: 'Mi hijo tiene siete años, y mi hija está aprendiendo inglés en la escuela.' },
        { speaker: 'tutor', en: 'That is wonderful. Do you have a baby too?', es: '¿Qué bonito. También tienes un bebé?' },
        { speaker: 'student', en: 'Yes, my baby is one year old.', es: 'Sí, mi bebé tiene un año.' },
        { speaker: 'tutor', en: 'Great job! You can now describe your husband or wife, your children, and their ages.', es: '¡Buen trabajo! Ahora puedes describir a tu esposo o esposa, tus hijos y sus edades.' },
      ],
    },
    {
      label: 'Part 3: Talking about extended family',
      text: 'Your friend asks about your cousins, aunts, and uncles. Practice describing your extended family and asking questions back about theirs.',
      script: [
        { speaker: 'tutor', en: 'Now tell me about your extended family. Do you have any cousins?', es: 'Ahora cuéntame de tu familia extendida. ¿Tienes primos?' },
        { speaker: 'student', en: 'Yes, my cousin lives in Brooklyn.', es: 'Sí, mi primo vive en Brooklyn.' },
        { speaker: 'tutor', en: 'Nice! What about your aunts and uncles?', es: '¡Qué bien! ¿Y tus tías y tíos?' },
        { speaker: 'student', en: 'My aunt and uncle came to visit last month.', es: 'Mi tía y mi tío vinieron de visita el mes pasado.' },
        { speaker: 'tutor', en: 'Are your grandparents here in the U.S.?', es: '¿Tus abuelos están aquí en los Estados Unidos?' },
        { speaker: 'student', en: 'No, my grandparents stayed in Mexico.', es: 'No, mis abuelos se quedaron en México.' },
        { speaker: 'tutor', en: 'Good. Now ask me a question back — how many children do I have?', es: 'Bien. Ahora pregúntame algo — ¿cuántos hijos tengo yo?' },
        { speaker: 'student', en: 'How many children do you have?', es: '¿Cuántos hijos tienes?' },
        { speaker: 'tutor', en: 'I have two children! Great job describing your extended family and asking questions back.', es: '¡Tengo dos hijos! Buen trabajo describiendo tu familia extendida y haciendo preguntas también.' },
      ],
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ two brothers.', promptEs: 'Tengo dos hermanos. (I ____ two brothers.)', answer: 'have' },
    { id: 'w2', promptEn: 'My ____ works in construction.', promptEs: 'Mi padre trabaja en construcción. (My ____ works in construction.)', answer: 'father' },
    { id: 'w3', promptEn: 'How many ____ do you have?', promptEs: '¿Cuántos hijos tienes? (How many ____ do you have?)', answer: 'children' },
    { id: 'w4', promptEn: 'This is my ____. She is my father\'s sister.', promptEs: 'Esta es mi tía. (This is my ____.)', answer: 'aunt' },
    { id: 'w5', promptEn: 'My ____ is one year old.', promptEs: 'Mi bebé tiene un año. (My ____ is one year old.)', answer: 'baby' },
  ],
}

export default module
