import type { Module } from '@/types'

const module: Module = {
  slug: 'gerunds-and-infinitives',
  track: 'esl',
  titleEn: 'Gerunds and Infinitives',
  titleEs: 'Gerundios e Infinitivos',
  descriptionEn: 'Learn how to talk about things you like doing, need to do, and want to do.',
  descriptionEs: 'Aprende a hablar de cosas que te gusta hacer, necesitas hacer y quieres hacer.',
  icon: 'Repeat',
  vocab: [
    { id: 'i-like-ing', en: 'I like ...-ing', es: 'Me gusta + gerundio',
      exampleEn: 'I like cooking.', exampleEs: 'Me gusta cocinar.' },
    { id: 'i-want-to', en: 'I want to...', es: 'Quiero...',
      exampleEn: 'I want to learn English.', exampleEs: 'Quiero aprender inglés.' },
    { id: 'i-need-to', en: 'I need to...', es: 'Necesito...',
      exampleEn: 'I need to go to work.', exampleEs: 'Necesito ir al trabajo.' },
    { id: 'i-have-to', en: 'I have to...', es: 'Tengo que...',
      exampleEn: 'I have to pick up my kids.', exampleEs: 'Tengo que recoger a mis hijos.' },
    { id: 'i-enjoy-ing', en: 'I enjoy ...-ing', es: 'Disfruto + gerundio',
      exampleEn: 'I enjoy walking in the park.', exampleEs: 'Disfruto caminar en el parque.' },
    { id: 'i-stopped-ing', en: 'I stopped ...-ing', es: 'Dejé de...',
      exampleEn: 'I stopped smoking.', exampleEs: 'Dejé de fumar.' },
    { id: 'i-started-ing', en: 'I started ...-ing', es: 'Empecé a...',
      exampleEn: 'I started studying English.', exampleEs: 'Empecé a estudiar inglés.' },
    { id: 'working', en: 'working', es: 'trabajando / el trabajar',
      exampleEn: 'Working helps me support my family.', exampleEs: 'Trabajar me ayuda a mantener a mi familia.' },
    { id: 'reading', en: 'reading', es: 'leyendo / el leer',
      exampleEn: 'Reading helps me learn new words.', exampleEs: 'Leer me ayuda a aprender palabras nuevas.' },
    { id: 'cooking', en: 'cooking', es: 'cocinando / el cocinar',
      exampleEn: 'Cooking for my family makes me happy.', exampleEs: 'Cocinar para mi familia me hace feliz.' },
    { id: 'i-love-to', en: 'I love to...', es: 'Me encanta...',
      exampleEn: 'I love to dance.', exampleEs: 'Me encanta bailar.' },
    { id: 'i-like-to', en: 'I like to...', es: 'Me gusta...',
      exampleEn: 'I like to sing.', exampleEs: 'Me gusta cantar.' },
    { id: 'i-plan-to', en: 'I plan to...', es: 'Planeo...',
      exampleEn: 'I plan to study tonight.', exampleEs: 'Planeo estudiar esta noche.' },
    { id: 'i-hope-to', en: 'I hope to...', es: 'Espero...',
      exampleEn: 'I hope to find a good job.', exampleEs: 'Espero encontrar un buen trabajo.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'How do you say "Necesito ir al trabajo"?', promptEs: '¿Cómo se dice "Necesito ir al trabajo"?',
      answer: 'I need to go to work', options: ['I need to go to work', 'I want to go to work', 'I like to go to work', 'I stopped going to work'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "I like ___." (cocinar)', promptEs: 'Completa: "I like ___." (cocinar)',
      answer: 'cooking', options: ['cooking', 'cook', 'to cooking', 'cooked'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Tengo que" in English is:', promptEs: '"Tengo que" en inglés es:',
      answer: 'I have to', options: ['I have to', 'I like to', 'I hope to', 'I stopped'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "I want ___ learn English."', promptEs: 'Completa: "I want ___ learn English."',
      answer: 'to', options: ['to', 'ing', 'for', 'at'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"Empecé a estudiar inglés" in English is:', promptEs: '"Empecé a estudiar inglés" en inglés es:',
      answer: 'I started studying English', options: ['I started studying English', 'I stopped studying English', 'I need to study English', 'I enjoy English'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about things you enjoy',
      text: 'Practice talking about hobbies and things you like doing in your free time, using "I like...", "I enjoy...", and "I love to...".' },
    { label: 'Part 2: Talking about daily obligations',
      text: 'Practice talking about things you have to do or need to do each day, like picking up your kids or going to work.' },
    { label: 'Part 3: Talking about goals and hopes',
      text: 'Practice talking about your goals, like learning English or finding a good job, using "I want to...", "I plan to...", and "I hope to...".' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I like ____.', promptEs: 'Me gusta cocinar. (I like ____.)', answer: 'cooking' },
    { id: 'w2', promptEn: 'I need ____ go to work.', promptEs: 'Necesito ir al trabajo. (I need ____ go to work.)', answer: 'to' },
    { id: 'w3', promptEn: 'I have ____ pick up my kids.', promptEs: 'Tengo que recoger a mis hijos. (I have ____ pick up my kids.)', answer: 'to' },
    { id: 'w4', promptEn: 'I want ____ learn English.', promptEs: 'Quiero aprender inglés. (I want ____ learn English.)', answer: 'to' },
    { id: 'w5', promptEn: 'I enjoy ____ in the park.', promptEs: 'Disfruto caminar en el parque. (I enjoy ____ in the park.)', answer: 'walking' },
  ],
}

export default module
