import type { Module } from '@/types'

const module: Module = {
  slug: 'gerunds-and-infinitives',
  track: 'esl',
  titleEn: 'Gerunds and Infinitives',
  titleEs: 'Gerundios e Infinitivos',
  descriptionEn: 'Learn how to talk about things you like doing, need to do, and want to do.',
  descriptionEs: 'Aprende a hablar de cosas que te gusta hacer, necesitas hacer y quieres hacer.',
  icon: 'Repeat',
  vocab: [
    { id: 'i-like-ing', en: 'I like ...-ing', es: 'Me gusta + gerundio',
      exampleEn: 'I like cooking.', exampleEs: 'Me gusta cocinar.' },
    { id: 'i-want-to', en: 'I want to...', es: 'Quiero...',
      exampleEn: 'I want to learn English.', exampleEs: 'Quiero aprender inglés.' },
    { id: 'i-need-to', en: 'I need to...', es: 'Necesito...',
      exampleEn: 'I need to go to work.', exampleEs: 'Necesito ir al trabajo.' },
    { id: 'i-have-to', en: 'I have to...', es: 'Tengo que...',
      exampleEn: 'I have to pick up my kids.', exampleEs: 'Tengo que recoger a mis hijos.' },
    { id: 'i-enjoy-ing', en: 'I enjoy ...-ing', es: 'Disfruto + gerundio',
      exampleEn: 'I enjoy walking in the park.', exampleEs: 'Disfruto caminar en el parque.' },
    { id: 'i-stopped-ing', en: 'I stopped ...-ing', es: 'Dejé de...',
      exampleEn: 'I stopped smoking.', exampleEs: 'Dejé de fumar.' },
    { id: 'i-started-ing', en: 'I started ...-ing', es: 'Empecé a...',
      exampleEn: 'I started studying English.', exampleEs: 'Empecé a estudiar inglés.' },
    { id: 'working', en: 'working', es: 'trabajando / el trabajar',
      exampleEn: 'Working helps me support my family.', exampleEs: 'Trabajar me ayuda a mantener a mi familia.' },
    { id: 'reading', en: 'reading', es: 'leyendo / el leer',
      exampleEn: 'Reading helps me learn new words.', exampleEs: 'Leer me ayuda a aprender palabras nuevas.' },
    { id: 'cooking', en: 'cooking', es: 'cocinando / el cocinar',
      exampleEn: 'Cooking for my family makes me happy.', exampleEs: 'Cocinar para mi familia me hace feliz.' },
    { id: 'i-love-to', en: 'I love to...', es: 'Me encanta...',
      exampleEn: 'I love to dance.', exampleEs: 'Me encanta bailar.' },
    { id: 'i-like-to', en: 'I like to...', es: 'Me gusta...',
      exampleEn: 'I like to sing.', exampleEs: 'Me gusta cantar.' },
    { id: 'i-plan-to', en: 'I plan to...', es: 'Planeo...',
      exampleEn: 'I plan to study tonight.', exampleEs: 'Planeo estudiar esta noche.' },
    { id: 'i-hope-to', en: 'I hope to...', es: 'Espero...',
      exampleEn: 'I hope to find a good job.', exampleEs: 'Espero encontrar un buen trabajo.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'How do you say "Necesito ir al trabajo"?', promptEs: '¿Cómo se dice "Necesito ir al trabajo"?',
      answer: 'I need to go to work', options: ['I need to go to work', 'I want to go to work', 'I like to go to work', 'I stopped going to work'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "I like ___." (cocinar)', promptEs: 'Completa: "I like ___." (cocinar)',
      answer: 'cooking', options: ['cooking', 'cook', 'to cooking', 'cooked'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Tengo que" in English is:', promptEs: '"Tengo que" en inglés es:',
      answer: 'I have to', options: ['I have to', 'I like to', 'I hope to', 'I stopped'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "I want ___ learn English."', promptEs: 'Completa: "I want ___ learn English."',
      answer: 'to', options: ['to', 'ing', 'for', 'at'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"Empecé a estudiar inglés" in English is:', promptEs: '"Empecé a estudiar inglés" en inglés es:',
      answer: 'I started studying English', options: ['I started studying English', 'I stopped studying English', 'I need to study English', 'I enjoy English'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about things you enjoy',
      text: 'Practice talking about hobbies and things you like doing in your free time, using "I like...", "I enjoy...", and "I love to...".',
      script: [
        { speaker: 'tutor', en: "Let's talk about your free time. What do you like doing?", es: 'Hablemos de tu tiempo libre. ¿Qué te gusta hacer?' },
        { speaker: 'student', en: 'I like cooking.', es: 'Me gusta cocinar.' },
        { speaker: 'tutor', en: 'Nice! Do you enjoy cooking for your family?', es: '¡Qué bien! ¿Disfrutas cocinar para tu familia?' },
        { speaker: 'student', en: 'Yes, cooking for my family makes me happy.', es: 'Sí, cocinar para mi familia me hace feliz.' },
        { speaker: 'tutor', en: 'That is wonderful. What else do you like to do?', es: 'Qué maravilloso. ¿Qué más te gusta hacer?' },
        { speaker: 'student', en: 'I love to dance.', es: 'Me encanta bailar.' },
        { speaker: 'tutor', en: 'Fun! And do you enjoy reading too?', es: '¡Divertido! ¿Y también disfrutas leer?' },
        { speaker: 'student', en: 'Yes, I enjoy walking in the park, and reading helps me learn new words.', es: 'Sí, disfruto caminar en el parque, y leer me ayuda a aprender palabras nuevas.' },
        { speaker: 'tutor', en: 'Great answers! You used "like", "enjoy", and "love to" perfectly.', es: '¡Excelentes respuestas! Usaste "like", "enjoy" y "love to" perfectamente.' },
      ] },
    { label: 'Part 2: Talking about daily obligations',
      text: 'Practice talking about things you have to do or need to do each day, like picking up your kids or going to work.',
      script: [
        { speaker: 'tutor', en: 'Tell me about your day. What do you have to do this morning?', es: 'Cuéntame de tu día. ¿Qué tienes que hacer esta mañana?' },
        { speaker: 'student', en: 'I need to go to work.', es: 'Necesito ir al trabajo.' },
        { speaker: 'tutor', en: 'Okay. And what do you have to do after work?', es: 'Bien. ¿Y qué tienes que hacer después del trabajo?' },
        { speaker: 'student', en: 'I have to pick up my kids.', es: 'Tengo que recoger a mis hijos.' },
        { speaker: 'tutor', en: 'That is a busy day! Do you need to do anything else?', es: '¡Qué día tan ocupado! ¿Necesitas hacer algo más?' },
        { speaker: 'student', en: 'Yes, I need to cook dinner for my family.', es: 'Sí, necesito cocinar la cena para mi familia.' },
        { speaker: 'tutor', en: 'You are doing a lot! Did you stop doing anything to have more time?', es: '¡Haces mucho! ¿Dejaste de hacer algo para tener más tiempo?' },
        { speaker: 'student', en: 'I stopped working on Sundays.', es: 'Dejé de trabajar los domingos.' },
        { speaker: 'tutor', en: 'Smart! You explained your obligations very clearly.', es: '¡Inteligente! Explicaste tus obligaciones muy claramente.' },
      ] },
    { label: 'Part 3: Talking about goals and hopes',
      text: 'Practice talking about your goals, like learning English or finding a good job, using "I want to...", "I plan to...", and "I hope to...".',
      script: [
        { speaker: 'tutor', en: "Let's talk about your goals. What do you want to do this year?", es: 'Hablemos de tus metas. ¿Qué quieres hacer este año?' },
        { speaker: 'student', en: 'I want to learn English.', es: 'Quiero aprender inglés.' },
        { speaker: 'tutor', en: 'That is a great goal! When did you start studying?', es: '¡Excelente meta! ¿Cuándo empezaste a estudiar?' },
        { speaker: 'student', en: 'I started studying English last year.', es: 'Empecé a estudiar inglés el año pasado.' },
        { speaker: 'tutor', en: 'Wonderful progress. What do you plan to do tonight to practice?', es: 'Progreso maravilloso. ¿Qué planeas hacer esta noche para practicar?' },
        { speaker: 'student', en: 'I plan to study tonight.', es: 'Planeo estudiar esta noche.' },
        { speaker: 'tutor', en: 'Good! And what do you hope to do in the future?', es: '¡Bien! ¿Y qué esperas hacer en el futuro?' },
        { speaker: 'student', en: 'I hope to find a good job.', es: 'Espero encontrar un buen trabajo.' },
        { speaker: 'tutor', en: 'Wonderful hopes! You used "want to", "plan to", and "hope to" beautifully.', es: '¡Maravillosas esperanzas! Usaste "want to", "plan to" y "hope to" maravillosamente.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I like ____.', promptEs: 'Me gusta cocinar. (I like ____.)', answer: 'cooking' },
    { id: 'w2', promptEn: 'I need ____ go to work.', promptEs: 'Necesito ir al trabajo. (I need ____ go to work.)', answer: 'to' },
    { id: 'w3', promptEn: 'I have ____ pick up my kids.', promptEs: 'Tengo que recoger a mis hijos. (I have ____ pick up my kids.)', answer: 'to' },
    { id: 'w4', promptEn: 'I want ____ learn English.', promptEs: 'Quiero aprender inglés. (I want ____ learn English.)', answer: 'to' },
    { id: 'w5', promptEn: 'I enjoy ____ in the park.', promptEs: 'Disfruto caminar en el parque. (I enjoy ____ in the park.)', answer: 'walking' },
  ],
}

export default module
