import type { Module } from '@/types'

const module: Module = {
  slug: 'health-emergencies',
  track: 'esl',
  titleEn: 'Health Needs & Emergencies',
  titleEs: 'Necesidades de Salud y Emergencias',
  descriptionEn: 'Learn how to describe symptoms, ask for medical help, and handle an emergency.',
  descriptionEs: 'Aprende a describir síntomas, pedir ayuda médica y manejar una emergencia.',
  icon: 'HeartPulse',
  vocab: [
    { id: 'doctor', en: 'doctor', es: 'el doctor / la doctora',
      exampleEn: 'I need to see a doctor.', exampleEs: 'Necesito ver a un doctor.' },
    { id: 'hospital', en: 'hospital', es: 'el hospital',
      exampleEn: 'The hospital is near my house.', exampleEs: 'El hospital está cerca de mi casa.' },
    { id: 'i-feel-sick', en: 'I feel sick', es: 'Me siento mal',
      exampleEn: 'I feel sick today.', exampleEs: 'Me siento mal hoy.' },
    { id: 'pain-it-hurts', en: 'pain / it hurts', es: 'el dolor / me duele',
      exampleEn: 'My stomach hurts.', exampleEs: 'Me duele el estómago.' },
    { id: 'i-have-a-fever', en: 'I have a fever', es: 'Tengo fiebre',
      exampleEn: 'I have a fever and a cough.', exampleEs: 'Tengo fiebre y tos.' },
    { id: 'call-911', en: 'Call 911', es: 'Llame al 911',
      exampleEn: 'Call 911, it is an emergency!', exampleEs: '¡Llame al 911, es una emergencia!' },
    { id: 'emergency-room', en: 'emergency room', es: 'la sala de emergencias',
      exampleEn: 'We need to go to the emergency room.', exampleEs: 'Necesitamos ir a la sala de emergencias.' },
    { id: 'ambulance', en: 'ambulance', es: 'la ambulancia',
      exampleEn: 'The ambulance is coming.', exampleEs: 'La ambulancia está llegando.' },
    { id: 'medicine-pills', en: 'medicine / pills', es: 'la medicina / las pastillas',
      exampleEn: 'Take this medicine twice a day.', exampleEs: 'Tome esta medicina dos veces al día.' },
    { id: 'pharmacy', en: 'pharmacy', es: 'la farmacia',
      exampleEn: 'I need to pick up medicine at the pharmacy.', exampleEs: 'Necesito recoger medicina en la farmacia.' },
    { id: 'insurance', en: 'insurance', es: 'el seguro médico',
      exampleEn: 'Do you have insurance?', exampleEs: '¿Tiene seguro médico?' },
    { id: 'i-need-to-see-a-doctor', en: 'I need to see a doctor', es: 'Necesito ver a un doctor',
      exampleEn: 'I need to see a doctor today.', exampleEs: 'Necesito ver a un doctor hoy.' },
    { id: 'are-you-okay', en: 'Are you okay?', es: '¿Estás bien?',
      exampleEn: 'Are you okay? You look sick.', exampleEs: '¿Estás bien? Te ves enfermo.' },
    { id: 'help', en: 'Help!', es: '¡Ayuda!',
      exampleEn: 'Help! Someone call 911!', exampleEs: '¡Ayuda! ¡Alguien llame al 911!' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"El hospital" in English is:', promptEs: '"El hospital" en inglés es:',
      answer: 'hospital', options: ['hospital', 'pharmacy', 'doctor', 'insurance'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you say "Me duele"?', promptEs: '¿Cómo se dice "Me duele"?',
      answer: 'It hurts', options: ['It hurts', 'I feel sick', 'I have a fever', 'Help!'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'What number do you call for an emergency in the US?', promptEs: '¿A qué número llamas para una emergencia en Estados Unidos?',
      answer: '911', options: ['911', '311', '411', '511'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"La farmacia" in English is:', promptEs: '"La farmacia" en inglés es:',
      answer: 'pharmacy', options: ['pharmacy', 'hospital', 'emergency room', 'insurance'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you say "Necesito ver a un doctor"?', promptEs: '¿Cómo se dice "Necesito ver a un doctor"?',
      answer: 'I need to see a doctor', options: ['I need to see a doctor', 'I feel sick', 'Call 911', 'Are you okay?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Describing symptoms to a doctor',
      text: 'You are at a clinic and need to describe how you feel — that you feel sick, have a fever, or something hurts.' },
    { label: 'Part 2: A medical emergency',
      text: 'Someone near you is badly hurt. Practice calling for help, saying "Call 911," and asking "Are you okay?"' },
    { label: 'Part 3: At the pharmacy',
      text: 'Practice picking up medicine at the pharmacy and answering questions about insurance.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I feel ____.', promptEs: 'Me siento mal. (I feel ____.)', answer: 'sick' },
    { id: 'w2', promptEn: 'I have a ____.', promptEs: 'Tengo fiebre. (I have a ____.)', answer: 'fever' },
    { id: 'w3', promptEn: 'My stomach ____.', promptEs: 'Me duele el estómago. (My stomach ____.)', answer: 'hurts' },
    { id: 'w4', promptEn: 'Call ____!', promptEs: '¡Llame al 911! (Call ____!)', answer: '911' },
    { id: 'w5', promptEn: 'I need to see a ____.', promptEs: 'Necesito ver a un doctor. (I need to see a ____.)', answer: 'doctor' },
  ],
}

export default module
