import type { Module } from '@/types'

const module: Module = {
  slug: 'health-emergencies',
  track: 'esl',
  titleEn: 'Health Needs & Emergencies',
  titleEs: 'Necesidades de Salud y Emergencias',
  descriptionEn: 'Learn how to describe symptoms, ask for medical help, and handle an emergency.',
  descriptionEs: 'Aprende a describir síntomas, pedir ayuda médica y manejar una emergencia.',
  icon: 'HeartPulse',
  vocab: [
    { id: 'doctor', en: 'doctor', es: 'el doctor / la doctora',
      exampleEn: 'I need to see a doctor.', exampleEs: 'Necesito ver a un doctor.' },
    { id: 'hospital', en: 'hospital', es: 'el hospital',
      exampleEn: 'The hospital is near my house.', exampleEs: 'El hospital está cerca de mi casa.' },
    { id: 'i-feel-sick', en: 'I feel sick', es: 'Me siento mal',
      exampleEn: 'I feel sick today.', exampleEs: 'Me siento mal hoy.' },
    { id: 'pain-it-hurts', en: 'pain / it hurts', es: 'el dolor / me duele',
      exampleEn: 'My stomach hurts.', exampleEs: 'Me duele el estómago.' },
    { id: 'i-have-a-fever', en: 'I have a fever', es: 'Tengo fiebre',
      exampleEn: 'I have a fever and a cough.', exampleEs: 'Tengo fiebre y tos.' },
    { id: 'call-911', en: 'Call 911', es: 'Llame al 911',
      exampleEn: 'Call 911, it is an emergency!', exampleEs: '¡Llame al 911, es una emergencia!' },
    { id: 'emergency-room', en: 'emergency room', es: 'la sala de emergencias',
      exampleEn: 'We need to go to the emergency room.', exampleEs: 'Necesitamos ir a la sala de emergencias.' },
    { id: 'ambulance', en: 'ambulance', es: 'la ambulancia',
      exampleEn: 'The ambulance is coming.', exampleEs: 'La ambulancia está llegando.' },
    { id: 'medicine-pills', en: 'medicine / pills', es: 'la medicina / las pastillas',
      exampleEn: 'Take this medicine twice a day.', exampleEs: 'Tome esta medicina dos veces al día.' },
    { id: 'pharmacy', en: 'pharmacy', es: 'la farmacia',
      exampleEn: 'I need to pick up medicine at the pharmacy.', exampleEs: 'Necesito recoger medicina en la farmacia.' },
    { id: 'insurance', en: 'insurance', es: 'el seguro médico',
      exampleEn: 'Do you have insurance?', exampleEs: '¿Tiene seguro médico?' },
    { id: 'i-need-to-see-a-doctor', en: 'I need to see a doctor', es: 'Necesito ver a un doctor',
      exampleEn: 'I need to see a doctor today.', exampleEs: 'Necesito ver a un doctor hoy.' },
    { id: 'are-you-okay', en: 'Are you okay?', es: '¿Estás bien?',
      exampleEn: 'Are you okay? You look sick.', exampleEs: '¿Estás bien? Te ves enfermo.' },
    { id: 'help', en: 'Help!', es: '¡Ayuda!',
      exampleEn: 'Help! Someone call 911!', exampleEs: '¡Ayuda! ¡Alguien llame al 911!' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"El hospital" in English is:', promptEs: '"El hospital" en inglés es:',
      answer: 'hospital', options: ['hospital', 'pharmacy', 'doctor', 'insurance'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you say "Me duele"?', promptEs: '¿Cómo se dice "Me duele"?',
      answer: 'It hurts', options: ['It hurts', 'I feel sick', 'I have a fever', 'Help!'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'What number do you call for an emergency in the US?', promptEs: '¿A qué número llamas para una emergencia en Estados Unidos?',
      answer: '911', options: ['911', '311', '411', '511'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"La farmacia" in English is:', promptEs: '"La farmacia" en inglés es:',
      answer: 'pharmacy', options: ['pharmacy', 'hospital', 'emergency room', 'insurance'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you say "Necesito ver a un doctor"?', promptEs: '¿Cómo se dice "Necesito ver a un doctor"?',
      answer: 'I need to see a doctor', options: ['I need to see a doctor', 'I feel sick', 'Call 911', 'Are you okay?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Describing symptoms to a doctor',
      text: 'You are at a clinic and need to describe how you feel — that you feel sick, have a fever, or something hurts.',
      script: [
        { speaker: 'tutor', en: "I'll be the doctor at the clinic. Tell me how you feel.", es: 'Yo seré el doctor en la clínica. Dígame cómo se siente.' },
        { speaker: 'student', en: 'I feel sick today.', es: 'Me siento mal hoy.' },
        { speaker: 'tutor', en: 'I am sorry to hear that. Do you have a fever?', es: 'Lo siento. ¿Tiene fiebre?' },
        { speaker: 'student', en: 'Yes, I have a fever and a cough.', es: 'Sí, tengo fiebre y tos.' },
        { speaker: 'tutor', en: 'Does anything hurt?', es: '¿Le duele algo?' },
        { speaker: 'student', en: 'My stomach hurts.', es: 'Me duele el estómago.' },
        { speaker: 'tutor', en: 'I see. When did you start feeling sick?', es: 'Entiendo. ¿Cuándo empezó a sentirse mal?' },
        { speaker: 'student', en: 'I need to see a doctor because I feel sick and my stomach hurts.', es: 'Necesito ver a un doctor porque me siento mal y me duele el estómago.' },
        { speaker: 'tutor', en: 'Thank you for explaining your symptoms so clearly. I can help you feel better.', es: 'Gracias por explicar sus síntomas tan claramente. Puedo ayudarle a sentirse mejor.' },
      ] },
    { label: 'Part 2: A medical emergency',
      text: 'Someone near you is badly hurt. Practice calling for help, saying "Call 911," and asking "Are you okay?"',
      script: [
        { speaker: 'tutor', en: "Now let's practice an emergency. I'll pretend to be hurt on the street. What do you say first?", es: 'Ahora vamos a practicar una emergencia. Yo fingiré estar lastimado en la calle. ¿Qué dice primero?' },
        { speaker: 'student', en: 'Are you okay?', es: '¿Estás bien?' },
        { speaker: 'tutor', en: "No, I'm hurt badly! Please help.", es: '¡No, estoy muy lastimado! Por favor ayúdeme.' },
        { speaker: 'student', en: 'Help! Someone call 911!', es: '¡Ayuda! ¡Alguien llame al 911!' },
        { speaker: 'tutor', en: 'Good, you are calling for help. What do you tell the 911 operator?', es: 'Bien, está pidiendo ayuda. ¿Qué le dice al operador de 911?' },
        { speaker: 'student', en: 'Call 911, it is an emergency! We need an ambulance.', es: '¡Llame al 911, es una emergencia! Necesitamos una ambulancia.' },
        { speaker: 'tutor', en: 'The ambulance is coming. Where should they take me?', es: 'La ambulancia está llegando. ¿Adónde deben llevarme?' },
        { speaker: 'student', en: 'We need to go to the emergency room.', es: 'Necesitamos ir a la sala de emergencias.' },
        { speaker: 'tutor', en: 'Excellent! You knew exactly how to ask for help and call for emergency care.', es: '¡Excelente! Supo exactamente cómo pedir ayuda y llamar para atención de emergencia.' },
      ] },
    { label: 'Part 3: At the pharmacy',
      text: 'Practice picking up medicine at the pharmacy and answering questions about insurance.',
      script: [
        { speaker: 'tutor', en: "Let's practice the pharmacy. I'll be the pharmacist. How can I help you?", es: 'Vamos a practicar en la farmacia. Yo seré el farmacéutico. ¿Cómo puedo ayudarle?' },
        { speaker: 'student', en: 'I need to pick up medicine at the pharmacy.', es: 'Necesito recoger medicina en la farmacia.' },
        { speaker: 'tutor', en: 'Sure, what is your name, and do you have insurance?', es: 'Claro, ¿cuál es su nombre, y tiene seguro médico?' },
        { speaker: 'student', en: 'Yes, I have insurance.', es: 'Sí, tengo seguro médico.' },
        { speaker: 'tutor', en: 'Great, here are your pills. Take this medicine twice a day.', es: 'Muy bien, aquí están sus pastillas. Tome esta medicina dos veces al día.' },
        { speaker: 'student', en: 'Twice a day, thank you. What if I do not have insurance next time?', es: 'Dos veces al día, gracias. ¿Y si no tengo seguro médico la próxima vez?' },
        { speaker: 'tutor', en: 'We can talk about payment options without insurance too.', es: 'También podemos hablar de opciones de pago sin seguro médico.' },
        { speaker: 'student', en: 'Thank you very much for your help.', es: 'Muchas gracias por su ayuda.' },
        { speaker: 'tutor', en: 'You are welcome! Now you can confidently pick up medicine and talk about insurance at the pharmacy.', es: '¡De nada! Ahora puede recoger medicina y hablar sobre el seguro médico en la farmacia con confianza.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I feel ____.', promptEs: 'Me siento mal. (I feel ____.)', answer: 'sick' },
    { id: 'w2', promptEn: 'I have a ____.', promptEs: 'Tengo fiebre. (I have a ____.)', answer: 'fever' },
    { id: 'w3', promptEn: 'My stomach ____.', promptEs: 'Me duele el estómago. (My stomach ____.)', answer: 'hurts' },
    { id: 'w4', promptEn: 'Call ____!', promptEs: '¡Llame al 911! (Call ____!)', answer: '911' },
    { id: 'w5', promptEn: 'I need to see a ____.', promptEs: 'Necesito ver a un doctor. (I need to see a ____.)', answer: 'doctor' },
  ],
}

export default module
