import type { Module } from '@/types'

const module: Module = {
  slug: 'introducing-yourself',
  track: 'esl',
  titleEn: 'Introducing Yourself',
  titleEs: 'Presentarte',
  descriptionEn: 'Learn how to meet new people and share basic information about yourself.',
  descriptionEs: 'Aprende a conocer personas nuevas y compartir información básica sobre ti.',
  icon: 'Hand',
  vocab: [
    {
      id: 'my-name-is',
      en: 'My name is...',
      es: 'Me llamo... / Mi nombre es...',
      exampleEn: 'My name is Maria. Nice to meet you!',
      exampleEs: 'Me llamo María. ¡Mucho gusto!',
    },
    {
      id: 'nice-to-meet-you',
      en: 'Nice to meet you',
      es: 'Mucho gusto',
      exampleEn: 'Nice to meet you! My name is Carlos.',
      exampleEs: '¡Mucho gusto! Me llamo Carlos.',
    },
    {
      id: 'i-am-from',
      en: 'I am from...',
      es: 'Soy de...',
      exampleEn: 'I am from Mexico. Where are you from?',
      exampleEs: 'Soy de México. ¿De dónde eres tú?',
    },
    {
      id: 'i-live-in',
      en: 'I live in...',
      es: 'Vivo en...',
      exampleEn: 'I live in Queens, New York.',
      exampleEs: 'Vivo en Queens, Nueva York.',
    },
    {
      id: 'i-speak',
      en: 'I speak...',
      es: 'Hablo...',
      exampleEn: 'I speak Spanish and a little English.',
      exampleEs: 'Hablo español y un poco de inglés.',
    },
    {
      id: 'how-are-you',
      en: 'How are you?',
      es: '¿Cómo estás?',
      exampleEn: 'Hello! How are you today?',
      exampleEs: '¡Hola! ¿Cómo estás hoy?',
    },
    {
      id: 'i-am-fine',
      en: 'I am fine, thank you',
      es: 'Estoy bien, gracias',
      exampleEn: 'I am fine, thank you. And you?',
      exampleEs: 'Estoy bien, gracias. ¿Y tú?',
    },
    {
      id: 'what-is-your-name',
      en: 'What is your name?',
      es: '¿Cómo te llamas?',
      exampleEn: 'Excuse me, what is your name?',
      exampleEs: 'Disculpa, ¿cómo te llamas?',
    },
    {
      id: 'good-morning',
      en: 'Good morning / Good afternoon',
      es: 'Buenos días / Buenas tardes',
      exampleEn: 'Good morning! Nice to meet you.',
      exampleEs: '¡Buenos días! Mucho gusto.',
    },
    {
      id: 'how-old-are-you',
      en: 'How old are you?',
      es: '¿Cuántos años tienes?',
      exampleEn: 'How old are you? I am thirty years old.',
      exampleEs: '¿Cuántos años tienes? Tengo treinta años.',
    },
    {
      id: 'i-am-years-old',
      en: 'I am ... years old',
      es: 'Tengo ... años',
      exampleEn: 'I am thirty-five years old.',
      exampleEs: 'Tengo treinta y cinco años.',
    },
    {
      id: 'what-do-you-do',
      en: 'What do you do?',
      es: '¿A qué te dedicas?',
      exampleEn: 'What do you do? I work in construction.',
      exampleEs: '¿A qué te dedicas? Trabajo en construcción.',
    },
    {
      id: 'i-work-as',
      en: 'I work as a...',
      es: 'Trabajo como...',
      exampleEn: 'I work as a cook.',
      exampleEs: 'Trabajo como cocinero.',
    },
    {
      id: 'goodbye',
      en: 'Goodbye / See you later',
      es: 'Adiós / Hasta luego',
      exampleEn: 'Goodbye! It was nice to meet you.',
      exampleEs: '¡Adiós! Fue un placer conocerte.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'How do you say "Me llamo..." in English?',
      promptEs: '¿Cómo se dice "Me llamo..." en inglés?',
      answer: 'My name is...',
      options: ['My name is...', 'I live in...', 'I am from...', 'How are you?'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'What does "Nice to meet you" mean?',
      promptEs: '¿Qué significa "Nice to meet you"?',
      answer: 'Mucho gusto',
      options: ['Mucho gusto', 'Hasta luego', 'Soy de México', 'Estoy bien'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: 'How do you ask someone\'s name in English?',
      promptEs: '¿Cómo preguntas el nombre de alguien en inglés?',
      answer: 'What is your name?',
      options: ['What is your name?', 'Where are you from?', 'How are you?', 'I live in...'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: '"Soy de México" in English is:',
      promptEs: '"Soy de México" en inglés es:',
      answer: 'I am from Mexico',
      options: ['I am from Mexico', 'I live in Mexico', 'I speak Mexico', 'I am Mexico'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: 'How do you respond when someone asks "How are you?"',
      promptEs: '¿Cómo respondes cuando alguien pregunta "How are you?"',
      answer: 'I am fine, thank you',
      options: ['I am fine, thank you', 'Nice to meet you', 'My name is Carlos', 'I am from Queens'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Meeting someone new',
      text: 'You just arrived at a church community event in Queens. You want to meet the people there but do not know how to introduce yourself or start a conversation in English.',
      script: [
        { speaker: 'tutor', en: 'Good morning! Welcome to our church group.', es: '¡Buenos días! Bienvenido a nuestro grupo de la iglesia.' },
        { speaker: 'student', en: 'Good morning! Thank you.', es: '¡Buenos días! Gracias.' },
        { speaker: 'tutor', en: 'What is your name?', es: '¿Cómo te llamas?' },
        { speaker: 'student', en: 'My name is Rosa.', es: 'Me llamo Rosa.' },
        { speaker: 'tutor', en: 'Nice to meet you, Rosa!', es: '¡Mucho gusto, Rosa!' },
        { speaker: 'student', en: 'Nice to meet you too.', es: 'Mucho gusto también.' },
        { speaker: 'tutor', en: 'How are you today?', es: '¿Cómo estás hoy?' },
        { speaker: 'student', en: 'I am fine, thank you. And you?', es: 'Estoy bien, gracias. ¿Y tú?' },
        { speaker: 'tutor', en: 'I am fine, thank you. I am glad you came today.', es: 'Estoy bien, gracias. Me alegra que hayas venido hoy.' },
      ],
    },
    {
      label: 'Part 2: Sharing more about yourself',
      text: 'The conversation continues. Practice sharing where you are from, where you live now, what languages you speak, and your age.',
      script: [
        { speaker: 'tutor', en: 'So Rosa, where are you from?', es: 'Entonces Rosa, ¿de dónde eres?' },
        { speaker: 'student', en: 'I am from Mexico.', es: 'Soy de México.' },
        { speaker: 'tutor', en: 'And where do you live now?', es: '¿Y dónde vives ahora?' },
        { speaker: 'student', en: 'I live in Queens, New York.', es: 'Vivo en Queens, Nueva York.' },
        { speaker: 'tutor', en: 'What languages do you speak?', es: '¿Qué idiomas hablas?' },
        { speaker: 'student', en: 'I speak Spanish and a little English.', es: 'Hablo español y un poco de inglés.' },
        { speaker: 'tutor', en: 'How old are you?', es: '¿Cuántos años tienes?' },
        { speaker: 'student', en: 'I am thirty-five years old.', es: 'Tengo treinta y cinco años.' },
        { speaker: 'tutor', en: 'Thank you for sharing all of that with me.', es: 'Gracias por compartir todo eso conmigo.' },
      ],
    },
    {
      label: 'Part 3: Talking about work and saying goodbye',
      text: 'The person asks what you do for work. Practice describing your job, then practice a polite goodbye as the event ends.',
      script: [
        { speaker: 'tutor', en: 'What do you do, Rosa?', es: '¿A qué te dedicas, Rosa?' },
        { speaker: 'student', en: 'I work as a cook.', es: 'Trabajo como cocinera.' },
        { speaker: 'tutor', en: 'That sounds like hard work. Do you like it?', es: 'Eso suena a trabajo duro. ¿Te gusta?' },
        { speaker: 'student', en: 'Yes, I like it very much.', es: 'Sí, me gusta mucho.' },
        { speaker: 'tutor', en: "It's getting late, and the event is ending.", es: 'Se está haciendo tarde, y el evento está terminando.' },
        { speaker: 'student', en: 'Yes, I should go home now.', es: 'Sí, debo irme a casa ahora.' },
        { speaker: 'tutor', en: 'Goodbye, Rosa! It was nice to meet you.', es: '¡Adiós, Rosa! Fue un placer conocerte.' },
        { speaker: 'student', en: 'Goodbye! See you later.', es: '¡Adiós! Hasta luego.' },
        { speaker: 'tutor', en: 'See you at the next event!', es: '¡Nos vemos en el próximo evento!' },
      ],
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'My name ____ Maria.', promptEs: 'Me llamo Maria. (My name ____ Maria.)', answer: 'is' },
    { id: 'w2', promptEn: 'I ____ from Mexico.', promptEs: 'Soy de México. (I ____ from Mexico.)', answer: 'am' },
    { id: 'w3', promptEn: 'Where ____ you from?', promptEs: '¿De dónde eres? (Where ____ you from?)', answer: 'are' },
    { id: 'w4', promptEn: 'I ____ Spanish and a little English.', promptEs: 'Hablo español y un poco de inglés. (I ____ Spanish...)', answer: 'speak' },
    { id: 'w5', promptEn: 'Nice to ____ you.', promptEs: 'Mucho gusto. (Nice to ____ you.)', answer: 'meet' },
  ],
}

export default module
