import type { Module } from '@/types'

const module: Module = {
  slug: 'likes-and-dislikes',
  track: 'esl',
  titleEn: 'Likes and Dislikes',
  titleEs: 'Gustos y Disgustos',
  descriptionEn: 'Learn how to talk about what you like, love, and don\'t like.',
  descriptionEs: 'Aprende a hablar de lo que te gusta, te encanta y no te gusta.',
  icon: 'Heart',
  vocab: [
    { id: 'i-like', en: 'I like...', es: 'Me gusta...',
      exampleEn: 'I like coffee.', exampleEs: 'Me gusta el café.' },
    { id: 'i-dont-like', en: "I don't like...", es: 'No me gusta...',
      exampleEn: "I don't like spicy food.", exampleEs: 'No me gusta la comida picante.' },
    { id: 'i-love', en: 'I love...', es: 'Me encanta...',
      exampleEn: 'I love dancing.', exampleEs: 'Me encanta bailar.' },
    { id: 'i-hate', en: "I don't like ... at all", es: 'No me gusta nada...',
      exampleEn: "I don't like the cold at all.", exampleEs: 'No me gusta nada el frío.' },
    { id: 'i-prefer', en: 'I prefer...', es: 'Prefiero...',
      exampleEn: 'I prefer tea over coffee.', exampleEs: 'Prefiero el té sobre el café.' },
    { id: 'do-you-like', en: 'Do you like...?', es: '¿Te gusta...?',
      exampleEn: 'Do you like pizza?', exampleEs: '¿Te gusta la pizza?' },
    { id: 'my-favorite', en: 'my favorite...', es: 'mi favorito / mi favorita',
      exampleEn: 'My favorite food is rice and beans.', exampleEs: 'Mi comida favorita es arroz con frijoles.' },
    { id: 'i-really-like', en: 'I really like...', es: 'Me gusta mucho...',
      exampleEn: 'I really like this neighborhood.', exampleEs: 'Me gusta mucho este vecindario.' },
    { id: 'i-like-it-a-lot', en: 'I like it a lot', es: 'Me gusta mucho',
      exampleEn: 'I tried this dish and I like it a lot.', exampleEs: 'Probé este plato y me gusta mucho.' },
    { id: 'i-dont-like-it-at-all', en: "I don't like it at all", es: 'No me gusta para nada',
      exampleEn: "I tried it, but I don't like it at all.", exampleEs: 'Lo probé, pero no me gusta para nada.' },
    { id: 'what-do-you-like', en: 'What do you like?', es: '¿Qué te gusta?',
      exampleEn: 'What do you like to do on weekends?', exampleEs: '¿Qué te gusta hacer los fines de semana?' },
    { id: 'i-like-this-food', en: 'I like this food', es: 'Me gusta esta comida',
      exampleEn: 'I like this food a lot.', exampleEs: 'Me gusta mucho esta comida.' },
    { id: 'she-likes-he-likes', en: 'she likes / he likes', es: 'a ella le gusta / a él le gusta',
      exampleEn: 'He likes soccer. She likes music.', exampleEs: 'A él le gusta el fútbol. A ella le gusta la música.' },
    { id: 'me-too-me-neither', en: 'Me too / Me neither', es: 'A mí también / A mí tampoco',
      exampleEn: '"I like coffee." "Me too!"', exampleEs: '"Me gusta el café." "¡A mí también!"' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Me gusta" in English is:', promptEs: '"Me gusta" en inglés es:',
      answer: 'I like', options: ['I like', "I don't like", 'I love', 'I prefer'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"No me gusta" in English is:', promptEs: '"No me gusta" en inglés es:',
      answer: "I don't like", options: ["I don't like", 'I like', 'I love', 'I prefer'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "She ___ coffee."', promptEs: 'Completa: "She ___ coffee." (le gusta)',
      answer: 'likes', options: ['likes', 'like', 'liking', 'to like'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"¿Te gusta la pizza?" in English is:', promptEs: '"¿Te gusta la pizza?" en inglés es:',
      answer: 'Do you like pizza?', options: ['Do you like pizza?', 'You like pizza?', 'I like pizza', 'Are you pizza?'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"A mí también" in English is:', promptEs: '"A mí también" en inglés es:',
      answer: 'Me too', options: ['Me too', 'Me neither', 'I like it', 'I prefer it'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about food',
      text: 'You are at a restaurant or grocery store talking about food you like and don\'t like. Practice using "I like...", "I love...", and "I prefer...".' },
    { label: 'Part 2: Talking about hobbies',
      text: 'Practice talking about activities you like doing in your free time, and asking the other person what they like to do.' },
    { label: 'Part 3: Agreeing and sharing favorites',
      text: 'Practice agreeing with someone using "Me too" or "Me neither," and talking about your favorite food, music, or activity.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ coffee.', promptEs: 'Me gusta el café. (I ____ coffee.)', answer: 'like' },
    { id: 'w2', promptEn: 'She ____ tea.', promptEs: 'A ella le gusta el té. (She ____ tea.)', answer: 'likes' },
    { id: 'w3', promptEn: "I don't ____ spicy food.", promptEs: 'No me gusta la comida picante. (I don\'t ____ spicy food.)', answer: 'like' },
    { id: 'w4', promptEn: '____ you like pizza?', promptEs: '¿Te gusta la pizza? (____ you like pizza?)', answer: 'Do' },
    { id: 'w5', promptEn: 'I ____ dancing.', promptEs: 'Me encanta bailar. (I ____ dancing.)', answer: 'love' },
  ],
}

export default module
