import type { Module } from '@/types'

const module: Module = {
  slug: 'navigating-subway',
  track: 'esl',
  titleEn: 'Getting Around: Subway & Directions',
  titleEs: 'Moverse por la Ciudad: El Metro y las Direcciones',
  descriptionEn: 'Learn the words and phrases you need to ride the NYC subway and ask for directions on the street.',
  descriptionEs: 'Aprende las palabras y frases para viajar en el metro de Nueva York y pedir direcciones en la calle.',
  icon: 'Train',
  vocab: [
    {
      id: 'subway',
      en: 'subway',
      es: 'el metro / el subterráneo',
      exampleEn: 'I take the subway to work every day.',
      exampleEs: 'Tomo el metro al trabajo todos los días.',
    },
    {
      id: 'metrocard',
      en: 'MetroCard',
      es: 'la tarjeta MetroCard',
      exampleEn: 'I need to buy a MetroCard at the machine.',
      exampleEs: 'Necesito comprar una MetroCard en la máquina.',
    },
    {
      id: 'platform',
      en: 'platform',
      es: 'el andén',
      exampleEn: 'Wait for the train on the platform.',
      exampleEs: 'Espera el tren en el andén.',
    },
    {
      id: 'uptown',
      en: 'uptown',
      es: 'hacia el norte / uptown',
      exampleEn: 'Take the uptown train to get to Manhattan.',
      exampleEs: 'Toma el tren uptown para ir a Manhattan.',
    },
    {
      id: 'downtown',
      en: 'downtown',
      es: 'hacia el sur / downtown',
      exampleEn: 'The downtown train goes toward Brooklyn.',
      exampleEs: 'El tren downtown va hacia Brooklyn.',
    },
    {
      id: 'transfer',
      en: 'transfer',
      es: 'hacer transbordo / cambiar de tren',
      exampleEn: 'Transfer to the A train at Jay Street.',
      exampleEs: 'Haz transbordo al tren A en Jay Street.',
    },
    {
      id: 'exit',
      en: 'exit',
      es: 'la salida',
      exampleEn: 'Use the exit on the left side of the train.',
      exampleEs: 'Usa la salida del lado izquierdo del tren.',
    },
    {
      id: 'which-train',
      en: 'Which train goes to...?',
      es: '¿Qué tren va a...?',
      exampleEn: 'Excuse me, which train goes to Times Square?',
      exampleEs: 'Disculpe, ¿qué tren va a Times Square?',
    },
    {
      id: 'turn-left',
      en: 'turn left',
      es: 'dobla a la izquierda',
      exampleEn: 'Turn left at the light.',
      exampleEs: 'Dobla a la izquierda en el semáforo.',
    },
    {
      id: 'turn-right',
      en: 'turn right',
      es: 'dobla a la derecha',
      exampleEn: 'Turn right on Main Street.',
      exampleEs: 'Dobla a la derecha en la calle Main.',
    },
    {
      id: 'straight-ahead',
      en: 'straight ahead',
      es: 'derecho / todo recto',
      exampleEn: 'Go straight ahead for two blocks.',
      exampleEs: 'Sigue derecho por dos cuadras.',
    },
    {
      id: 'corner',
      en: 'corner',
      es: 'la esquina',
      exampleEn: 'The store is on the corner.',
      exampleEs: 'La tienda está en la esquina.',
    },
    {
      id: 'block',
      en: 'block',
      es: 'la cuadra',
      exampleEn: 'The pharmacy is one block away.',
      exampleEs: 'La farmacia está a una cuadra.',
    },
    {
      id: 'excuse-me-where-is',
      en: 'Excuse me, where is...?',
      es: 'Disculpe, ¿dónde está...?',
      exampleEn: 'Excuse me, where is the nearest subway station?',
      exampleEs: 'Disculpe, ¿dónde está la estación de metro más cercana?',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'What do you need to ride the subway in NYC?',
      promptEs: '¿Qué necesitas para viajar en el metro de Nueva York?',
      answer: 'MetroCard',
      options: ['MetroCard', 'Passport', 'Driver\'s license', 'Ticket'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'Where do you wait for the train?',
      promptEs: '¿Dónde esperas el tren?',
      answer: 'On the platform',
      options: ['On the platform', 'At the exit', 'In the street', 'At the machine'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Uptown" means the train is going toward:',
      promptEs: '"Uptown" significa que el tren va hacia:',
      answer: 'Manhattan / north',
      options: ['Manhattan / north', 'Brooklyn / south', 'Queens / east', 'New Jersey / west'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you ask a stranger where something is?',
      promptEs: '¿Cómo le preguntas a un desconocido dónde está algo?',
      answer: 'Excuse me, where is...?',
      options: ['Excuse me, where is...?', 'Turn left', 'Which train goes to...?', 'How much is the MetroCard?'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"La cuadra" in English is:',
      promptEs: '"La cuadra" en inglés es:',
      answer: 'block',
      options: ['block', 'corner', 'platform', 'exit'],
    },
  ],
  teachingScenarios: [
    {
      label: 'Part 1: Buying a MetroCard',
      text: 'You need to take the subway from Jackson Heights, Queens to Manhattan for a job interview, but you do not know how to buy a MetroCard at the machine or find the right platform.',
    },
    {
      label: 'Part 2: Asking which train to take',
      text: 'You are on the platform but you are not sure if you need the uptown or downtown train, or where to transfer. Practice asking another rider or a subway worker for help.',
    },
    {
      label: 'Part 3: Asking for directions on the street',
      text: 'You exit the subway station but do not recognize the street. Practice asking a stranger for directions to your job interview using turn left/right, straight ahead, corner, and block.',
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'Excuse me, ____ train goes to Manhattan?', promptEs: 'Disculpe, ¿____ tren va a Manhattan?', answer: 'which' },
    { id: 'w2', promptEn: 'Wait for the train on the ____.', promptEs: 'Espera el tren en el ____.', answer: 'platform' },
    { id: 'w3', promptEn: 'Turn ____ at the corner, then go straight.', promptEs: 'Dobla a la ____ en la esquina, luego sigue derecho.', answer: 'left' },
    { id: 'w4', promptEn: 'The pharmacy is one ____ from here.', promptEs: 'La farmacia está a una ____ de aquí.', answer: 'block' },
    { id: 'w5', promptEn: 'Go straight ____, then turn right at the bank.', promptEs: 'Sigue ____, luego dobla a la derecha en el banco.', answer: 'ahead' },
  ],
}

export default module
