import type { Module } from '@/types'

const module: Module = {
  slug: 'negation',
  track: 'esl',
  titleEn: 'Negation',
  titleEs: 'La Negación',
  descriptionEn: 'Learn how to say no, say what you don\'t have, and say you don\'t understand.',
  descriptionEs: 'Aprende a decir que no, decir lo que no tienes, y decir que no entiendes.',
  icon: 'XCircle',
  vocab: [
    { id: 'not', en: 'not', es: 'no',
      exampleEn: 'This is not my bag.', exampleEs: 'Esta no es mi bolsa.' },
    { id: 'i-am-not', en: 'I am not...', es: 'No soy... / No estoy...',
      exampleEn: 'I am not from here.', exampleEs: 'No soy de aquí.' },
    { id: 'i-dont', en: "I don't...", es: 'No... (presente)',
      exampleEn: "I don't speak much English.", exampleEs: 'No hablo mucho inglés.' },
    { id: 'i-didnt', en: "I didn't...", es: 'No... (pasado)',
      exampleEn: "I didn't go to work yesterday.", exampleEs: 'No fui al trabajo ayer.' },
    { id: 'i-dont-have', en: "I don't have...", es: 'No tengo...',
      exampleEn: "I don't have any money.", exampleEs: 'No tengo dinero.' },
    { id: 'i-cant', en: "I can't...", es: 'No puedo...',
      exampleEn: "I can't come tomorrow.", exampleEs: 'No puedo venir mañana.' },
    { id: 'no', en: 'no', es: 'no',
      exampleEn: 'No, thank you.', exampleEs: 'No, gracias.' },
    { id: 'never', en: 'never', es: 'nunca',
      exampleEn: 'I never eat breakfast.', exampleEs: 'Nunca desayuno.' },
    { id: 'nothing', en: 'nothing', es: 'nada',
      exampleEn: 'There is nothing in the fridge.', exampleEs: 'No hay nada en el refrigerador.' },
    { id: 'nobody', en: 'nobody / no one', es: 'nadie',
      exampleEn: 'Nobody is home right now.', exampleEs: 'No hay nadie en casa ahora.' },
    { id: 'not-yet', en: 'not yet', es: 'todavía no',
      exampleEn: 'I have not finished the form yet.', exampleEs: 'Todavía no he terminado el formulario.' },
    { id: 'i-dont-know', en: "I don't know", es: 'No sé',
      exampleEn: "I don't know the answer.", exampleEs: 'No sé la respuesta.' },
    { id: 'i-dont-understand', en: "I don't understand", es: 'No entiendo',
      exampleEn: "I'm sorry, I don't understand.", exampleEs: 'Lo siento, no entiendo.' },
    { id: 'doesnt', en: "doesn't (he/she doesn't...)", es: 'no... (él/ella)',
      exampleEn: "She doesn't speak Spanish.", exampleEs: 'Ella no habla español.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"No sé" in English is:', promptEs: '"No sé" en inglés es:',
      answer: "I don't know", options: ["I don't know", "I don't understand", "I can't", "I am not"] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "I ___ have a car."', promptEs: 'Completa: "I ___ have a car."',
      answer: "don't", options: ["don't", "doesn't", "am not", "didn't"] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "She ___ speak Spanish."', promptEs: 'Completa: "She ___ speak Spanish."',
      answer: "doesn't", options: ["doesn't", "don't", "isn't", "can't"] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Nunca" in English is:', promptEs: '"Nunca" en inglés es:',
      answer: 'never', options: ['never', 'nothing', 'nobody', 'not yet'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"Todavía no" in English is:', promptEs: '"Todavía no" en inglés es:',
      answer: 'not yet', options: ['not yet', 'never', 'nothing', 'no one'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Saying you don\'t understand',
      text: 'Practice a moment where you need to say you don\'t understand or don\'t know something, like at a doctor\'s office or in a class.',
      script: [
        { speaker: 'tutor', en: "Hello, I'm the doctor today. How are you feeling?", es: 'Hola, soy el doctor hoy. ¿Cómo te sientes?' },
        { speaker: 'student', en: "I don't understand the question.", es: 'No entiendo la pregunta.' },
        { speaker: 'tutor', en: "That's okay, let's go slowly. Do you have pain here?", es: 'Está bien, vamos despacio. ¿Tienes dolor aquí?' },
        { speaker: 'student', en: "I don't know.", es: 'No sé.' },
        { speaker: 'tutor', en: 'No problem. I am not going to rush you.', es: 'No hay problema. No voy a apurarte.' },
        { speaker: 'student', en: "I'm sorry, I don't understand.", es: 'Lo siento, no entiendo.' },
        { speaker: 'tutor', en: "Let's try again slowly. Have you taken this medicine before?", es: 'Intentemos otra vez despacio. ¿Has tomado esta medicina antes?' },
        { speaker: 'student', en: "I don't know the answer.", es: 'No sé la respuesta.' },
        { speaker: 'tutor', en: "That's alright — it's normal not to understand everything at first. We'll figure it out together.", es: 'Está bien — es normal no entender todo al principio. Lo resolveremos juntos.' },
      ] },
    { label: 'Part 2: Saying what you don\'t have or can\'t do',
      text: 'Practice explaining that you don\'t have something (like money or a car) or that you can\'t do something (like come tomorrow).',
      script: [
        { speaker: 'tutor', en: "Let's imagine you're talking to your boss about tomorrow. Can you come to work?", es: 'Imaginemos que hablas con tu jefe sobre mañana. ¿Puedes venir al trabajo?' },
        { speaker: 'student', en: "I can't come tomorrow.", es: 'No puedo venir mañana.' },
        { speaker: 'tutor', en: 'I understand. Do you have a car to get here usually?', es: 'Entiendo. ¿Tienes carro para llegar aquí normalmente?' },
        { speaker: 'student', en: "I don't have a car.", es: 'No tengo carro.' },
        { speaker: 'tutor', en: 'That\'s fine. Do you have any money for the bus this week?', es: 'Está bien. ¿Tienes dinero para el autobús esta semana?' },
        { speaker: 'student', en: "I don't have any money.", es: 'No tengo dinero.' },
        { speaker: 'tutor', en: 'Thanks for telling me. Did you go to work yesterday?', es: 'Gracias por decirme. ¿Fuiste al trabajo ayer?' },
        { speaker: 'student', en: "I didn't go to work yesterday.", es: 'No fui al trabajo ayer.' },
        { speaker: 'tutor', en: "No problem — she doesn't come in on Mondays either, so we'll adjust the schedule together.", es: 'No hay problema — ella tampoco viene los lunes, así que ajustaremos el horario juntos.' },
      ] },
    { label: 'Part 3: Politely declining',
      text: 'Someone offers you something. Practice politely saying no, using "No, thank you," "nothing," and "not yet."',
      script: [
        { speaker: 'tutor', en: 'Would you like some coffee?', es: '¿Te gustaría un poco de café?' },
        { speaker: 'student', en: 'No, thank you.', es: 'No, gracias.' },
        { speaker: 'tutor', en: 'Okay. What about something to eat? Nothing at all?', es: 'Está bien. ¿Y algo de comer? ¿Nada en absoluto?' },
        { speaker: 'student', en: 'Nothing, thank you.', es: 'Nada, gracias.' },
        { speaker: 'tutor', en: 'Have you finished the form yet?', es: '¿Ya terminaste el formulario?' },
        { speaker: 'student', en: 'Not yet.', es: 'Todavía no.' },
        { speaker: 'tutor', en: 'No problem, take your time. Is anybody helping you with it?', es: 'No hay problema, tómate tu tiempo. ¿Alguien te está ayudando con eso?' },
        { speaker: 'student', en: 'Nobody is helping me right now.', es: 'No hay nadie ayudándome ahora.' },
        { speaker: 'tutor', en: "I can help you. Let's finish it together, no rush at all.", es: 'Yo puedo ayudarte. Terminémoslo juntos, sin ninguna prisa.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ have a car.', promptEs: 'No tengo carro. (I ____ have a car.)', answer: "don't" },
    { id: 'w2', promptEn: 'She ____ speak English yet.', promptEs: 'Ella todavía no habla inglés. (She ____ speak English yet.)', answer: "doesn't" },
    { id: 'w3', promptEn: 'I ____ go to the doctor yesterday.', promptEs: 'No fui al doctor ayer. (I ____ go to the doctor yesterday.)', answer: "didn't" },
    { id: 'w4', promptEn: 'I have ____ money today.', promptEs: 'No tengo dinero hoy. (I have ____ money today.)', answer: 'no' },
    { id: 'w5', promptEn: 'I ____ come to work tomorrow.', promptEs: 'No puedo venir al trabajo mañana. (I ____ come to work tomorrow.)', answer: "can't" },
  ],
}

export default module
