import type { Module } from '@/types'

const module: Module = {
  slug: 'nouns-and-articles',
  track: 'esl',
  titleEn: 'Nouns and Articles',
  titleEs: 'Sustantivos y Artículos',
  descriptionEn: 'Learn how to name things and use "a," "an," and "the" correctly.',
  descriptionEs: 'Aprende a nombrar cosas y a usar "a," "an" y "the" correctamente.',
  icon: 'Tag',
  vocab: [
    { id: 'a-an', en: 'a / an', es: 'un / una',
      exampleEn: 'I have a book. She has an apple.', exampleEs: 'Tengo un libro. Ella tiene una manzana.' },
    { id: 'the', en: 'the', es: 'el / la / los / las',
      exampleEn: 'The book is on the table.', exampleEs: 'El libro está en la mesa.' },
    { id: 'book-books', en: 'book / books', es: 'el libro / los libros',
      exampleEn: 'I have three books.', exampleEs: 'Tengo tres libros.' },
    { id: 'apple-apples', en: 'an apple / apples', es: 'una manzana / manzanas',
      exampleEn: 'I eat an apple every day.', exampleEs: 'Como una manzana todos los días.' },
    { id: 'house', en: 'house', es: 'la casa',
      exampleEn: 'This is a beautiful house.', exampleEs: 'Esta es una casa hermosa.' },
    { id: 'car', en: 'car', es: 'el carro / el coche',
      exampleEn: 'I need to buy a car.', exampleEs: 'Necesito comprar un carro.' },
    { id: 'woman-women', en: 'woman / women', es: 'la mujer / las mujeres',
      exampleEn: 'That woman is my teacher.', exampleEs: 'Esa mujer es mi maestra.' },
    { id: 'man-men', en: 'man / men', es: 'el hombre / los hombres',
      exampleEn: 'The men are working outside.', exampleEs: 'Los hombres están trabajando afuera.' },
    { id: 'child-children', en: 'child / children', es: 'el niño / los niños',
      exampleEn: 'The children are playing.', exampleEs: 'Los niños están jugando.' },
    { id: 'this-is-a', en: 'This is a...', es: 'Esto es un/una...',
      exampleEn: 'This is a good school.', exampleEs: 'Esta es una buena escuela.' },
    { id: 'these-are', en: 'These are...', es: 'Estos son... / Estas son...',
      exampleEn: 'These are my documents.', exampleEs: 'Estos son mis documentos.' },
    { id: 'some', en: 'some', es: 'algunos / algunas / un poco de',
      exampleEn: 'I need some help.', exampleEs: 'Necesito un poco de ayuda.' },
    { id: 'water', en: 'water', es: 'el agua',
      exampleEn: 'Can I have some water, please?', exampleEs: '¿Me puede dar agua, por favor?' },
    { id: 'money', en: 'money', es: 'el dinero',
      exampleEn: "I don't have much money.", exampleEs: 'No tengo mucho dinero.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'Complete: "I have ___ book."', promptEs: 'Completa: "I have ___ book."',
      answer: 'a', options: ['a', 'an', 'the', 'some'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Which word goes before "apple"?', promptEs: '¿Qué palabra va antes de "apple"?',
      answer: 'an', options: ['an', 'a', 'the', 'some'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'The plural of "child" is:', promptEs: 'El plural de "child" es:',
      answer: 'children', options: ['children', 'childs', 'childrens', 'child'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'The plural of "woman" is:', promptEs: 'El plural de "woman" es:',
      answer: 'women', options: ['women', 'womans', 'womens', 'woman'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"El agua" in English is:', promptEs: '"El agua" en inglés es:',
      answer: 'water', options: ['water', 'money', 'house', 'book'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: At the library',
      text: 'You are at the public library and want to ask for a specific book. Practice using "a," "an," and "the" when talking about books.',
      script: [
        { speaker: 'tutor', en: 'Welcome to the library! Can I help you find a book?', es: '¡Bienvenido a la biblioteca! ¿Puedo ayudarte a encontrar un libro?' },
        { speaker: 'student', en: 'Yes, I am looking for a book about New York.', es: 'Sí, estoy buscando un libro sobre Nueva York.' },
        { speaker: 'tutor', en: 'Great, this is a good book for that.', es: 'Muy bien, este es un buen libro para eso.' },
        { speaker: 'student', en: 'Thank you! Is this the only book about New York?', es: '¡Gracias! ¿Es este el único libro sobre Nueva York?' },
        { speaker: 'tutor', en: 'No, these are three more books about the city.', es: 'No, estos son tres libros más sobre la ciudad.' },
        { speaker: 'student', en: 'Perfect, I will take a book and the map too.', es: 'Perfecto, voy a llevar un libro y también el mapa.' },
        { speaker: 'tutor', en: 'Good choice. Do you need an English dictionary too?', es: 'Buena elección. ¿También necesitas un diccionario de inglés?' },
        { speaker: 'student', en: 'Yes, please. I need some help with new words.', es: 'Sí, por favor. Necesito un poco de ayuda con palabras nuevas.' },
        { speaker: 'tutor', en: 'Here you go. Enjoy the books!', es: 'Aquí tienes. ¡Disfruta los libros!' },
      ] },
    { label: 'Part 2: Talking about people you know',
      text: 'Practice describing the men, women, and children in your building or neighborhood, using the correct plural forms.',
      script: [
        { speaker: 'tutor', en: 'Tell me about the people in your building.', es: 'Cuéntame sobre las personas en tu edificio.' },
        { speaker: 'student', en: 'There are many families. The children play outside every day.', es: 'Hay muchas familias. Los niños juegan afuera todos los días.' },
        { speaker: 'tutor', en: "That's nice. What about the adults?", es: '¡Qué bonito! ¿Y los adultos?' },
        { speaker: 'student', en: 'The women meet in the morning, and the men meet in the evening.', es: 'Las mujeres se reúnen en la mañana, y los hombres se reúnen en la tarde.' },
        { speaker: 'tutor', en: 'Do you know a woman or a man there well?', es: '¿Conoces bien a una mujer o a un hombre allí?' },
        { speaker: 'student', en: 'Yes, I know one woman and one man very well. They are kind.', es: 'Sí, conozco bien a una mujer y a un hombre. Son amables.' },
        { speaker: 'tutor', en: 'And how many children live in your building?', es: '¿Y cuántos niños viven en tu edificio?' },
        { speaker: 'student', en: 'I think there are ten children in total.', es: 'Creo que hay diez niños en total.' },
        { speaker: 'tutor', en: 'It sounds like a friendly neighborhood.', es: 'Suena como un vecindario amigable.' },
      ] },
    { label: 'Part 3: Everyday requests at home',
      text: 'Practice simple requests like asking for some water or explaining you don\'t have much money right now.',
      script: [
        { speaker: 'tutor', en: 'Excuse me, can I have some water, please?', es: '¿Me puede dar agua, por favor?' },
        { speaker: 'student', en: 'Of course, here is some water for you.', es: 'Claro, aquí tienes agua.' },
        { speaker: 'tutor', en: 'Thank you. Now imagine you need to ask me for water. Try it.', es: 'Gracias. Ahora imagina que necesitas pedirme agua. Inténtalo.' },
        { speaker: 'student', en: 'Can I have some water, please?', es: '¿Me puede dar agua, por favor?' },
        { speaker: 'tutor', en: "Very good! Now, what if you don't have much money this week?", es: '¡Muy bien! Ahora, ¿qué pasa si no tienes mucho dinero esta semana?' },
        { speaker: 'student', en: "I don't have much money right now.", es: 'No tengo mucho dinero ahora mismo.' },
        { speaker: 'tutor', en: 'That is a clear way to explain it. Do you need some help?', es: 'Esa es una manera clara de explicarlo. ¿Necesitas un poco de ayuda?' },
        { speaker: 'student', en: 'Yes, I need some help this week.', es: 'Sí, necesito un poco de ayuda esta semana.' },
        { speaker: 'tutor', en: 'Good job practicing these everyday requests.', es: 'Buen trabajo practicando estas peticiones cotidianas.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I have ____ apple.', promptEs: 'Tengo una manzana. (I have ____ apple.)', answer: 'an' },
    { id: 'w2', promptEn: 'I have ____ book.', promptEs: 'Tengo un libro. (I have ____ book.)', answer: 'a' },
    { id: 'w3', promptEn: '____ book is on the table.', promptEs: 'El libro está en la mesa. (____ book is on the table.)', answer: 'The' },
    { id: 'w4', promptEn: 'The ____ are playing outside.', promptEs: 'Los niños están jugando afuera. (The ____ are playing outside.)', answer: 'children' },
    { id: 'w5', promptEn: 'Can I have ____ water?', promptEs: '¿Me puede dar agua? (Can I have ____ water?)', answer: 'some' },
  ],
}

export default module
