import type { Module } from '@/types'

const module: Module = {
  slug: 'nouns-and-articles',
  track: 'esl',
  titleEn: 'Nouns and Articles',
  titleEs: 'Sustantivos y Artículos',
  descriptionEn: 'Learn how to name things and use "a," "an," and "the" correctly.',
  descriptionEs: 'Aprende a nombrar cosas y a usar "a," "an" y "the" correctamente.',
  icon: 'Tag',
  vocab: [
    { id: 'a-an', en: 'a / an', es: 'un / una',
      exampleEn: 'I have a book. She has an apple.', exampleEs: 'Tengo un libro. Ella tiene una manzana.' },
    { id: 'the', en: 'the', es: 'el / la / los / las',
      exampleEn: 'The book is on the table.', exampleEs: 'El libro está en la mesa.' },
    { id: 'book-books', en: 'book / books', es: 'el libro / los libros',
      exampleEn: 'I have three books.', exampleEs: 'Tengo tres libros.' },
    { id: 'apple-apples', en: 'an apple / apples', es: 'una manzana / manzanas',
      exampleEn: 'I eat an apple every day.', exampleEs: 'Como una manzana todos los días.' },
    { id: 'house', en: 'house', es: 'la casa',
      exampleEn: 'This is a beautiful house.', exampleEs: 'Esta es una casa hermosa.' },
    { id: 'car', en: 'car', es: 'el carro / el coche',
      exampleEn: 'I need to buy a car.', exampleEs: 'Necesito comprar un carro.' },
    { id: 'woman-women', en: 'woman / women', es: 'la mujer / las mujeres',
      exampleEn: 'That woman is my teacher.', exampleEs: 'Esa mujer es mi maestra.' },
    { id: 'man-men', en: 'man / men', es: 'el hombre / los hombres',
      exampleEn: 'The men are working outside.', exampleEs: 'Los hombres están trabajando afuera.' },
    { id: 'child-children', en: 'child / children', es: 'el niño / los niños',
      exampleEn: 'The children are playing.', exampleEs: 'Los niños están jugando.' },
    { id: 'this-is-a', en: 'This is a...', es: 'Esto es un/una...',
      exampleEn: 'This is a good school.', exampleEs: 'Esta es una buena escuela.' },
    { id: 'these-are', en: 'These are...', es: 'Estos son... / Estas son...',
      exampleEn: 'These are my documents.', exampleEs: 'Estos son mis documentos.' },
    { id: 'some', en: 'some', es: 'algunos / algunas / un poco de',
      exampleEn: 'I need some help.', exampleEs: 'Necesito un poco de ayuda.' },
    { id: 'water', en: 'water', es: 'el agua',
      exampleEn: 'Can I have some water, please?', exampleEs: '¿Me puede dar agua, por favor?' },
    { id: 'money', en: 'money', es: 'el dinero',
      exampleEn: "I don't have much money.", exampleEs: 'No tengo mucho dinero.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'Complete: "I have ___ book."', promptEs: 'Completa: "I have ___ book."',
      answer: 'a', options: ['a', 'an', 'the', 'some'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Which word goes before "apple"?', promptEs: '¿Qué palabra va antes de "apple"?',
      answer: 'an', options: ['an', 'a', 'the', 'some'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'The plural of "child" is:', promptEs: 'El plural de "child" es:',
      answer: 'children', options: ['children', 'childs', 'childrens', 'child'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'The plural of "woman" is:', promptEs: 'El plural de "woman" es:',
      answer: 'women', options: ['women', 'womans', 'womens', 'woman'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"El agua" in English is:', promptEs: '"El agua" en inglés es:',
      answer: 'water', options: ['water', 'money', 'house', 'book'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: At the library',
      text: 'You are at the public library and want to ask for a specific book. Practice using "a," "an," and "the" when talking about books.' },
    { label: 'Part 2: Talking about people you know',
      text: 'Practice describing the men, women, and children in your building or neighborhood, using the correct plural forms.' },
    { label: 'Part 3: Everyday requests at home',
      text: 'Practice simple requests like asking for some water or explaining you don\'t have much money right now.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I have ____ apple.', promptEs: 'Tengo una manzana. (I have ____ apple.)', answer: 'an' },
    { id: 'w2', promptEn: 'I have ____ book.', promptEs: 'Tengo un libro. (I have ____ book.)', answer: 'a' },
    { id: 'w3', promptEn: '____ book is on the table.', promptEs: 'El libro está en la mesa. (____ book is on the table.)', answer: 'The' },
    { id: 'w4', promptEn: 'The ____ are playing outside.', promptEs: 'Los niños están jugando afuera. (The ____ are playing outside.)', answer: 'children' },
    { id: 'w5', promptEn: 'Can I have ____ water?', promptEs: '¿Me puede dar agua? (Can I have ____ water?)', answer: 'some' },
  ],
}

export default module
