import type { Module } from '@/types'

const module: Module = {
  slug: 'nouns-and-articles',
  track: 'esl',
  titleEn: 'Nouns and Articles',
  titleEs: 'Sustantivos y Artículos',
  descriptionEn: 'Learn how to name things and use "a," "an," and "the" correctly.',
  descriptionEs: 'Aprende a nombrar cosas y a usar "a," "an" y "the" correctamente.',
  icon: 'Tag',
  vocab: [
    { id: 'a-an', en: 'a / an', es: 'un / una',
      exampleEn: 'I have a book. She has an apple.', exampleEs: 'Tengo un libro. Ella tiene una manzana.' },
    { id: 'the', en: 'the', es: 'el / la / los / las',
      exampleEn: 'The book is on the table.', exampleEs: 'El libro está en la mesa.' },
    { id: 'book-books', en: 'book / books', es: 'el libro / los libros',
      exampleEn: 'I have three books.', exampleEs: 'Tengo tres libros.' },
    { id: 'apple-apples', en: 'an apple / apples', es: 'una manzana / manzanas',
      exampleEn: 'I eat an apple every day.', exampleEs: 'Como una manzana todos los días.' },
    { id: 'house', en: 'house', es: 'la casa',
      exampleEn: 'This is a beautiful house.', exampleEs: 'Esta es una casa hermosa.' },
    { id: 'car', en: 'car', es: 'el carro / el coche',
      exampleEn: 'I need to buy a car.', exampleEs: 'Necesito comprar un carro.' },
    { id: 'woman-women', en: 'woman / women', es: 'la mujer / las mujeres',
      exampleEn: 'That woman is my teacher.', exampleEs: 'Esa mujer es mi maestra.' },
    { id: 'man-men', en: 'man / men', es: 'el hombre / los hombres',
      exampleEn: 'The men are working outside.', exampleEs: 'Los hombres están trabajando afuera.' },
    { id: 'child-children', en: 'child / children', es: 'el niño / los niños',
      exampleEn: 'The children are playing.', exampleEs: 'Los niños están jugando.' },
    { id: 'this-is-a', en: 'This is a...', es: 'Esto es un/una...',
      exampleEn: 'This is a good school.', exampleEs: 'Esta es una buena escuela.' },
    { id: 'these-are', en: 'These are...', es: 'Estos son... / Estas son...',
      exampleEn: 'These are my documents.', exampleEs: 'Estos son mis documentos.' },
    { id: 'some', en: 'some', es: 'algunos / algunas / un poco de',
      exampleEn: 'I need some help.', exampleEs: 'Necesito un poco de ayuda.' },
    { id: 'water', en: 'water', es: 'el agua',
      exampleEn: 'Can I have some water, please?', exampleEs: '¿Me puede dar agua, por favor?' },
    { id: 'money', en: 'money', es: 'el dinero',
      exampleEn: "I don't have much money.", exampleEs: 'No tengo mucho dinero.' },
  ],
  grammar: [
    {
      titleEn: '"a" vs "an": listen to the sound, not the letter',
      titleEs: '"a" vs "an": escucha el sonido, no la letra',
      explanationEn: 'Use "an" when the next word starts with a vowel sound (a, e, i, o, u) and "a" when it starts with a consonant sound. This is about sound, not spelling: an apple, a car, an umbrella, a house.',
      explanationEs: 'Usa "an" cuando la siguiente palabra empieza con un sonido de vocal (a, e, i, o, u) y "a" cuando empieza con un sonido de consonante. Esto se trata del sonido, no de la ortografía: an apple, a car, an umbrella, a house.',
      examples: [
        { en: 'I have a book. She has an apple.', es: 'Tengo un libro. Ella tiene una manzana.' },
        { en: 'I need to buy a car.', es: 'Necesito comprar un carro.' },
      ],
    },
    {
      titleEn: 'Irregular plurals: child, woman, man',
      titleEs: 'Plurales irregulares: child, woman, man',
      explanationEn: 'Most nouns just add "-s" for the plural (book → books). But a few common nouns change completely: child becomes children, woman becomes women, and man becomes men. These are worth memorizing since they come up often.',
      explanationEs: 'La mayoría de los sustantivos solo agregan "-s" para el plural (book → books). Pero algunos sustantivos comunes cambian completamente: child se convierte en children, woman se convierte en women, y man se convierte en men. Vale la pena memorizarlos porque aparecen con frecuencia.',
      examples: [
        { en: 'I have three books.', es: 'Tengo tres libros.' },
        { en: 'The children are playing.', es: 'Los niños están jugando.' },
        { en: 'The men are working outside.', es: 'Los hombres están trabajando afuera.' },
      ],
    },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'Complete: "I have ___ book."', promptEs: 'Completa: "I have ___ book."',
      answer: 'a', options: ['a', 'an', 'the', 'some'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Which word goes before "apple"?', promptEs: '¿Qué palabra va antes de "apple"?',
      answer: 'an', options: ['an', 'a', 'the', 'some'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'The plural of "child" is:', promptEs: 'El plural de "child" es:',
      answer: 'children', options: ['children', 'childs', 'childrens', 'child'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'The plural of "woman" is:', promptEs: 'El plural de "woman" es:',
      answer: 'women', options: ['women', 'womans', 'womens', 'woman'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"El agua" in English is:', promptEs: '"El agua" en inglés es:',
      answer: 'water', options: ['water', 'money', 'house', 'book'] },
    { id: 'q6', type: 'multiple-choice', promptEn: 'Which word uses "a," not "an"?', promptEs: '¿Qué palabra usa "a," no "an"?',
      answer: 'car', options: ['car', 'apple', 'umbrella', 'orange'] },
    { id: 'q7', type: 'multiple-choice', promptEn: 'The plural of "man" is:', promptEs: 'El plural de "man" es:',
      answer: 'men', options: ['men', 'mans', 'mens', 'man'] },
    { id: 'q8', type: 'multiple-choice', promptEn: 'Complete: "___ book is on the table." (a specific book you already mentioned)', promptEs: 'Completa: "___ book is on the table." (un libro específico que ya mencionaste)',
      answer: 'The', options: ['The', 'A', 'An', 'Some'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: At the library',
      text: 'You are at the public library and want to ask for a specific book. Practice using "a," "an," and "the" when talking about books.',
      script: [
        { speaker: 'tutor', en: 'Welcome to the library! Can I help you find a book?', es: '¡Bienvenido a la biblioteca! ¿Puedo ayudarte a encontrar un libro?' },
        { speaker: 'student', en: 'Yes, I am looking for a book about New York.', es: 'Sí, estoy buscando un libro sobre Nueva York.' },
        { speaker: 'tutor', en: 'Great, this is a good book for that.', es: 'Muy bien, este es un buen libro para eso.' },
        { speaker: 'student', en: 'Thank you! Is this the only book about New York?', es: '¡Gracias! ¿Es este el único libro sobre Nueva York?' },
        { speaker: 'tutor', en: 'No, these are three more books about the city.', es: 'No, estos son tres libros más sobre la ciudad.' },
        { speaker: 'student', en: 'Perfect, I will take a book and the map too.', es: 'Perfecto, voy a llevar un libro y también el mapa.' },
        { speaker: 'tutor', en: 'Good choice. Do you need an English dictionary too?', es: 'Buena elección. ¿También necesitas un diccionario de inglés?' },
        { speaker: 'student', en: 'Yes, please. I need some help with new words.', es: 'Sí, por favor. Necesito un poco de ayuda con palabras nuevas.' },
        { speaker: 'tutor', en: 'Here you go. Enjoy the books!', es: 'Aquí tienes. ¡Disfruta los libros!' },
      ] },
    { label: 'Part 2: Talking about people you know',
      text: 'Practice describing the men, women, and children in your building or neighborhood, using the correct plural forms.',
      script: [
        { speaker: 'tutor', en: 'Tell me about the people in your building.', es: 'Cuéntame sobre las personas en tu edificio.' },
        { speaker: 'student', en: 'There are many families. The children play outside every day.', es: 'Hay muchas familias. Los niños juegan afuera todos los días.' },
        { speaker: 'tutor', en: "That's nice. What about the adults?", es: '¡Qué bonito! ¿Y los adultos?' },
        { speaker: 'student', en: 'The women meet in the morning, and the men meet in the evening.', es: 'Las mujeres se reúnen en la mañana, y los hombres se reúnen en la tarde.' },
        { speaker: 'tutor', en: 'Do you know a woman or a man there well?', es: '¿Conoces bien a una mujer o a un hombre allí?' },
        { speaker: 'student', en: 'Yes, I know one woman and one man very well. They are kind.', es: 'Sí, conozco bien a una mujer y a un hombre. Son amables.' },
        { speaker: 'tutor', en: 'And how many children live in your building?', es: '¿Y cuántos niños viven en tu edificio?' },
        { speaker: 'student', en: 'I think there are ten children in total.', es: 'Creo que hay diez niños en total.' },
        { speaker: 'tutor', en: 'It sounds like a friendly neighborhood.', es: 'Suena como un vecindario amigable.' },
      ] },
    { label: 'Part 3: Everyday requests at home',
      text: 'Practice simple requests like asking for some water or explaining you don\'t have much money right now.',
      script: [
        { speaker: 'tutor', en: 'Excuse me, can I have some water, please?', es: '¿Me puede dar agua, por favor?' },
        { speaker: 'student', en: 'Of course, here is some water for you.', es: 'Claro, aquí tienes agua.' },
        { speaker: 'tutor', en: 'Thank you. Now imagine you need to ask me for water. Try it.', es: 'Gracias. Ahora imagina que necesitas pedirme agua. Inténtalo.' },
        { speaker: 'student', en: 'Can I have some water, please?', es: '¿Me puede dar agua, por favor?' },
        { speaker: 'tutor', en: "Very good! Now, what if you don't have much money this week?", es: '¡Muy bien! Ahora, ¿qué pasa si no tienes mucho dinero esta semana?' },
        { speaker: 'student', en: "I don't have much money right now.", es: 'No tengo mucho dinero ahora mismo.' },
        { speaker: 'tutor', en: 'That is a clear way to explain it. Do you need some help?', es: 'Esa es una manera clara de explicarlo. ¿Necesitas un poco de ayuda?' },
        { speaker: 'student', en: 'Yes, I need some help this week.', es: 'Sí, necesito un poco de ayuda esta semana.' },
        { speaker: 'tutor', en: 'Good job practicing these everyday requests.', es: 'Buen trabajo practicando estas peticiones cotidianas.' },
      ] },
  ],
  practiceActivities: [
    {
      titleEn: 'A or An?',
      titleEs: '¿A o An?',
      instructionsEn: 'Tutor: say nouns one at a time — apple, book, house, umbrella, orange, car, dog. Student: say "a" or "an" quickly before each one, based on the sound.',
      instructionsEs: 'Tutor: di sustantivos uno a la vez — apple, book, house, umbrella, orange, car, dog. Estudiante: di "a" o "an" rápidamente antes de cada uno, según el sonido.',
    },
    {
      titleEn: 'Describe What\'s Around You',
      titleEs: 'Describe lo que te Rodea',
      instructionsEn: 'Student: name five objects you can see right now, using "a" or "an" the first time you mention each one, then say a second sentence about it using "the" (e.g., "I see a book. The book is red.").',
      instructionsEs: 'Estudiante: nombra cinco objetos que puedes ver ahora mismo, usando "a" o "an" la primera vez que mencionas cada uno, y luego di una segunda oración sobre él usando "the" (por ejemplo, "I see a book. The book is red.").',
    },
    {
      titleEn: 'Plural Challenge',
      titleEs: 'Reto de Plurales',
      instructionsEn: 'Tutor: say the singular form of a noun from today (child, woman, man, book, apple). Student: give the plural form in a full sentence, such as "There are three children."',
      instructionsEs: 'Tutor: di la forma singular de un sustantivo de hoy (child, woman, man, book, apple). Estudiante: da la forma plural en una oración completa, como "There are three children."',
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I have ____ apple.', promptEs: 'Tengo una manzana. (I have ____ apple.)', answer: 'an' },
    { id: 'w2', promptEn: 'I have ____ book.', promptEs: 'Tengo un libro. (I have ____ book.)', answer: 'a' },
    { id: 'w3', promptEn: '____ book is on the table.', promptEs: 'El libro está en la mesa. (____ book is on the table.)', answer: 'The' },
    { id: 'w4', promptEn: 'The ____ are playing outside.', promptEs: 'Los niños están jugando afuera. (The ____ are playing outside.)', answer: 'children' },
    { id: 'w5', promptEn: 'Can I have ____ water?', promptEs: '¿Me puede dar agua? (Can I have ____ water?)', answer: 'some' },
  ],
}

export default module
