import type { Module } from '@/types'

const module: Module = {
  slug: 'possessives-and-reflexives',
  track: 'esl',
  titleEn: 'Possessives and Reflexives',
  titleEs: 'Posesivos y Reflexivos',
  descriptionEn: 'Learn how to say what belongs to you and talk about doing things yourself.',
  descriptionEs: 'Aprende a decir qué te pertenece y a hablar de hacer cosas tú mismo.',
  icon: 'Key',
  vocab: [
    { id: 'my', en: 'my', es: 'mi / mis',
      exampleEn: 'This is my house.', exampleEs: 'Esta es mi casa.' },
    { id: 'your', en: 'your', es: 'tu / tus',
      exampleEn: 'Is this your coat?', exampleEs: '¿Es tu abrigo?' },
    { id: 'his-her', en: 'his / her', es: 'su / sus (de él / de ella)',
      exampleEn: 'This is his car. That is her phone.', exampleEs: 'Este es su carro (de él). Ese es su teléfono (de ella).' },
    { id: 'our', en: 'our', es: 'nuestro / nuestra',
      exampleEn: 'This is our apartment.', exampleEs: 'Este es nuestro apartamento.' },
    { id: 'their', en: 'their', es: 'su / sus (de ellos)',
      exampleEn: 'That is their car.', exampleEs: 'Ese es su carro (de ellos).' },
    { id: 'mine', en: 'mine', es: 'mío / mía',
      exampleEn: 'This bag is mine.', exampleEs: 'Esta bolsa es mía.' },
    { id: 'marias-house', en: "Maria's house", es: 'la casa de María',
      exampleEn: "That is Maria's house.", exampleEs: 'Esa es la casa de María.' },
    { id: 'myself', en: 'myself', es: 'yo mismo / yo misma',
      exampleEn: 'I made this myself.', exampleEs: 'Hice esto yo mismo.' },
    { id: 'yourself', en: 'yourself', es: 'tú mismo / tú misma',
      exampleEn: 'Did you do this yourself?', exampleEs: '¿Hiciste esto tú mismo?' },
    { id: 'himself-herself', en: 'himself / herself', es: 'él mismo / ella misma',
      exampleEn: 'He fixed the car himself.', exampleEs: 'Él arregló el carro él mismo.' },
    { id: 'ourselves', en: 'ourselves', es: 'nosotros mismos',
      exampleEn: 'We cleaned the house ourselves.', exampleEs: 'Limpiamos la casa nosotros mismos.' },
    { id: 'themselves', en: 'themselves', es: 'ellos mismos',
      exampleEn: 'They painted the room themselves.', exampleEs: 'Ellos pintaron el cuarto ellos mismos.' },
    { id: 'by-myself', en: 'by myself', es: 'yo solo / yo sola',
      exampleEn: 'I live by myself.', exampleEs: 'Vivo yo solo.' },
    { id: 'whose-is-this', en: 'Whose is this?', es: '¿De quién es esto?',
      exampleEn: 'Whose is this jacket?', exampleEs: '¿De quién es esta chaqueta?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Mi" (before a noun) in English is:', promptEs: '"Mi" (antes de un sustantivo) en inglés es:',
      answer: 'my', options: ['my', 'mine', 'me', 'I'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "This bag is ___." (it belongs to me)', promptEs: 'Completa: "This bag is ___." (me pertenece)',
      answer: 'mine', options: ['mine', 'my', 'myself', 'I'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Maria\'s house" means:', promptEs: '"Maria\'s house" significa:',
      answer: 'the house that belongs to Maria', options: ['the house that belongs to Maria', 'Maria is a house', 'Maria lives near a house', 'a house named Maria'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Yo mismo" in English is:', promptEs: '"Yo mismo" en inglés es:',
      answer: 'myself', options: ['myself', 'my', 'mine', 'I'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"¿De quién es esto?" in English is:', promptEs: '"¿De quién es esto?" en inglés es:',
      answer: 'Whose is this?', options: ['Whose is this?', 'What is this?', 'Is this mine?', 'This is mine'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about your things and family',
      text: 'Practice talking about your own belongings and family using my, our, his, and her — like "This is my house" or "That is our car."' },
    { label: 'Part 2: Asking whose something is',
      text: 'You find something that isn\'t yours. Practice asking "Whose is this?" and responding with "This is mine" or "That is Maria\'s."' },
    { label: 'Part 3: Talking about doing things alone',
      text: 'Practice talking about things you did yourself or by yourself, like fixing something or living alone.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'This is ____ house.', promptEs: 'Esta es mi casa. (This is ____ house.)', answer: 'my' },
    { id: 'w2', promptEn: 'That book is ____.', promptEs: 'Ese libro es mío. (That book is ____.)', answer: 'mine' },
    { id: 'w3', promptEn: 'I made dinner ____.', promptEs: 'Hice la cena yo mismo. (I made dinner ____.)', answer: 'myself' },
    { id: 'w4', promptEn: '____ is this coat?', promptEs: '¿De quién es este abrigo? (____ is this coat?)', answer: 'Whose' },
    { id: 'w5', promptEn: 'They cleaned the house ____.', promptEs: 'Limpiaron la casa ellos mismos. (They cleaned the house ____.)', answer: 'themselves' },
  ],
}

export default module
