import type { Module } from '@/types'

const module: Module = {
  slug: 'possessives-and-reflexives',
  track: 'esl',
  titleEn: 'Possessives and Reflexives',
  titleEs: 'Posesivos y Reflexivos',
  descriptionEn: 'Learn how to say what belongs to you and talk about doing things yourself.',
  descriptionEs: 'Aprende a decir qué te pertenece y a hablar de hacer cosas tú mismo.',
  icon: 'Key',
  vocab: [
    { id: 'my', en: 'my', es: 'mi / mis',
      exampleEn: 'This is my house.', exampleEs: 'Esta es mi casa.' },
    { id: 'your', en: 'your', es: 'tu / tus',
      exampleEn: 'Is this your coat?', exampleEs: '¿Es tu abrigo?' },
    { id: 'his-her', en: 'his / her', es: 'su / sus (de él / de ella)',
      exampleEn: 'This is his car. That is her phone.', exampleEs: 'Este es su carro (de él). Ese es su teléfono (de ella).' },
    { id: 'our', en: 'our', es: 'nuestro / nuestra',
      exampleEn: 'This is our apartment.', exampleEs: 'Este es nuestro apartamento.' },
    { id: 'their', en: 'their', es: 'su / sus (de ellos)',
      exampleEn: 'That is their car.', exampleEs: 'Ese es su carro (de ellos).' },
    { id: 'mine', en: 'mine', es: 'mío / mía',
      exampleEn: 'This bag is mine.', exampleEs: 'Esta bolsa es mía.' },
    { id: 'marias-house', en: "Maria's house", es: 'la casa de María',
      exampleEn: "That is Maria's house.", exampleEs: 'Esa es la casa de María.' },
    { id: 'myself', en: 'myself', es: 'yo mismo / yo misma',
      exampleEn: 'I made this myself.', exampleEs: 'Hice esto yo mismo.' },
    { id: 'yourself', en: 'yourself', es: 'tú mismo / tú misma',
      exampleEn: 'Did you do this yourself?', exampleEs: '¿Hiciste esto tú mismo?' },
    { id: 'himself-herself', en: 'himself / herself', es: 'él mismo / ella misma',
      exampleEn: 'He fixed the car himself.', exampleEs: 'Él arregló el carro él mismo.' },
    { id: 'ourselves', en: 'ourselves', es: 'nosotros mismos',
      exampleEn: 'We cleaned the house ourselves.', exampleEs: 'Limpiamos la casa nosotros mismos.' },
    { id: 'themselves', en: 'themselves', es: 'ellos mismos',
      exampleEn: 'They painted the room themselves.', exampleEs: 'Ellos pintaron el cuarto ellos mismos.' },
    { id: 'by-myself', en: 'by myself', es: 'yo solo / yo sola',
      exampleEn: 'I live by myself.', exampleEs: 'Vivo yo solo.' },
    { id: 'whose-is-this', en: 'Whose is this?', es: '¿De quién es esto?',
      exampleEn: 'Whose is this jacket?', exampleEs: '¿De quién es esta chaqueta?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Mi" (before a noun) in English is:', promptEs: '"Mi" (antes de un sustantivo) en inglés es:',
      answer: 'my', options: ['my', 'mine', 'me', 'I'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "This bag is ___." (it belongs to me)', promptEs: 'Completa: "This bag is ___." (me pertenece)',
      answer: 'mine', options: ['mine', 'my', 'myself', 'I'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Maria\'s house" means:', promptEs: '"Maria\'s house" significa:',
      answer: 'the house that belongs to Maria', options: ['the house that belongs to Maria', 'Maria is a house', 'Maria lives near a house', 'a house named Maria'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Yo mismo" in English is:', promptEs: '"Yo mismo" en inglés es:',
      answer: 'myself', options: ['myself', 'my', 'mine', 'I'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"¿De quién es esto?" in English is:', promptEs: '"¿De quién es esto?" en inglés es:',
      answer: 'Whose is this?', options: ['Whose is this?', 'What is this?', 'Is this mine?', 'This is mine'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about your things and family',
      text: 'Practice talking about your own belongings and family using my, our, his, and her — like "This is my house" or "That is our car."',
      script: [
        { speaker: 'tutor', en: "Let's talk about our homes and families. Is this your coat?", es: 'Hablemos de nuestros hogares y familias. ¿Es tu abrigo?' },
        { speaker: 'student', en: 'Yes, this is my coat.', es: 'Sí, este es mi abrigo.' },
        { speaker: 'tutor', en: 'Nice! Tell me about your family. Is that your car outside?', es: '¡Qué bien! Cuéntame de tu familia. ¿Ese es tu carro afuera?' },
        { speaker: 'student', en: 'This is my house, and that is our car.', es: 'Esta es mi casa, y ese es nuestro carro.' },
        { speaker: 'tutor', en: 'Who does the blue car belong to, your brother?', es: '¿De quién es el carro azul, de tu hermano?' },
        { speaker: 'student', en: 'This is his car.', es: 'Este es su carro (de él).' },
        { speaker: 'tutor', en: "And the phone on the table, is that your sister's?", es: 'Y el teléfono en la mesa, ¿es de tu hermana?' },
        { speaker: 'student', en: 'That is her phone.', es: 'Ese es su teléfono (de ella).' },
        { speaker: 'tutor', en: 'What about your neighbors — do they have a car too?', es: '¿Y tus vecinos? ¿Ellos también tienen carro?' },
        { speaker: 'student', en: 'That is their car.', es: 'Ese es su carro (de ellos).' },
        { speaker: 'tutor', en: 'Great work using my, our, his, her, and their! You know your family\'s things well.', es: '¡Buen trabajo usando mi, nuestro, su (de él), su (de ella) y su (de ellos)! Conoces bien las cosas de tu familia.' },
      ] },
    { label: 'Part 2: Asking whose something is',
      text: 'You find something that isn\'t yours. Practice asking "Whose is this?" and responding with "This is mine" or "That is Maria\'s."',
      script: [
        { speaker: 'tutor', en: "I found a bag on the table. Let's practice — you don't know whose it is.", es: 'Encontré una bolsa en la mesa. Practiquemos — no sabes de quién es.' },
        { speaker: 'student', en: 'Whose is this?', es: '¿De quién es esto?' },
        { speaker: 'tutor', en: 'Good question! Is this jacket yours?', es: '¡Buena pregunta! ¿Esta chaqueta es tuya?' },
        { speaker: 'student', en: 'This bag is mine.', es: 'Esta bolsa es mía.' },
        { speaker: 'tutor', en: 'And what about this jacket over here, whose is this?', es: '¿Y esta chaqueta de aquí, de quién es esto?' },
        { speaker: 'student', en: 'Whose is this jacket?', es: '¿De quién es esta chaqueta?' },
        { speaker: 'tutor', en: 'I think it belongs to Maria. Have you seen her house nearby?', es: 'Creo que es de María. ¿Has visto su casa cerca?' },
        { speaker: 'student', en: "That is Maria's house.", es: 'Esa es la casa de María.' },
        { speaker: 'tutor', en: "Exactly! So this jacket is probably Maria's, not yours.", es: 'Exacto. Así que esta chaqueta probablemente es de María, no tuya.' },
        { speaker: 'student', en: "Okay, that jacket isn't mine, but this bag is mine.", es: 'Está bien, esa chaqueta no es mía, pero esta bolsa es mía.' },
        { speaker: 'tutor', en: 'Perfect — now you can ask whose something is and answer with confidence.', es: 'Perfecto — ahora puedes preguntar de quién es algo y responder con confianza.' },
      ] },
    { label: 'Part 3: Talking about doing things alone',
      text: 'Practice talking about things you did yourself or by yourself, like fixing something or living alone.',
      script: [
        { speaker: 'tutor', en: "Let's talk about doing things on your own. I fixed my car myself last week.", es: 'Hablemos de hacer cosas por tu cuenta. Arreglé mi carro yo mismo la semana pasada.' },
        { speaker: 'student', en: 'Did you do this yourself?', es: '¿Hiciste esto tú mismo?' },
        { speaker: 'tutor', en: 'Yes, I did! And my brother fixed his bike himself too.', es: '¡Sí, lo hice! Y mi hermano arregló su bicicleta él mismo también.' },
        { speaker: 'student', en: 'He fixed the car himself.', es: 'Él arregló el carro él mismo.' },
        { speaker: 'tutor', en: 'What about you? Did you make dinner yourself last night?', es: '¿Y tú? ¿Hiciste la cena tú mismo anoche?' },
        { speaker: 'student', en: 'I made this myself.', es: 'Hice esto yo mismo.' },
        { speaker: 'tutor', en: 'Great! Do you live with family, or by yourself?', es: '¡Qué bien! ¿Vives con familia, o vives solo?' },
        { speaker: 'student', en: 'I live by myself.', es: 'Vivo yo solo.' },
        { speaker: 'tutor', en: 'And has your family ever cleaned the whole house together?', es: '¿Y tu familia alguna vez ha limpiado toda la casa juntos?' },
        { speaker: 'student', en: 'We cleaned the house ourselves.', es: 'Limpiamos la casa nosotros mismos.' },
        { speaker: 'tutor', en: "Wonderful! You've practiced myself, himself, yourself, and ourselves — well done.", es: 'Maravilloso. Has practicado yo mismo, él mismo, tú mismo y nosotros mismos — bien hecho.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'This is ____ house.', promptEs: 'Esta es mi casa. (This is ____ house.)', answer: 'my' },
    { id: 'w2', promptEn: 'That book is ____.', promptEs: 'Ese libro es mío. (That book is ____.)', answer: 'mine' },
    { id: 'w3', promptEn: 'I made dinner ____.', promptEs: 'Hice la cena yo mismo. (I made dinner ____.)', answer: 'myself' },
    { id: 'w4', promptEn: '____ is this coat?', promptEs: '¿De quién es este abrigo? (____ is this coat?)', answer: 'Whose' },
    { id: 'w5', promptEn: 'They cleaned the house ____.', promptEs: 'Limpiaron la casa ellos mismos. (They cleaned the house ____.)', answer: 'themselves' },
  ],
}

export default module
