import type { Module } from '@/types'

const module: Module = {
  slug: 'pronouns-and-greetings',
  track: 'esl',
  titleEn: 'Pronouns and Greetings',
  titleEs: 'Pronombres y Saludos',
  descriptionEn: 'Learn how to talk about yourself and others, and greet people politely.',
  descriptionEs: 'Aprende a hablar de ti mismo y de otras personas, y a saludar cortésmente.',
  icon: 'Smile',
  vocab: [
    { id: 'i', en: 'I', es: 'yo',
      exampleEn: 'I am a student.', exampleEs: 'Yo soy estudiante.' },
    { id: 'you', en: 'you', es: 'tú / usted',
      exampleEn: 'You are my teacher.', exampleEs: 'Tú eres mi maestro.' },
    { id: 'he-she', en: 'he / she', es: 'él / ella',
      exampleEn: 'He is my son. She is my daughter.', exampleEs: 'Él es mi hijo. Ella es mi hija.' },
    { id: 'we-they', en: 'we / they', es: 'nosotros / ellos',
      exampleEn: 'We are neighbors. They are my friends.', exampleEs: 'Nosotros somos vecinos. Ellos son mis amigos.' },
    { id: 'hello', en: 'Hello / Hi', es: 'Hola',
      exampleEn: 'Hello! How are you?', exampleEs: '¡Hola! ¿Cómo estás?' },
    { id: 'good-morning', en: 'Good morning / Good afternoon', es: 'Buenos días / Buenas tardes',
      exampleEn: 'Good morning! Nice to see you.', exampleEs: '¡Buenos días! Qué gusto verte.' },
    { id: 'how-are-you', en: 'How are you?', es: '¿Cómo estás?',
      exampleEn: 'Hi, how are you today?', exampleEs: 'Hola, ¿cómo estás hoy?' },
    { id: 'i-am-fine', en: 'I am fine, thank you', es: 'Estoy bien, gracias',
      exampleEn: 'I am fine, thank you. And you?', exampleEs: 'Estoy bien, gracias. ¿Y tú?' },
    { id: 'nice-to-meet-you', en: 'Nice to meet you', es: 'Mucho gusto',
      exampleEn: 'Nice to meet you, my name is Maria.', exampleEs: 'Mucho gusto, me llamo María.' },
    { id: 'whats-your-name', en: "What's your name?", es: '¿Cómo te llamas?',
      exampleEn: "Hi, what's your name?", exampleEs: 'Hola, ¿cómo te llamas?' },
    { id: 'my-name-is', en: 'My name is...', es: 'Me llamo...',
      exampleEn: 'My name is Carlos.', exampleEs: 'Me llamo Carlos.' },
    { id: 'this-is-my-friend', en: 'This is my friend...', es: 'Este es mi amigo... / Esta es mi amiga...',
      exampleEn: 'This is my friend Ana.', exampleEs: 'Esta es mi amiga Ana.' },
    { id: 'goodbye', en: 'Goodbye / See you later', es: 'Adiós / Hasta luego',
      exampleEn: 'Goodbye! See you later.', exampleEs: '¡Adiós! Hasta luego.' },
    { id: 'see-you-next-week', en: 'See you next week', es: 'Nos vemos la próxima semana',
      exampleEn: 'Thank you for today. See you next week!', exampleEs: 'Gracias por hoy. ¡Nos vemos la próxima semana!' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Yo" in English is:', promptEs: '"Yo" en inglés es:',
      answer: 'I', options: ['I', 'you', 'he', 'we'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you greet someone you are meeting for the first time?', promptEs: '¿Cómo saludas a alguien que conoces por primera vez?',
      answer: 'Nice to meet you', options: ['Nice to meet you', 'Goodbye', 'How are you?', 'Hello'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Ella" in English is:', promptEs: '"Ella" en inglés es:',
      answer: 'she', options: ['she', 'he', 'they', 'we'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ are my neighbors." ("Ellos son mis vecinos")', promptEs: 'Completa: "___ are my neighbors." ("Ellos son mis vecinos")',
      answer: 'They', options: ['They', 'He', 'You', 'I'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you say goodbye in English?', promptEs: '¿Cómo te despides en inglés?',
      answer: 'Goodbye', options: ['Goodbye', 'Hello', 'How are you?', 'Nice to meet you'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Meeting a new neighbor',
      text: 'You are meeting a new neighbor for the first time outside your apartment building. Introduce yourself, ask how they are doing, and find out their name.' },
    { label: 'Part 2: Introducing a friend',
      text: 'Your neighbor is now with you at a community event. Practice introducing them to a third person using "This is my friend..." and pronouns (he/she/they).' },
    { label: 'Part 3: Saying goodbye',
      text: 'The event is ending. Practice a polite goodbye and saying you will see them again soon.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ am a student.', promptEs: 'Yo soy estudiante. (____ am a student.)', answer: 'I' },
    { id: 'w2', promptEn: 'Hello! ____ are you today?', promptEs: '¡Hola! ¿Cómo estás hoy? (Hello! ____ are you today?)', answer: 'How' },
    { id: 'w3', promptEn: 'This is my friend. ____ is from Mexico.', promptEs: 'Este es mi amigo. Es de México. (This is my friend. ____ is from Mexico.)', answer: 'He' },
    { id: 'w4', promptEn: 'Nice to meet ____.', promptEs: 'Mucho gusto. (Nice to meet ____.)', answer: 'you' },
    { id: 'w5', promptEn: 'Goodbye! See ____ later.', promptEs: '¡Adiós! Nos vemos. (Goodbye! See ____ later.)', answer: 'you' },
  ],
}

export default module
