import type { Module } from '@/types'

const module: Module = {
  slug: 'pronouns-and-greetings',
  track: 'esl',
  titleEn: 'Pronouns and Greetings',
  titleEs: 'Pronombres y Saludos',
  descriptionEn: 'Learn how to talk about yourself and others, and greet people politely.',
  descriptionEs: 'Aprende a hablar de ti mismo y de otras personas, y a saludar cortésmente.',
  icon: 'Smile',
  vocab: [
    { id: 'i', en: 'I', es: 'yo',
      exampleEn: 'I am a student.', exampleEs: 'Yo soy estudiante.' },
    { id: 'you', en: 'you', es: 'tú / usted',
      exampleEn: 'You are my teacher.', exampleEs: 'Tú eres mi maestro.' },
    { id: 'he-she', en: 'he / she', es: 'él / ella',
      exampleEn: 'He is my son. She is my daughter.', exampleEs: 'Él es mi hijo. Ella es mi hija.' },
    { id: 'we-they', en: 'we / they', es: 'nosotros / ellos',
      exampleEn: 'We are neighbors. They are my friends.', exampleEs: 'Nosotros somos vecinos. Ellos son mis amigos.' },
    { id: 'hello', en: 'Hello / Hi', es: 'Hola',
      exampleEn: 'Hello! How are you?', exampleEs: '¡Hola! ¿Cómo estás?' },
    { id: 'good-morning', en: 'Good morning / Good afternoon', es: 'Buenos días / Buenas tardes',
      exampleEn: 'Good morning! Nice to see you.', exampleEs: '¡Buenos días! Qué gusto verte.' },
    { id: 'how-are-you', en: 'How are you?', es: '¿Cómo estás?',
      exampleEn: 'Hi, how are you today?', exampleEs: 'Hola, ¿cómo estás hoy?' },
    { id: 'i-am-fine', en: 'I am fine, thank you', es: 'Estoy bien, gracias',
      exampleEn: 'I am fine, thank you. And you?', exampleEs: 'Estoy bien, gracias. ¿Y tú?' },
    { id: 'nice-to-meet-you', en: 'Nice to meet you', es: 'Mucho gusto',
      exampleEn: 'Nice to meet you, my name is Maria.', exampleEs: 'Mucho gusto, me llamo María.' },
    { id: 'whats-your-name', en: "What's your name?", es: '¿Cómo te llamas?',
      exampleEn: "Hi, what's your name?", exampleEs: 'Hola, ¿cómo te llamas?' },
    { id: 'my-name-is', en: 'My name is...', es: 'Me llamo...',
      exampleEn: 'My name is Carlos.', exampleEs: 'Me llamo Carlos.' },
    { id: 'this-is-my-friend', en: 'This is my friend...', es: 'Este es mi amigo... / Esta es mi amiga...',
      exampleEn: 'This is my friend Ana.', exampleEs: 'Esta es mi amiga Ana.' },
    { id: 'goodbye', en: 'Goodbye / See you later', es: 'Adiós / Hasta luego',
      exampleEn: 'Goodbye! See you later.', exampleEs: '¡Adiós! Hasta luego.' },
    { id: 'see-you-next-week', en: 'See you next week', es: 'Nos vemos la próxima semana',
      exampleEn: 'Thank you for today. See you next week!', exampleEs: 'Gracias por hoy. ¡Nos vemos la próxima semana!' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Yo" in English is:', promptEs: '"Yo" en inglés es:',
      answer: 'I', options: ['I', 'you', 'he', 'we'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you greet someone you are meeting for the first time?', promptEs: '¿Cómo saludas a alguien que conoces por primera vez?',
      answer: 'Nice to meet you', options: ['Nice to meet you', 'Goodbye', 'How are you?', 'Hello'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Ella" in English is:', promptEs: '"Ella" en inglés es:',
      answer: 'she', options: ['she', 'he', 'they', 'we'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Complete: "___ are my neighbors." ("Ellos son mis vecinos")', promptEs: 'Completa: "___ are my neighbors." ("Ellos son mis vecinos")',
      answer: 'They', options: ['They', 'He', 'You', 'I'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you say goodbye in English?', promptEs: '¿Cómo te despides en inglés?',
      answer: 'Goodbye', options: ['Goodbye', 'Hello', 'How are you?', 'Nice to meet you'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Meeting a new neighbor',
      text: 'You are meeting a new neighbor for the first time outside your apartment building. Introduce yourself, ask how they are doing, and find out their name.',
      script: [
        { speaker: 'tutor', en: "Hello! I don't think we've met. I live in this building too.", es: '¡Hola! Creo que no nos conocemos. Yo también vivo en este edificio.' },
        { speaker: 'student', en: 'Hello! Nice to meet you.', es: '¡Hola! Mucho gusto.' },
        { speaker: 'tutor', en: 'How are you today?', es: '¿Cómo estás hoy?' },
        { speaker: 'student', en: 'I am fine, thank you. And you?', es: 'Estoy bien, gracias. ¿Y tú?' },
        { speaker: 'tutor', en: "I am fine, thank you. What's your name?", es: 'Estoy bien, gracias. ¿Cómo te llamas?' },
        { speaker: 'student', en: 'My name is Ana.', es: 'Me llamo Ana.' },
        { speaker: 'tutor', en: 'Nice to meet you, Ana. I am your new neighbor.', es: 'Mucho gusto, Ana. Soy tu nueva vecina.' },
        { speaker: 'student', en: 'Nice to meet you too.', es: 'Mucho gusto también.' },
        { speaker: 'tutor', en: "I'm glad we finally introduced ourselves.", es: 'Me alegra que por fin nos hayamos presentado.' },
      ] },
    { label: 'Part 2: Introducing a friend',
      text: 'Your neighbor is now with you at a community event. Practice introducing them to a third person using "This is my friend..." and pronouns (he/she/they).',
      script: [
        { speaker: 'tutor', en: 'Ana, this is my friend Pedro.', es: 'Ana, este es mi amigo Pedro.' },
        { speaker: 'student', en: 'Nice to meet you, Pedro.', es: 'Mucho gusto, Pedro.' },
        { speaker: 'tutor', en: 'He lives in the next building.', es: 'Él vive en el edificio de al lado.' },
        { speaker: 'student', en: 'Oh, he is my neighbor too!', es: '¡Ah, él también es mi vecino!' },
        { speaker: 'tutor', en: 'Yes! And this is my friend Sara. She works with me.', es: 'Sí. Y esta es mi amiga Sara. Ella trabaja conmigo.' },
        { speaker: 'student', en: 'Nice to meet you, Sara.', es: 'Mucho gusto, Sara.' },
        { speaker: 'tutor', en: 'They are both very kind people.', es: 'Ellos son personas muy amables.' },
        { speaker: 'student', en: "I can tell. I'm happy to meet them.", es: 'Se nota. Me da gusto conocerlos.' },
        { speaker: 'tutor', en: 'Great! Now you know how to introduce your friends too.', es: '¡Genial! Ahora tú también sabes cómo presentar a tus amigos.' },
      ] },
    { label: 'Part 3: Saying goodbye',
      text: 'The event is ending. Practice a polite goodbye and saying you will see them again soon.',
      script: [
        { speaker: 'tutor', en: "It's getting late. I should go home now.", es: 'Se está haciendo tarde. Debo irme a casa.' },
        { speaker: 'student', en: 'Yes, me too.', es: 'Sí, yo también.' },
        { speaker: 'tutor', en: 'Goodbye, Ana! It was nice to meet you.', es: '¡Adiós, Ana! Fue un placer conocerte.' },
        { speaker: 'student', en: 'Goodbye! It was nice to meet you too.', es: '¡Adiós! También fue un placer conocerte.' },
        { speaker: 'tutor', en: 'See you next week at the next event?', es: '¿Nos vemos la próxima semana en el próximo evento?' },
        { speaker: 'student', en: 'Yes, see you next week!', es: '¡Sí, nos vemos la próxima semana!' },
        { speaker: 'tutor', en: 'Perfect. Take care until then.', es: 'Perfecto. Cuídate hasta entonces.' },
        { speaker: 'student', en: 'You too. Goodbye!', es: 'Tú también. ¡Adiós!' },
        { speaker: 'tutor', en: "Goodbye! I'm glad we met today.", es: '¡Adiós! Me alegra que nos hayamos conocido hoy.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: '____ am a student.', promptEs: 'Yo soy estudiante. (____ am a student.)', answer: 'I' },
    { id: 'w2', promptEn: 'Hello! ____ are you today?', promptEs: '¡Hola! ¿Cómo estás hoy? (Hello! ____ are you today?)', answer: 'How' },
    { id: 'w3', promptEn: 'This is my friend. ____ is from Mexico.', promptEs: 'Este es mi amigo. Es de México. (This is my friend. ____ is from Mexico.)', answer: 'He' },
    { id: 'w4', promptEn: 'Nice to meet ____.', promptEs: 'Mucho gusto. (Nice to meet ____.)', answer: 'you' },
    { id: 'w5', promptEn: 'Goodbye! See ____ later.', promptEs: '¡Adiós! Nos vemos. (Goodbye! See ____ later.)', answer: 'you' },
  ],
}

export default module
