import type { Module } from '@/types'

const module: Module = {
  slug: 'shopping-dining-out',
  track: 'esl',
  titleEn: 'Shopping & Dining Out',
  titleEs: 'Compras y Comer Afuera',
  descriptionEn: 'Learn how to order food at a restaurant and shop with confidence.',
  descriptionEs: 'Aprende a ordenar comida en un restaurante y comprar con confianza.',
  icon: 'Utensils',
  vocab: [
    { id: 'menu', en: 'menu', es: 'el menú',
      exampleEn: 'Can I see the menu?', exampleEs: '¿Puedo ver el menú?' },
    { id: 'can-i-see-the-menu', en: 'Can I see the menu?', es: '¿Puedo ver el menú?',
      exampleEn: 'Excuse me, can I see the menu?', exampleEs: 'Disculpe, ¿puedo ver el menú?' },
    { id: 'i-would-like-to-order', en: 'I would like to order...', es: 'Quisiera ordenar...',
      exampleEn: 'I would like to order the chicken.', exampleEs: 'Quisiera ordenar el pollo.' },
    { id: 'waiter-waitress', en: 'waiter / waitress', es: 'el mesero / la mesera',
      exampleEn: 'The waitress brought our food.', exampleEs: 'La mesera trajo nuestra comida.' },
    { id: 'table-for-two', en: 'table for two', es: 'mesa para dos',
      exampleEn: 'We need a table for two, please.', exampleEs: 'Necesitamos una mesa para dos, por favor.' },
    { id: 'do-you-have-a-table', en: 'Do you have a table available?', es: '¿Tiene una mesa disponible?',
      exampleEn: 'Do you have a table available for four?', exampleEs: '¿Tiene una mesa disponible para cuatro?' },
    { id: 'check-bill', en: 'check / bill', es: 'la cuenta',
      exampleEn: 'Can I have the check, please?', exampleEs: '¿Me trae la cuenta, por favor?' },
    { id: 'can-i-have-the-check', en: 'Can I have the check, please?', es: '¿Me trae la cuenta, por favor?',
      exampleEn: "We're ready. Can I have the check, please?", exampleEs: 'Ya terminamos. ¿Me trae la cuenta, por favor?' },
    { id: 'tip', en: 'tip', es: 'la propina',
      exampleEn: 'We left a good tip for the waitress.', exampleEs: 'Dejamos una buena propina para la mesera.' },
    { id: 'to-go', en: 'to go / take-out', es: 'para llevar',
      exampleEn: 'I want my food to go.', exampleEs: 'Quiero mi comida para llevar.' },
    { id: 'is-this-spicy', en: 'Is this spicy?', es: '¿Esto es picante?',
      exampleEn: 'Excuse me, is this dish spicy?', exampleEs: 'Disculpe, ¿este plato es picante?' },
    { id: 'im-allergic-to', en: "I'm allergic to...", es: 'Soy alérgico/a a...',
      exampleEn: "I'm allergic to peanuts.", exampleEs: 'Soy alérgico a los cacahuates.' },
    { id: 'store-hours', en: 'store hours', es: 'el horario de la tienda',
      exampleEn: 'What are the store hours today?', exampleEs: '¿Cuál es el horario de la tienda hoy?' },
    { id: 'what-time-do-you-close', en: 'What time do you close?', es: '¿A qué hora cierran?',
      exampleEn: 'Excuse me, what time do you close?', exampleEs: 'Disculpe, ¿a qué hora cierran?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"El menú" in English is:', promptEs: '"El menú" en inglés es:',
      answer: 'menu', options: ['menu', 'check', 'tip', 'table'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you ask for the check at the end of a meal?', promptEs: '¿Cómo pides la cuenta al final de la comida?',
      answer: 'Can I have the check, please?', options: ['Can I have the check, please?', 'Can I see the menu?', 'I would like to order', 'Is this spicy?'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Para llevar" in English is:', promptEs: '"Para llevar" en inglés es:',
      answer: 'to go', options: ['to go', 'table for two', 'the check', 'the tip'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"La propina" in English is:', promptEs: '"La propina" en inglés es:',
      answer: 'tip', options: ['tip', 'check', 'menu', 'waiter'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you tell someone about a food allergy?', promptEs: '¿Cómo le dices a alguien sobre una alergia a la comida?',
      answer: "I'm allergic to...", options: ["I'm allergic to...", 'Is this spicy?', 'I would like to order', 'What time do you close?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Getting a table at a restaurant',
      text: 'You arrive at a restaurant with your family. Practice asking if there is a table available and asking for a table for a certain number of people.',
      script: [
        { speaker: 'tutor', en: 'Welcome! How many people are in your group?', es: '¡Bienvenidos! ¿Cuántas personas son en su grupo?' },
        { speaker: 'student', en: 'Do you have a table available for four?', es: '¿Tiene una mesa disponible para cuatro?' },
        { speaker: 'tutor', en: 'Let me check... yes, we do.', es: 'Déjeme revisar... sí, tenemos.' },
        { speaker: 'student', en: 'We need a table for two, actually, please.', es: 'En realidad, necesitamos una mesa para dos, por favor.' },
        { speaker: 'tutor', en: 'No problem, right this way.', es: 'No hay problema, por aquí por favor.' },
        { speaker: 'student', en: 'Thank you very much.', es: 'Muchas gracias.' },
        { speaker: 'tutor', en: 'Here is your table. Your waitress will be with you shortly.', es: 'Aquí está su mesa. Su mesera vendrá pronto.' },
        { speaker: 'student', en: 'Great, thank you.', es: 'Perfecto, gracias.' },
        { speaker: 'tutor', en: 'Enjoy your meal when she arrives!', es: '¡Disfruten su comida cuando ella llegue!' },
      ] },
    { label: 'Part 2: Ordering food and asking about ingredients',
      text: 'The waiter brings the menu. Practice ordering food, asking if a dish is spicy, and mentioning a food allergy.',
      script: [
        { speaker: 'tutor', en: 'Hello, here is the menu. Can I get you something to drink first?', es: 'Hola, aquí está el menú. ¿Le traigo algo de tomar primero?' },
        { speaker: 'student', en: 'Can I see the menu again, please? I need a moment.', es: '¿Puedo ver el menú otra vez, por favor? Necesito un momento.' },
        { speaker: 'tutor', en: 'Of course, take your time.', es: 'Claro, tómese su tiempo.' },
        { speaker: 'student', en: 'I would like to order the chicken.', es: 'Quisiera ordenar el pollo.' },
        { speaker: 'tutor', en: 'Good choice. Do you have any allergies?', es: 'Buena elección. ¿Tiene alguna alergia?' },
        { speaker: 'student', en: "Yes, I'm allergic to peanuts.", es: 'Sí, soy alérgico a los cacahuates.' },
        { speaker: 'tutor', en: "Thank you for telling me, I'll let the kitchen know.", es: 'Gracias por decirme, le avisaré a la cocina.' },
        { speaker: 'student', en: 'Also, is this dish spicy?', es: 'También, ¿este plato es picante?' },
        { speaker: 'tutor', en: "No, it's not spicy at all. I'll bring your order soon.", es: 'No, no es nada picante. Le traeré su orden pronto.' },
      ] },
    { label: 'Part 3: Paying and asking about store hours',
      text: 'You are ready to leave. Practice asking for the check, talking about the tip, and later asking a nearby store what time it closes.',
      script: [
        { speaker: 'tutor', en: 'How was everything today?', es: '¿Cómo estuvo todo hoy?' },
        { speaker: 'student', en: 'It was great. Can I have the check, please?', es: 'Estuvo delicioso. ¿Me trae la cuenta, por favor?' },
        { speaker: 'tutor', en: 'Of course, here you go.', es: 'Claro, aquí tiene.' },
        { speaker: 'student', en: 'Should I leave a tip for the waitress?', es: '¿Debería dejar una propina para la mesera?' },
        { speaker: 'tutor', en: 'Yes, a tip is usually appreciated.', es: 'Sí, una propina normalmente se aprecia.' },
        { speaker: 'student', en: 'Great, thank you.', es: 'Perfecto, gracias.' },
        { speaker: 'tutor', en: 'Hi there, can I help you?', es: 'Hola, ¿le puedo ayudar?' },
        { speaker: 'student', en: 'Yes, what time do you close?', es: 'Sí, ¿a qué hora cierran?' },
        { speaker: 'tutor', en: 'We close at nine tonight. Have a good evening!', es: 'Cerramos a las nueve esta noche. ¡Que tenga buena noche!' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'Can I see the ____?', promptEs: '¿Puedo ver el menú? (Can I see the ____?)', answer: 'menu' },
    { id: 'w2', promptEn: 'I would ____ to order the chicken.', promptEs: 'Quisiera ordenar el pollo. (I would ____ to order the chicken.)', answer: 'like' },
    { id: 'w3', promptEn: 'Can I have the ____, please?', promptEs: '¿Me trae la cuenta, por favor? (Can I have the ____, please?)', answer: 'check' },
    { id: 'w4', promptEn: 'I want my food ____.', promptEs: 'Quiero mi comida para llevar. (I want my food ____.)', answer: 'to go' },
    { id: 'w5', promptEn: 'What time do you ____?', promptEs: '¿A qué hora cierran? (What time do you ____?)', answer: 'close' },
  ],
}

export default module
