import type { Module } from '@/types'

const module: Module = {
  slug: 'shopping-dining-out',
  track: 'esl',
  titleEn: 'Shopping & Dining Out',
  titleEs: 'Compras y Comer Afuera',
  descriptionEn: 'Learn how to order food at a restaurant and shop with confidence.',
  descriptionEs: 'Aprende a ordenar comida en un restaurante y comprar con confianza.',
  icon: 'Utensils',
  vocab: [
    { id: 'menu', en: 'menu', es: 'el menú',
      exampleEn: 'Can I see the menu?', exampleEs: '¿Puedo ver el menú?' },
    { id: 'can-i-see-the-menu', en: 'Can I see the menu?', es: '¿Puedo ver el menú?',
      exampleEn: 'Excuse me, can I see the menu?', exampleEs: 'Disculpe, ¿puedo ver el menú?' },
    { id: 'i-would-like-to-order', en: 'I would like to order...', es: 'Quisiera ordenar...',
      exampleEn: 'I would like to order the chicken.', exampleEs: 'Quisiera ordenar el pollo.' },
    { id: 'waiter-waitress', en: 'waiter / waitress', es: 'el mesero / la mesera',
      exampleEn: 'The waitress brought our food.', exampleEs: 'La mesera trajo nuestra comida.' },
    { id: 'table-for-two', en: 'table for two', es: 'mesa para dos',
      exampleEn: 'We need a table for two, please.', exampleEs: 'Necesitamos una mesa para dos, por favor.' },
    { id: 'do-you-have-a-table', en: 'Do you have a table available?', es: '¿Tiene una mesa disponible?',
      exampleEn: 'Do you have a table available for four?', exampleEs: '¿Tiene una mesa disponible para cuatro?' },
    { id: 'check-bill', en: 'check / bill', es: 'la cuenta',
      exampleEn: 'Can I have the check, please?', exampleEs: '¿Me trae la cuenta, por favor?' },
    { id: 'can-i-have-the-check', en: 'Can I have the check, please?', es: '¿Me trae la cuenta, por favor?',
      exampleEn: "We're ready. Can I have the check, please?", exampleEs: 'Ya terminamos. ¿Me trae la cuenta, por favor?' },
    { id: 'tip', en: 'tip', es: 'la propina',
      exampleEn: 'We left a good tip for the waitress.', exampleEs: 'Dejamos una buena propina para la mesera.' },
    { id: 'to-go', en: 'to go / take-out', es: 'para llevar',
      exampleEn: 'I want my food to go.', exampleEs: 'Quiero mi comida para llevar.' },
    { id: 'is-this-spicy', en: 'Is this spicy?', es: '¿Esto es picante?',
      exampleEn: 'Excuse me, is this dish spicy?', exampleEs: 'Disculpe, ¿este plato es picante?' },
    { id: 'im-allergic-to', en: "I'm allergic to...", es: 'Soy alérgico/a a...',
      exampleEn: "I'm allergic to peanuts.", exampleEs: 'Soy alérgico a los cacahuates.' },
    { id: 'store-hours', en: 'store hours', es: 'el horario de la tienda',
      exampleEn: 'What are the store hours today?', exampleEs: '¿Cuál es el horario de la tienda hoy?' },
    { id: 'what-time-do-you-close', en: 'What time do you close?', es: '¿A qué hora cierran?',
      exampleEn: 'Excuse me, what time do you close?', exampleEs: 'Disculpe, ¿a qué hora cierran?' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"El menú" in English is:', promptEs: '"El menú" en inglés es:',
      answer: 'menu', options: ['menu', 'check', 'tip', 'table'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'How do you ask for the check at the end of a meal?', promptEs: '¿Cómo pides la cuenta al final de la comida?',
      answer: 'Can I have the check, please?', options: ['Can I have the check, please?', 'Can I see the menu?', 'I would like to order', 'Is this spicy?'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"Para llevar" in English is:', promptEs: '"Para llevar" en inglés es:',
      answer: 'to go', options: ['to go', 'table for two', 'the check', 'the tip'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"La propina" in English is:', promptEs: '"La propina" en inglés es:',
      answer: 'tip', options: ['tip', 'check', 'menu', 'waiter'] },
    { id: 'q5', type: 'multiple-choice', promptEn: 'How do you tell someone about a food allergy?', promptEs: '¿Cómo le dices a alguien sobre una alergia a la comida?',
      answer: "I'm allergic to...", options: ["I'm allergic to...", 'Is this spicy?', 'I would like to order', 'What time do you close?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Getting a table at a restaurant',
      text: 'You arrive at a restaurant with your family. Practice asking if there is a table available and asking for a table for a certain number of people.' },
    { label: 'Part 2: Ordering food and asking about ingredients',
      text: 'The waiter brings the menu. Practice ordering food, asking if a dish is spicy, and mentioning a food allergy.' },
    { label: 'Part 3: Paying and asking about store hours',
      text: 'You are ready to leave. Practice asking for the check, talking about the tip, and later asking a nearby store what time it closes.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'Can I see the ____?', promptEs: '¿Puedo ver el menú? (Can I see the ____?)', answer: 'menu' },
    { id: 'w2', promptEn: 'I would ____ to order the chicken.', promptEs: 'Quisiera ordenar el pollo. (I would ____ to order the chicken.)', answer: 'like' },
    { id: 'w3', promptEn: 'Can I have the ____, please?', promptEs: '¿Me trae la cuenta, por favor? (Can I have the ____, please?)', answer: 'check' },
    { id: 'w4', promptEn: 'I want my food ____.', promptEs: 'Quiero mi comida para llevar. (I want my food ____.)', answer: 'to go' },
    { id: 'w5', promptEn: 'What time do you ____?', promptEs: '¿A qué hora cierran? (What time do you ____?)', answer: 'close' },
  ],
}

export default module
