import type { Module } from '@/types'

const module: Module = {
  slug: 'tenses',
  track: 'esl',
  titleEn: 'Tenses',
  titleEs: 'Los Tiempos Verbales',
  descriptionEn: 'Learn how to talk about the present, past, and future in English.',
  descriptionEs: 'Aprende a hablar del presente, pasado y futuro en inglés.',
  icon: 'Clock',
  vocab: [
    { id: 'today-now', en: 'today / now', es: 'hoy / ahora',
      exampleEn: 'I am working today.', exampleEs: 'Estoy trabajando hoy.' },
    { id: 'yesterday', en: 'yesterday', es: 'ayer',
      exampleEn: 'I worked yesterday.', exampleEs: 'Trabajé ayer.' },
    { id: 'tomorrow', en: 'tomorrow', es: 'mañana',
      exampleEn: 'I will work tomorrow.', exampleEs: 'Trabajaré mañana.' },
    { id: 'i-work-worked-will-work', en: 'I work / I worked / I will work', es: 'Trabajo / Trabajé / Trabajaré',
      exampleEn: 'I work every day. I worked yesterday. I will work tomorrow.', exampleEs: 'Trabajo todos los días. Trabajé ayer. Trabajaré mañana.' },
    { id: 'i-am-working', en: 'I am ...-ing (right now)', es: 'Estoy + -ando/-iendo (ahora mismo)',
      exampleEn: 'I am working right now.', exampleEs: 'Estoy trabajando ahora mismo.' },
    { id: 'was-were', en: 'was / were', es: 'estaba (yo, él, ella) / estaban (tú, nosotros, ellos)',
      exampleEn: 'I was at home. They were at work.', exampleEs: 'Yo estaba en casa. Ellos estaban en el trabajo.' },
    { id: 'will', en: 'will', es: '(verbo en futuro)',
      exampleEn: 'I will call you tomorrow.', exampleEs: 'Te llamaré mañana.' },
    { id: 'go-went', en: 'go / went', es: 'ir / fui (pasado)',
      exampleEn: 'I go to church every Sunday. Yesterday I went to the store.', exampleEs: 'Voy a la iglesia todos los domingos. Ayer fui a la tienda.' },
    { id: 'every-day', en: 'every day', es: 'todos los días',
      exampleEn: 'I take the bus every day.', exampleEs: 'Tomo el autobús todos los días.' },
    { id: 'last-week', en: 'last week', es: 'la semana pasada',
      exampleEn: 'I saw the doctor last week.', exampleEs: 'Vi al doctor la semana pasada.' },
    { id: 'next-week', en: 'next week', es: 'la próxima semana',
      exampleEn: 'I will start my new job next week.', exampleEs: 'Empezaré mi nuevo trabajo la próxima semana.' },
    { id: 'if-then', en: 'If..., I will...', es: 'Si..., (verbo en futuro)...',
      exampleEn: 'If it rains, I will stay home.', exampleEs: 'Si llueve, me quedaré en casa.' },
    { id: 'was-built-passive', en: 'The house was built in 1990.', es: 'La casa fue construida en 1990.',
      exampleEn: 'The house was built in 1990.', exampleEs: 'La casa fue construida en 1990.' },
    { id: 'always-sometimes-never', en: 'always / sometimes / never', es: 'siempre / a veces / nunca',
      exampleEn: 'I always work on Mondays. I never work on Sundays.', exampleEs: 'Siempre trabajo los lunes. Nunca trabajo los domingos.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Ayer" in English is:', promptEs: '"Ayer" en inglés es:',
      answer: 'yesterday', options: ['yesterday', 'today', 'tomorrow', 'always'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "I ___ to the store yesterday."', promptEs: 'Completa: "I ___ to the store yesterday."',
      answer: 'went', options: ['went', 'go', 'will go', 'going'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "I ___ work tomorrow."', promptEs: 'Completa: "I ___ work tomorrow."',
      answer: 'will', options: ['will', 'was', 'went', 'am'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Which sentence describes something happening right now?', promptEs: '¿Qué oración describe algo que pasa en este momento?',
      answer: 'I am working', options: ['I am working', 'I worked', 'I will work', 'I work every day'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"Si llueve, me quedaré en casa" in English is:', promptEs: '"Si llueve, me quedaré en casa" en inglés es:',
      answer: 'If it rains, I will stay home', options: ['If it rains, I will stay home', 'It rained, I stayed home', 'It is raining now', 'I will rain today'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Your daily routine',
      text: 'Practice talking about things you do every day — waking up, going to work, taking the bus — using the present tense.' },
    { label: 'Part 2: What happened yesterday or last week',
      text: 'Practice talking about something that already happened, like a doctor\'s visit last week or what you did yesterday, using the past tense.' },
    { label: 'Part 3: Future plans and a simple "if"',
      text: 'Practice talking about plans for tomorrow or next week, and one simple "if" plan, like "If I have time next week, I will visit my family."' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ to church every Sunday.', promptEs: 'Voy a la iglesia todos los domingos. (I ____ to church every Sunday.)', answer: 'go' },
    { id: 'w2', promptEn: 'Yesterday I ____ to the store.', promptEs: 'Ayer fui a la tienda. (Yesterday I ____ to the store.)', answer: 'went' },
    { id: 'w3', promptEn: 'Tomorrow I ____ work.', promptEs: 'Mañana trabajaré. (Tomorrow I ____ work.)', answer: 'will' },
    { id: 'w4', promptEn: 'Right now I ____ working.', promptEs: 'Ahora mismo estoy trabajando. (Right now I ____ working.)', answer: 'am' },
    { id: 'w5', promptEn: 'If it rains, I ____ stay home.', promptEs: 'Si llueve, me quedaré en casa. (If it rains, I ____ stay home.)', answer: 'will' },
  ],
}

export default module
