import type { Module } from '@/types'

const module: Module = {
  slug: 'time-dates-seasons',
  track: 'esl',
  titleEn: 'Time, Dates and Seasons',
  titleEs: 'La Hora, las Fechas y las Estaciones',
  descriptionEn: 'Learn how to tell time, talk about the days and months, and describe the seasons.',
  descriptionEs: 'Aprende a decir la hora, hablar de los días y meses, y describir las estaciones.',
  icon: 'Calendar',
  vocab: [
    { id: 'what-time-is-it', en: 'What time is it?', es: '¿Qué hora es?',
      exampleEn: 'Excuse me, what time is it?', exampleEs: 'Disculpe, ¿qué hora es?' },
    { id: 'oclock', en: "o'clock", es: 'en punto',
      exampleEn: "It's three o'clock.", exampleEs: 'Son las tres en punto.' },
    { id: 'half-past', en: 'half past', es: 'y media',
      exampleEn: "It's half past three.", exampleEs: 'Son las tres y media.' },
    { id: 'morning-afternoon-evening', en: 'in the morning / afternoon / evening', es: 'por la mañana / por la tarde / por la noche',
      exampleEn: 'I work in the morning.', exampleEs: 'Trabajo por la mañana.' },
    { id: 'what-day-is-it', en: 'What day is it?', es: '¿Qué día es?',
      exampleEn: "What day is it today? It's Monday.", exampleEs: '¿Qué día es hoy? Es lunes.' },
    { id: 'monday-through-friday', en: 'Monday through Friday', es: 'de lunes a viernes',
      exampleEn: 'I work Monday through Friday.', exampleEs: 'Trabajo de lunes a viernes.' },
    { id: 'weekend', en: 'weekend', es: 'el fin de semana',
      exampleEn: 'I rest on the weekend.', exampleEs: 'Descanso en el fin de semana.' },
    { id: 'month', en: 'month', es: 'el mes',
      exampleEn: 'I pay rent every month.', exampleEs: 'Pago la renta cada mes.' },
    { id: 'what-is-the-date-today', en: 'What is the date today?', es: '¿Cuál es la fecha de hoy?',
      exampleEn: 'What is the date today? It is May 3rd.', exampleEs: '¿Cuál es la fecha de hoy? Es el 3 de mayo.' },
    { id: 'january', en: 'January', es: 'enero',
      exampleEn: 'My son was born in January.', exampleEs: 'Mi hijo nació en enero.' },
    { id: 'birthday', en: 'birthday', es: 'el cumpleaños',
      exampleEn: 'My birthday is in June.', exampleEs: 'Mi cumpleaños es en junio.' },
    { id: 'spring-summer', en: 'spring / summer', es: 'la primavera / el verano',
      exampleEn: 'It gets warm in the spring and hot in the summer.', exampleEs: 'Hace calor templado en primavera y mucho calor en verano.' },
    { id: 'fall-winter', en: 'fall / winter', es: 'el otoño / el invierno',
      exampleEn: 'It gets cold in the fall and very cold in the winter.', exampleEs: 'Hace frío en otoño y mucho frío en invierno.' },
    { id: 'its-cold-hot', en: "It's cold / hot outside", es: 'Hace frío / calor afuera',
      exampleEn: "It's very cold outside today.", exampleEs: 'Hace mucho frío afuera hoy.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"¿Qué hora es?" in English is:', promptEs: '"¿Qué hora es?" en inglés es:',
      answer: 'What time is it?', options: ['What time is it?', 'What day is it?', 'What is the date today?', 'It\'s cold outside'] },
    { id: 'q2', type: 'multiple-choice', promptEn: '"El fin de semana" in English is:', promptEs: '"El fin de semana" en inglés es:',
      answer: 'weekend', options: ['weekend', 'month', 'morning', 'birthday'] },
    { id: 'q3', type: 'multiple-choice', promptEn: '"El cumpleaños" in English is:', promptEs: '"El cumpleaños" en inglés es:',
      answer: 'birthday', options: ['birthday', 'weekend', 'month', 'date'] },
    { id: 'q4', type: 'multiple-choice', promptEn: 'Which season is the coldest?', promptEs: '¿Cuál estación es la más fría?',
      answer: 'winter', options: ['winter', 'summer', 'spring', 'fall'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"¿Cuál es la fecha de hoy?" in English is:', promptEs: '"¿Cuál es la fecha de hoy?" en inglés es:',
      answer: 'What is the date today?', options: ['What is the date today?', 'What time is it?', 'What day is it?', 'What month is it?'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Telling time',
      text: 'Practice telling the time and talking about your daily schedule — when you wake up, work, and eat — using o\'clock and half past.',
      script: [
        { speaker: 'tutor', en: 'What time is it right now?', es: '¿Qué hora es ahora mismo?' },
        { speaker: 'student', en: "It's three o'clock.", es: 'Son las tres en punto.' },
        { speaker: 'tutor', en: 'Good. What time do you wake up in the morning?', es: '¿A qué hora te despiertas por la mañana?' },
        { speaker: 'student', en: 'I wake up at half past six in the morning.', es: 'Me despierto a las seis y media de la mañana.' },
        { speaker: 'tutor', en: 'And when do you work?', es: '¿Y cuándo trabajas?' },
        { speaker: 'student', en: 'I work in the morning and in the afternoon.', es: 'Trabajo por la mañana y por la tarde.' },
        { speaker: 'tutor', en: 'What time do you eat dinner in the evening?', es: '¿A qué hora cenas por la noche?' },
        { speaker: 'student', en: 'I eat dinner at half past seven in the evening.', es: 'Ceno a las siete y media de la noche.' },
        { speaker: 'tutor', en: 'Great job telling time and describing your schedule!', es: '¡Buen trabajo diciendo la hora y describiendo tu horario!' },
      ] },
    { label: 'Part 2: Talking about the week',
      text: 'Practice talking about which days you work (Monday through Friday) and what you like to do on the weekend.',
      script: [
        { speaker: 'tutor', en: 'What day is it today?', es: '¿Qué día es hoy?' },
        { speaker: 'student', en: 'Today is Monday.', es: 'Hoy es lunes.' },
        { speaker: 'tutor', en: 'Which days do you work?', es: '¿Qué días trabajas?' },
        { speaker: 'student', en: 'I work Monday through Friday.', es: 'Trabajo de lunes a viernes.' },
        { speaker: 'tutor', en: 'What do you do on the weekend?', es: '¿Qué haces en el fin de semana?' },
        { speaker: 'student', en: 'On the weekend, I rest and see my family.', es: 'En el fin de semana, descanso y veo a mi familia.' },
        { speaker: 'tutor', en: 'That sounds nice. Do you work every month?', es: 'Eso suena bien. ¿Trabajas cada mes?' },
        { speaker: 'student', en: 'Yes, I work every month, Monday through Friday.', es: 'Sí, trabajo cada mes, de lunes a viernes.' },
        { speaker: 'tutor', en: 'Perfect. Now you can talk about your whole week!', es: '¡Perfecto. Ahora puedes hablar de toda tu semana!' },
      ] },
    { label: 'Part 3: Seasons and important dates',
      text: 'Practice talking about the seasons, the weather in each one, and sharing your birthday month and date.',
      script: [
        { speaker: 'tutor', en: 'What is the date today?', es: '¿Cuál es la fecha de hoy?' },
        { speaker: 'student', en: 'Today is May 3rd.', es: 'Hoy es el 3 de mayo.' },
        { speaker: 'tutor', en: 'Nice. When is your birthday?', es: 'Qué bien. ¿Cuándo es tu cumpleaños?' },
        { speaker: 'student', en: 'My birthday is in January.', es: 'Mi cumpleaños es en enero.' },
        { speaker: 'tutor', en: 'January is winter. Is it cold outside then?', es: 'Enero es invierno. ¿Hace frío afuera entonces?' },
        { speaker: 'student', en: "Yes, it's very cold outside in January.", es: 'Sí, hace mucho frío afuera en enero.' },
        { speaker: 'tutor', en: "What about summer? What's the weather like?", es: '¿Y en el verano? ¿Cómo es el clima?' },
        { speaker: 'student', en: "In spring it's warm and in summer it's hot.", es: 'En primavera hace calor templado y en verano hace mucho calor.' },
        { speaker: 'tutor', en: 'Excellent! You know the seasons and can share your birthday date.', es: '¡Excelente! Conoces las estaciones y puedes compartir la fecha de tu cumpleaños.' },
      ] },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'What ____ is it?', promptEs: '¿Qué hora es? (What ____ is it?)', answer: 'time' },
    { id: 'w2', promptEn: 'It is three ____.', promptEs: 'Son las tres en punto. (It is three ____.)', answer: "o'clock" },
    { id: 'w3', promptEn: 'The ____ is Saturday and Sunday.', promptEs: 'El fin de semana es sábado y domingo. (The ____ is Saturday and Sunday.)', answer: 'weekend' },
    { id: 'w4', promptEn: 'It is very cold in ____.', promptEs: 'Hace mucho frío en invierno. (It is very cold in ____.)', answer: 'winter' },
    { id: 'w5', promptEn: 'What is the ____ today?', promptEs: '¿Cuál es la fecha de hoy? (What is the ____ today?)', answer: 'date' },
  ],
}

export default module
