import type { Module } from '@/types'

const module: Module = {
  slug: 'verb-to-have',
  track: 'esl',
  titleEn: 'The Verb "To Have"',
  titleEs: 'El Verbo "To Have"',
  descriptionEn: 'Learn how to talk about what you have — family, appointments, and everyday needs.',
  descriptionEs: 'Aprende a hablar de lo que tienes — familia, citas y necesidades diarias.',
  icon: 'Package',
  vocab: [
    { id: 'i-have', en: 'I have', es: 'tengo',
      exampleEn: 'I have a car.', exampleEs: 'Tengo un carro.' },
    { id: 'you-have', en: 'you have', es: 'tú tienes',
      exampleEn: 'You have a good job.', exampleEs: 'Tú tienes un buen trabajo.' },
    { id: 'he-she-has', en: 'he / she has', es: 'él / ella tiene',
      exampleEn: 'She has three children.', exampleEs: 'Ella tiene tres hijos.' },
    { id: 'we-have', en: 'we have', es: 'nosotros tenemos',
      exampleEn: 'We have a small apartment.', exampleEs: 'Tenemos un apartamento pequeño.' },
    { id: 'they-have', en: 'they have', es: 'ellos tienen',
      exampleEn: 'They have two cars.', exampleEs: 'Ellos tienen dos carros.' },
    { id: 'i-dont-have', en: "I don't have", es: 'no tengo',
      exampleEn: "I don't have a car.", exampleEs: 'No tengo carro.' },
    { id: 'do-you-have', en: 'Do you have...?', es: '¿Tienes...?',
      exampleEn: 'Do you have a pen?', exampleEs: '¿Tienes un lapicero?' },
    { id: 'does-he-she-have', en: 'Does he/she have...?', es: '¿Tiene él/ella...?',
      exampleEn: 'Does she have insurance?', exampleEs: '¿Tiene ella seguro médico?' },
    { id: 'i-have-two-children', en: 'I have two children', es: 'Tengo dos hijos',
      exampleEn: 'I have two children in school.', exampleEs: 'Tengo dos hijos en la escuela.' },
    { id: 'i-have-an-appointment', en: 'I have an appointment', es: 'Tengo una cita',
      exampleEn: 'I have an appointment at 3 o\'clock.', exampleEs: 'Tengo una cita a las 3.' },
    { id: 'i-have-a-headache', en: 'I have a headache', es: 'Tengo dolor de cabeza',
      exampleEn: 'I have a headache today.', exampleEs: 'Tengo dolor de cabeza hoy.' },
    { id: 'i-have-a-job', en: 'I have a job', es: 'Tengo un trabajo',
      exampleEn: 'I have a job in a restaurant.', exampleEs: 'Tengo un trabajo en un restaurante.' },
    { id: 'i-have-a-question', en: 'I have a question', es: 'Tengo una pregunta',
      exampleEn: 'Excuse me, I have a question.', exampleEs: 'Disculpe, tengo una pregunta.' },
    { id: 'i-dont-have-any-money', en: "I don't have any money", es: 'No tengo dinero',
      exampleEn: "I don't have any money with me today.", exampleEs: 'No tengo dinero conmigo hoy.' },
  ],
  grammar: [
    {
      titleEn: '"have" vs "has"',
      titleEs: '"have" vs "has"',
      explanationEn: 'Use "have" with I, you, we, and they. Use "has" with he, she, or it, and with one other person\'s name (Maria has, my neighbor has).',
      explanationEs: 'Usa "have" con I, you, we y they. Usa "has" con he, she, o it, y con el nombre de otra persona (Maria has, my neighbor has).',
      examples: [
        { en: 'I have a car.', es: 'Tengo un carro.' },
        { en: 'She has three children.', es: 'Ella tiene tres hijos.' },
        { en: 'We have a small apartment.', es: 'Tenemos un apartamento pequeño.' },
        { en: 'They have two cars.', es: 'Ellos tienen dos carros.' },
      ],
    },
    {
      titleEn: 'Questions and negatives: do/does + have',
      titleEs: 'Preguntas y negaciones: do/does + have',
      explanationEn: 'To ask a question, use "Do" (with I/you/we/they) or "Does" (with he/she/it) before the subject, and "have" stays in its base form. For a negative, add "don\'t" or "doesn\'t" before "have."',
      explanationEs: 'Para hacer una pregunta, usa "Do" (con I/you/we/they) o "Does" (con he/she/it) antes del sujeto, y "have" se mantiene en su forma base. Para una negación, agrega "don\'t" o "doesn\'t" antes de "have."',
      examples: [
        { en: 'Do you have a pen?', es: '¿Tienes un lapicero?' },
        { en: 'Does she have insurance?', es: '¿Tiene ella seguro médico?' },
        { en: "I don't have a car.", es: 'No tengo carro.' },
      ],
    },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Tengo" in English is:', promptEs: '"Tengo" en inglés es:',
      answer: 'I have', options: ['I have', 'I am', 'I need', 'I want'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "She ___ two children."', promptEs: 'Completa: "She ___ two children."',
      answer: 'has', options: ['has', 'have', 'is', 'are'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'How do you ask "¿Tienes un lapicero?"', promptEs: '¿Cómo preguntas "¿Tienes un lapicero?"',
      answer: 'Do you have a pen?', options: ['Do you have a pen?', 'Are you a pen?', 'Have you pen?', 'Is you have a pen?'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Tengo una cita" in English is:', promptEs: '"Tengo una cita" en inglés es:',
      answer: 'I have an appointment', options: ['I have an appointment', 'I have a headache', 'I have a job', 'I have a question'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"No tengo dinero" in English is:', promptEs: '"No tengo dinero" en inglés es:',
      answer: "I don't have any money", options: ["I don't have any money", "I don't have a job", "I have a lot of money", "I need money"] },
    { id: 'q6', type: 'multiple-choice', promptEn: 'Complete: "They ___ two cars."', promptEs: 'Completa: "They ___ two cars."',
      answer: 'have', options: ['have', 'has', 'is', 'are'] },
    { id: 'q7', type: 'multiple-choice', promptEn: 'Complete: "___ he have a car?"', promptEs: 'Completa: "___ he have a car?"',
      answer: 'Does', options: ['Does', 'Do', 'Is', 'Has'] },
    { id: 'q8', type: 'multiple-choice', promptEn: '"Tengo una pregunta" in English is:', promptEs: '"Tengo una pregunta" en inglés es:',
      answer: 'I have a question', options: ['I have a question', 'I have an appointment', 'I have a headache', 'I have a job'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about your family and belongings',
      text: 'Practice talking about what you have — how many children, whether you have a car, and where you live.',
      script: [
        { speaker: 'tutor', en: 'Tell me about your family. Do you have children?', es: 'Cuéntame de tu familia. ¿Tienes hijos?' },
        { speaker: 'student', en: 'Yes, I have two children.', es: 'Sí, tengo dos hijos.' },
        { speaker: 'tutor', en: 'Nice! Do you have a car?', es: '¡Qué bien! ¿Tienes un carro?' },
        { speaker: 'student', en: "No, I don't have a car right now.", es: 'No, no tengo carro ahora mismo.' },
        { speaker: 'tutor', en: 'That is okay. Does your husband have a car?', es: 'Está bien. ¿Tu esposo tiene un carro?' },
        { speaker: 'student', en: 'Yes, he has a car for work.', es: 'Sí, él tiene un carro para el trabajo.' },
        { speaker: 'tutor', en: 'Good. And where do you live — do you have a small apartment?', es: 'Bien. ¿Y dónde vives? ¿Tienes un apartamento pequeño?' },
        { speaker: 'student', en: 'We have a small apartment near the school.', es: 'Tenemos un apartamento pequeño cerca de la escuela.' },
        { speaker: 'tutor', en: 'Wonderful. Do your neighbors have children too?', es: 'Maravilloso. ¿Tus vecinos también tienen hijos?' },
        { speaker: 'student', en: 'Yes, they have two cars and three children.', es: 'Sí, ellos tienen dos carros y tres hijos.' },
        { speaker: 'tutor', en: 'Great practice talking about your family and belongings!', es: '¡Buena práctica hablando de tu familia y tus pertenencias!' },
      ] },
    { label: 'Part 2: At the doctor\'s office',
      text: 'Practice telling a receptionist you have an appointment and describing that you have a headache or another common symptom.',
      script: [
        { speaker: 'tutor', en: 'Good morning! Welcome to the clinic. How can I help you?', es: '¡Buenos días! Bienvenido a la clínica. ¿Cómo puedo ayudarle?' },
        { speaker: 'student', en: 'Good morning. I have an appointment at 3 o\'clock.', es: 'Buenos días. Tengo una cita a las 3.' },
        { speaker: 'tutor', en: 'What is your name, please?', es: '¿Cuál es su nombre, por favor?' },
        { speaker: 'student', en: 'My name is Maria Lopez.', es: 'Mi nombre es María López.' },
        { speaker: 'tutor', en: 'Thank you. What is the problem today? Do you have a headache?', es: '¿Cuál es el problema hoy? ¿Tiene dolor de cabeza?' },
        { speaker: 'student', en: 'Yes, I have a headache since this morning.', es: 'Sí, tengo dolor de cabeza desde esta mañana.' },
        { speaker: 'tutor', en: 'I understand. Does your daughter have an appointment today too?', es: 'Entiendo. ¿Su hija también tiene una cita hoy?' },
        { speaker: 'student', en: "No, she doesn't have an appointment. Just me.", es: 'No, ella no tiene cita. Solo yo.' },
        { speaker: 'tutor', en: 'Okay. Do you have your insurance card with you?', es: '¿Tiene su tarjeta de seguro con usted?' },
        { speaker: 'student', en: 'Yes, I have it here.', es: 'Sí, la tengo aquí.' },
        { speaker: 'tutor', en: 'Perfect. Please have a seat — the doctor will see you soon.', es: 'Perfecto. Por favor, tome asiento; el doctor la atenderá pronto.' },
      ] },
    { label: 'Part 3: At work or in a store',
      text: 'Practice saying you have a question, telling someone you have a job, or explaining you don\'t have money with you right now.',
      script: [
        { speaker: 'tutor', en: 'Excuse me, can I help you find something?', es: 'Disculpe, ¿le puedo ayudar a encontrar algo?' },
        { speaker: 'student', en: 'Yes, I have a question.', es: 'Sí, tengo una pregunta.' },
        { speaker: 'tutor', en: 'Sure, go ahead.', es: 'Claro, adelante.' },
        { speaker: 'student', en: 'Do you have milk on sale this week?', es: '¿Tienen leche en oferta esta semana?' },
        { speaker: 'tutor', en: "Yes, we have milk on sale. It's near the front.", es: 'Sí, tenemos leche en oferta. Está cerca de la entrada.' },
        { speaker: 'student', en: "Thank you. Oh no, I don't have any money with me today.", es: 'Gracias. Ay no, no tengo dinero conmigo hoy.' },
        { speaker: 'tutor', en: 'That is alright, you can come back tomorrow. Do you have a job nearby?', es: 'Está bien, puede regresar mañana. ¿Tiene un trabajo cerca?' },
        { speaker: 'student', en: 'Yes, I have a job in a restaurant close to here.', es: 'Sí, tengo un trabajo en un restaurante cerca de aquí.' },
        { speaker: 'tutor', en: 'That is great! Maybe you can shop after work tomorrow.', es: '¡Qué bien! Tal vez pueda comprar después del trabajo mañana.' },
        { speaker: 'student', en: "Yes, I'll come back tomorrow with money. Thank you!", es: 'Sí, regresaré mañana con dinero. ¡Gracias!' },
        { speaker: 'tutor', en: 'Perfect! You practiced asking questions and talking about money and work.', es: 'Perfecto! Practicaste hacer preguntas y hablar sobre el dinero y el trabajo.' },
      ] },
  ],
  practiceActivities: [
    {
      titleEn: 'Family Inventory',
      titleEs: 'Inventario Familiar',
      instructionsEn: 'Student: describe what three family members have — a car, a job, an apartment, children — using "has" for each person. Tutor: check that "has" (not "have") is used correctly every time.',
      instructionsEs: 'Estudiante: describe lo que tienen tres familiares — un carro, un trabajo, un apartamento, hijos — usando "has" para cada persona. Tutor: revisa que se use "has" (no "have") correctamente cada vez.',
    },
    {
      titleEn: '20 Questions: Do You Have...?',
      titleEs: '20 Preguntas: Do You Have...?',
      instructionsEn: 'Take turns asking "Do you have...?" or "Does he/she have...?" about real everyday items (a phone, a car, children, a job). Answer honestly with "I have..." or "I don\'t have..."',
      instructionsEs: 'Túrnense para preguntar "Do you have...?" o "Does he/she have...?" sobre objetos cotidianos reales (un teléfono, un carro, hijos, un trabajo). Respondan con honestidad usando "I have..." o "I don\'t have..."',
    },
    {
      titleEn: 'At the Front Desk',
      titleEs: 'En la Recepción',
      instructionsEn: 'Tutor: play a receptionist at a new office (not a doctor\'s office this time — try a school or a bank). Student: explain you have an appointment, but you don\'t have a document they ask for, and answer their follow-up questions.',
      instructionsEs: 'Tutor: haz de recepcionista en una oficina nueva (no un consultorio médico esta vez — prueba una escuela o un banco). Estudiante: explica que tienes una cita, pero que no tienes un documento que te piden, y responde sus preguntas de seguimiento.',
    },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ two children.', promptEs: 'Tengo dos hijos. (I ____ two children.)', answer: 'have' },
    { id: 'w2', promptEn: 'She ____ a headache.', promptEs: 'Ella tiene dolor de cabeza. (She ____ a headache.)', answer: 'has' },
    { id: 'w3', promptEn: '____ you have a pen?', promptEs: '¿Tienes un lapicero? (____ you have a pen?)', answer: 'Do' },
    { id: 'w4', promptEn: 'I ____ an appointment today.', promptEs: 'Tengo una cita hoy. (I ____ an appointment today.)', answer: 'have' },
    { id: 'w5', promptEn: "I don't ____ any money.", promptEs: 'No tengo dinero. (I don\'t ____ any money.)', answer: 'have' },
  ],
}

export default module
