import type { Module } from '@/types'

const module: Module = {
  slug: 'verb-to-have',
  track: 'esl',
  titleEn: 'The Verb "To Have"',
  titleEs: 'El Verbo "To Have"',
  descriptionEn: 'Learn how to talk about what you have — family, appointments, and everyday needs.',
  descriptionEs: 'Aprende a hablar de lo que tienes — familia, citas y necesidades diarias.',
  icon: 'Package',
  vocab: [
    { id: 'i-have', en: 'I have', es: 'tengo',
      exampleEn: 'I have a car.', exampleEs: 'Tengo un carro.' },
    { id: 'you-have', en: 'you have', es: 'tú tienes',
      exampleEn: 'You have a good job.', exampleEs: 'Tú tienes un buen trabajo.' },
    { id: 'he-she-has', en: 'he / she has', es: 'él / ella tiene',
      exampleEn: 'She has three children.', exampleEs: 'Ella tiene tres hijos.' },
    { id: 'we-have', en: 'we have', es: 'nosotros tenemos',
      exampleEn: 'We have a small apartment.', exampleEs: 'Tenemos un apartamento pequeño.' },
    { id: 'they-have', en: 'they have', es: 'ellos tienen',
      exampleEn: 'They have two cars.', exampleEs: 'Ellos tienen dos carros.' },
    { id: 'i-dont-have', en: "I don't have", es: 'no tengo',
      exampleEn: "I don't have a car.", exampleEs: 'No tengo carro.' },
    { id: 'do-you-have', en: 'Do you have...?', es: '¿Tienes...?',
      exampleEn: 'Do you have a pen?', exampleEs: '¿Tienes un lapicero?' },
    { id: 'does-he-she-have', en: 'Does he/she have...?', es: '¿Tiene él/ella...?',
      exampleEn: 'Does she have insurance?', exampleEs: '¿Tiene ella seguro médico?' },
    { id: 'i-have-two-children', en: 'I have two children', es: 'Tengo dos hijos',
      exampleEn: 'I have two children in school.', exampleEs: 'Tengo dos hijos en la escuela.' },
    { id: 'i-have-an-appointment', en: 'I have an appointment', es: 'Tengo una cita',
      exampleEn: 'I have an appointment at 3 o\'clock.', exampleEs: 'Tengo una cita a las 3.' },
    { id: 'i-have-a-headache', en: 'I have a headache', es: 'Tengo dolor de cabeza',
      exampleEn: 'I have a headache today.', exampleEs: 'Tengo dolor de cabeza hoy.' },
    { id: 'i-have-a-job', en: 'I have a job', es: 'Tengo un trabajo',
      exampleEn: 'I have a job in a restaurant.', exampleEs: 'Tengo un trabajo en un restaurante.' },
    { id: 'i-have-a-question', en: 'I have a question', es: 'Tengo una pregunta',
      exampleEn: 'Excuse me, I have a question.', exampleEs: 'Disculpe, tengo una pregunta.' },
    { id: 'i-dont-have-any-money', en: "I don't have any money", es: 'No tengo dinero',
      exampleEn: "I don't have any money with me today.", exampleEs: 'No tengo dinero conmigo hoy.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: '"Tengo" in English is:', promptEs: '"Tengo" en inglés es:',
      answer: 'I have', options: ['I have', 'I am', 'I need', 'I want'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "She ___ two children."', promptEs: 'Completa: "She ___ two children."',
      answer: 'has', options: ['has', 'have', 'is', 'are'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'How do you ask "¿Tienes un lapicero?"', promptEs: '¿Cómo preguntas "¿Tienes un lapicero?"',
      answer: 'Do you have a pen?', options: ['Do you have a pen?', 'Are you a pen?', 'Have you pen?', 'Is you have a pen?'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"Tengo una cita" in English is:', promptEs: '"Tengo una cita" en inglés es:',
      answer: 'I have an appointment', options: ['I have an appointment', 'I have a headache', 'I have a job', 'I have a question'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"No tengo dinero" in English is:', promptEs: '"No tengo dinero" en inglés es:',
      answer: "I don't have any money", options: ["I don't have any money", "I don't have a job", "I have a lot of money", "I need money"] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Talking about your family and belongings',
      text: 'Practice talking about what you have — how many children, whether you have a car, and where you live.' },
    { label: 'Part 2: At the doctor\'s office',
      text: 'Practice telling a receptionist you have an appointment and describing that you have a headache or another common symptom.' },
    { label: 'Part 3: At work or in a store',
      text: 'Practice saying you have a question, telling someone you have a job, or explaining you don\'t have money with you right now.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ two children.', promptEs: 'Tengo dos hijos. (I ____ two children.)', answer: 'have' },
    { id: 'w2', promptEn: 'She ____ a headache.', promptEs: 'Ella tiene dolor de cabeza. (She ____ a headache.)', answer: 'has' },
    { id: 'w3', promptEn: '____ you have a pen?', promptEs: '¿Tienes un lapicero? (____ you have a pen?)', answer: 'Do' },
    { id: 'w4', promptEn: 'I ____ an appointment today.', promptEs: 'Tengo una cita hoy. (I ____ an appointment today.)', answer: 'have' },
    { id: 'w5', promptEn: "I don't ____ any money.", promptEs: 'No tengo dinero. (I don\'t ____ any money.)', answer: 'have' },
  ],
}

export default module
