import type { Module } from '@/types'

const module: Module = {
  slug: 'verb-to-be',
  track: 'esl',
  titleEn: 'The Verb "To Be"',
  titleEs: 'El Verbo "To Be"',
  descriptionEn: 'Learn how to use am, is, and are to talk about who you are and how you feel.',
  descriptionEs: 'Aprende a usar am, is y are para hablar de quién eres y cómo te sientes.',
  icon: 'PersonStanding',
  vocab: [
    { id: 'i-am', en: 'I am', es: 'yo soy / estoy',
      exampleEn: 'I am a student.', exampleEs: 'Yo soy estudiante.' },
    { id: 'you-are', en: 'you are', es: 'tú eres / estás',
      exampleEn: 'You are very kind.', exampleEs: 'Tú eres muy amable.' },
    { id: 'he-she-is', en: 'he / she is', es: 'él / ella es / está',
      exampleEn: 'She is my neighbor.', exampleEs: 'Ella es mi vecina.' },
    { id: 'we-are', en: 'we are', es: 'nosotros somos / estamos',
      exampleEn: 'We are ready.', exampleEs: 'Estamos listos.' },
    { id: 'they-are', en: 'they are', es: 'ellos son / están',
      exampleEn: 'They are from Guatemala.', exampleEs: 'Ellos son de Guatemala.' },
    { id: 'i-am-not', en: 'I am not', es: 'yo no soy / no estoy',
      exampleEn: 'I am not sure.', exampleEs: 'No estoy seguro.' },
    { id: 'is-he-she', en: 'Is he/she...?', es: '¿Es/Está él/ella...?',
      exampleEn: 'Is she your sister?', exampleEs: '¿Es ella tu hermana?' },
    { id: 'are-you', en: 'Are you...?', es: '¿Eres/Estás tú...?',
      exampleEn: 'Are you okay?', exampleEs: '¿Estás bien?' },
    { id: 'i-am-happy', en: 'I am happy', es: 'Estoy feliz',
      exampleEn: 'I am happy today.', exampleEs: 'Estoy feliz hoy.' },
    { id: 'i-am-tired', en: 'I am tired', es: 'Estoy cansado / cansada',
      exampleEn: 'I am tired after work.', exampleEs: 'Estoy cansado después del trabajo.' },
    { id: 'i-am-from', en: 'I am from...', es: 'Soy de...',
      exampleEn: 'I am from Honduras.', exampleEs: 'Soy de Honduras.' },
    { id: 'it-is', en: 'It is...', es: 'Es... / Está...',
      exampleEn: 'It is cold today.', exampleEs: 'Está frío hoy.' },
    { id: 'there-is-are', en: 'There is / there are', es: 'Hay',
      exampleEn: 'There is a bank on this street. There are two children in my family.', exampleEs: 'Hay un banco en esta calle. Hay dos niños en mi familia.' },
    { id: 'contractions', en: "I'm / he isn't / they aren't", es: 'formas cortas de to be',
      exampleEn: "I'm tired. He isn't home. They aren't ready.", exampleEs: 'Estoy cansado. Él no está en casa. Ellos no están listos.' },
  ],
  quiz: [
    { id: 'q1', type: 'multiple-choice', promptEn: 'Complete: "I ___ a student."', promptEs: 'Completa: "I ___ a student."',
      answer: 'am', options: ['am', 'is', 'are', 'be'] },
    { id: 'q2', type: 'multiple-choice', promptEn: 'Complete: "She ___ my sister."', promptEs: 'Completa: "She ___ my sister."',
      answer: 'is', options: ['is', 'am', 'are', 'be'] },
    { id: 'q3', type: 'multiple-choice', promptEn: 'Complete: "They ___ from Guatemala."', promptEs: 'Completa: "They ___ from Guatemala."',
      answer: 'are', options: ['are', 'am', 'is', 'be'] },
    { id: 'q4', type: 'multiple-choice', promptEn: '"¿Estás bien?" in English is:', promptEs: '"¿Estás bien?" en inglés es:',
      answer: 'Are you okay?', options: ['Are you okay?', 'Is you okay?', 'I am okay?', 'You are okay'] },
    { id: 'q5', type: 'multiple-choice', promptEn: '"Hay" in English is:', promptEs: '"Hay" en inglés es:',
      answer: 'There is / there are', options: ['There is / there are', 'It is', 'I am', 'They are'] },
  ],
  teachingScenarios: [
    { label: 'Part 1: Introducing who you are',
      text: 'Practice introducing yourself using "I am" — your name, where you are from, and your job — as if meeting someone new.' },
    { label: 'Part 2: Talking about how you feel',
      text: 'Practice describing how you feel (happy, tired, sick) and asking someone else how they are feeling.' },
    { label: 'Part 3: Talking about the weather and everyday facts',
      text: 'Practice using "It is..." for weather and "There is / there are..." to describe things around you, like a store on your street.' },
  ],
  worksheet: [
    { id: 'w1', promptEn: 'I ____ a student.', promptEs: 'Yo soy estudiante. (I ____ a student.)', answer: 'am' },
    { id: 'w2', promptEn: 'She ____ my sister.', promptEs: 'Ella es mi hermana. (She ____ my sister.)', answer: 'is' },
    { id: 'w3', promptEn: 'They ____ from Guatemala.', promptEs: 'Ellos son de Guatemala. (They ____ from Guatemala.)', answer: 'are' },
    { id: 'w4', promptEn: '____ you okay?', promptEs: '¿Estás bien? (____ you okay?)', answer: 'Are' },
    { id: 'w5', promptEn: 'It ____ cold today.', promptEs: 'Está frío hoy. (It ____ cold today.)', answer: 'is' },
  ],
}

export default module
